// Package steer is the conversation-id-keyed steer/delegation-result queue.
//
// It is Postgres-backed with a per-kind TTL (D-06/D-07, migration 0103): a steer or a
// delegation_result row survives a daemon restart, so a background completion pushed
// while no turn is running -- the normal case for a delegation that outlives its parent
// turn -- is delivered on the next turn the operator opens on that conversation, never
// silently lost. It is keyed on conversation id, never run id, because the Telegram
// dispatch path calls runner.Turn directly with no run identity in scope at all (D-01) --
// a run-id-keyed inbox would be unreachable from that half of the callers by
// construction.
//
// It is NOT internal/agui's RunRegistry: no SSE fan-out, no subscriber set, no
// replay-from-seq. A row is consumed by Drain, never replayed. The in-memory,
// single-replica-by-construction *Inbox* this package shipped before Phase 51 is
// DELETED, not kept behind a flag (D-06: "two live implementations of one contract" was
// explicitly rejected) -- *PostgresStore (pg_store.go) is the sole implementation.
package steer

import (
	"errors"
	"time"
)

// defaultMax and defaultMaxBytes are the package-level fallbacks a non-positive Config
// cap resolves to — the same <=0 → default convention agui.NewRunRegistry uses.
// Deliberately NOT the ratified amendment #132 item 10 numbers: those live in
// config.AGUISteerConfig and arrive through Config, never as a literal in this file (a
// D-11-shaped drift guard).
const (
	defaultMax      = 32
	defaultMaxBytes = 32768
)

// Sentinel errors returned by Push, one per validation reason, so a caller (the AG-UI
// HTTP route, the Telegram reply) can render each without string matching.
var (
	ErrEmpty     = errors.New("steer: message is empty")
	ErrTooLarge  = errors.New("steer: message exceeds max size")
	ErrQueueFull = errors.New("steer: conversation queue is full")
	// ErrClosed is preserved for the shipped writeSteerRefusal switch
	// (internal/agui/server_run_steer.go) to keep compiling and rendering its ratified
	// 410 branch. *PostgresStore never returns it: there is no "closed" state for a
	// process-wide Postgres-backed store the way there was for the in-memory Inbox's
	// explicit Close() (never called in production — grepped clean across the tree at
	// the time of the D-06 migration). It stays defined, not reachable, rather than
	// deleted, exactly as CLAUDE.md's "adapt the new type to the shipped contract"
	// prohibition on widening/narrowing that switch requires.
	ErrClosed = errors.New("steer: inbox is closed")
)

// SourceWorker is the reserved source a DELEGATED WORKER's report arrives under, as
// opposed to the channel names an operator's own steer carries ("cockpit", "telegram").
// The consumer keys the delivery envelope on it: spike 098 measured that a worker's
// report wrapped in the operator envelope is discounted by the model as a spoofing
// attempt, because the envelope declares an author the payload contradicts. Also the
// storage source label. PostgresStore.PushDelegationResult explicitly selects the
// delegation-result kind; PostgresStore.Push writes KindSteer even for worker questions.
//
// It matches the Source the swarm already stamps on its own tool results
// (RunnerAdapter's Provenance{Source: "swarm", Trust: TrustUntrusted}), so one name
// means one thing whichever way a worker's output reaches the model.
const SourceWorker = "swarm"

// SourceShell is the reserved source for a background shell's terminal runtime
// fact. Like SourceWorker it is generated by Aura, not typed by the operator, so
// the agent must carry it in the untrusted tool-output envelope. Unlike a worker
// report it remains KindSteer in Postgres: it is a short process-lifecycle nudge,
// not a delegation result with fan-out/nudge semantics.
const SourceShell = "shell"

// Message is one steer or delegation-result row, carrying the minimum provenance the
// aura.steer echo frame needs: an id, the source channel, and the arrival time. A small
// value type, not an interface.
type Message struct {
	ID      string
	Source  string
	Text    string
	Arrived time.Time
}

// Config bundles the caps PostgresStore is configured with — this package's mirror of
// config.AGUISteerConfig's Max/MaxBytes fields plus the D-07 per-kind TTLs, kept
// separate so this package never imports internal/config; the composition root
// converts.
type Config struct {
	Max      int // queued-and-undrained-row cap per conversation (both kinds combined); <=0 resolves to a package default
	MaxBytes int // per-message byte cap (Unicode-encoded byte length, not rune count); <=0 resolves to a package default
	// SteerTTL/DelegationResultTTL are the D-07 per-kind TTLs a row's expires_at is
	// derived from at Push time. <=0 explicitly disables expiry for that kind — the
	// shipped AURA_ASKUSER_PAUSE_TTL_SEC precedent, never a silent fall-through to
	// "never expires" by omission.
	SteerTTL            time.Duration
	DelegationResultTTL time.Duration
}
