// Hand-written to mirror internal/api/types.go. Drift detection is by feel
// — runtime parsing failures are visible because polling exercises every
// endpoint. If drift becomes painful, swap in tygo Go→TS codegen.

// Slice 12m — compounding-rate metric.
export interface CompoundingRate {
  auto_added_7d: number;
  total_pages: number;
  rate_pct: number;
}

export interface HealthRollup {
  process: {
    version: string;
    git_revision?: string;
    started_at: string;
    uptime_seconds: number;
  };
  wiki: { pages: number; last_update: string };
  sources: { by_status: Record<string, number> };
  tasks: { by_status: Record<string, number> };
  scheduler: { next_run: string | null };
  // Slice 11j — embedding cache hit/miss counters since process start.
  // Both zero when no cache is wired.
  embed_cache: { hits: number; misses: number };
  // Slice 12m — optional: zero-value struct always present in 12i+ builds.
  compounding_rate?: CompoundingRate;
}

export interface WikiPageSummary {
  slug: string;
  title: string;
  category?: string;
  tags?: string[];
  updated_at: string;
}

export interface WikiPage {
  slug: string;
  title: string;
  body_md: string;
  frontmatter: Record<string, unknown>;
}

export interface GraphNode {
  id: string;
  title: string;
  category?: string;
}

export interface GraphEdge {
  source: string;
  target: string;
  type: 'wikilink' | 'related';
}

export interface Graph {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

export interface SourceSummary {
  id: string;
  // 'xlsx' is generated by create_xlsx (slice 15a) — same store layout
  // as user-uploaded PDFs, just a different ext + raw download flow.
  kind: 'pdf' | 'text' | 'url' | 'xlsx';
  filename: string;
  status: 'stored' | 'ocr_complete' | 'ingested' | 'failed';
  created_at: string;
  page_count?: number;
  wiki_pages?: string[];
}

export interface SourceDetail extends SourceSummary {
  mime_type?: string;
  sha256: string;
  size_bytes: number;
  ocr_model?: string;
  error?: string;
}

export interface UploadResponse {
  id: string;
  status: SourceSummary['status'];
  duplicate: boolean;
  filename: string;
  page_count?: number;
  wiki_pages?: string[];
  ingest_note?: string;
  ocr_error?: string;
  note?: string;
}

export interface IngestResponse {
  id: string;
  status: SourceSummary['status'];
  filename: string;
  wiki_pages?: string[];
  ingest_note?: string;
  note?: string;
}

export interface ReocrResponse {
  id: string;
  status: SourceSummary['status'];
  filename: string;
  page_count?: number;
  wiki_pages?: string[];
  ingest_note?: string;
  ocr_error?: string;
  note?: string;
}

export interface UpsertTaskRequest {
  name: string;
  kind: Task['kind'];
  payload?: string;
  recipient_id?: string;
  at?: string; // RFC3339 UTC
  daily?: string; // HH:MM (bot's local TZ)
  every_minutes?: number; // recurrence: fires every N minutes (>=1)
}

export interface WhoamiResponse {
  user_id: string;
}

// Slice 11b — skills + MCP read surfaces.

export interface SkillSummary {
  name: string;
  description?: string;
}

export interface SkillDetail {
  name: string;
  description?: string;
  content: string;
  truncated?: boolean;
}

export interface MCPToolInfo {
  name: string;
  description?: string;
  input_schema?: Record<string, unknown>;
}

export interface MCPServerSummary {
  name: string;
  transport: 'stdio' | 'http';
  tool_count: number;
  tools: MCPToolInfo[];
}

// Slice 11c — skills.sh catalog + admin-gated install/delete.

export interface SkillCatalogItem {
  source: string;
  skill_id?: string;
  name: string;
  installs: number;
  install_command?: string;
}

export interface SkillInstallRequest {
  source: string;
  skill_id?: string;
}

export interface SkillInstallResponse {
  ok: boolean;
  output?: string;
  error?: string;
}

export interface SkillDeleteResponse {
  ok: boolean;
  name: string;
}

// Slice 11d — invoke MCP tools from the dashboard.
export interface MCPInvokeResponse {
  ok: boolean;
  is_error?: boolean;
  output?: string;
  error?: string;
}

// Pending access requests. The list endpoint is gated by the dashboard
// bearer token, so by the time the frontend sees these the requester has
// already been queued by the bot's /start handler.
export interface PendingUserSummary {
  user_id: string;
  username?: string;
  requested_at: string;
}

export interface PendingDecisionResponse {
  ok: boolean;
  user_id: string;
}

// Slice 12j — conversation archive read surface.

export interface ConversationTurn {
  id: number;
  chat_id: number;
  user_id: number;
  turn_index: number;
  role: string;
  content: string;
  tool_calls?: string;
  tool_call_id?: string;
  llm_calls?: number;
  tool_calls_count?: number;
  elapsed_ms?: number;
  tokens_in?: number;
  tokens_out?: number;
  created_at: string;
}

export interface ConversationDetail {
  id: number;
  chat_id: number;
  user_id: number;
  turn_index: number;
  role: string;
  content: string;
  tool_calls?: string;
  tool_call_id?: string;
  llm_calls?: number;
  tool_calls_count?: number;
  elapsed_ms?: number;
  tokens_in?: number;
  tokens_out?: number;
  created_at: string;
}

// Slice 12l — wiki maintenance issue queue.

export interface WikiIssue {
  id: number;
  kind: string;
  severity: 'high' | 'medium' | 'low';
  slug?: string;
  broken_link?: string;
  message?: string;
  status: 'open' | 'resolved';
  created_at: string;
  resolved_at?: string;
}

// Slice 12k — summarizer proposed updates review queue.

export interface ProposedUpdate {
  id: number;
  chat_id: number;
  fact: string;
  action: 'new' | 'patch' | 'skip';
  target_slug?: string;
  similarity: number;
  source_turn_ids: number[];
  status: 'pending' | 'approved' | 'rejected';
  created_at: string;
}

export interface Task {
  name: string;
  kind: 'reminder' | 'wiki_maintenance';
  payload?: string;
  recipient_id?: string;
  schedule_kind: 'at' | 'daily' | 'every';
  schedule_at?: string;
  schedule_daily?: string;
  schedule_every_minutes?: number;
  next_run_at: string;
  last_run_at?: string;
  last_error?: string;
  status: 'active' | 'done' | 'cancelled' | 'failed';
  created_at: string;
  updated_at: string;
}

// Slice 14d — runtime settings page.
//
// `source` tells the UI where the effective `value` came from:
//   - "db"      : a row exists in aura.db (this is what the dashboard owns).
//   - "env"     : the bot loaded it from .env at startup; saving here
//                  promotes it to a DB row that overrides env on next boot.
//   - "default" : neither set; the bot is using the in-code default.
//
// `kind` hints which input control to render. Defaults to "text".
export type SettingKind = 'text' | 'bool' | 'int' | 'float' | 'enum' | 'url';

export interface SettingItem {
  key: string;
  value: string;
  source: 'db' | 'env' | 'default';
  is_secret: boolean;
  kind?: SettingKind;
  options?: string[]; // present when kind === 'enum'
  label?: string;
  hint?: string;
  group?: 'provider' | 'embeddings' | 'ocr' | 'budget' | 'summarizer' | 'other';
}
