// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adaptive_policy.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adaptiveEvidenceTransactionTime = `-- name: AdaptiveEvidenceTransactionTime :one
SELECT transaction_timestamp()::timestamptz AS evidence_time
`

func (q *Queries) AdaptiveEvidenceTransactionTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, adaptiveEvidenceTransactionTime)
	var evidence_time pgtype.Timestamptz
	err := row.Scan(&evidence_time)
	return evidence_time, err
}

const applyAdaptivePolicyTransition = `-- name: ApplyAdaptivePolicyTransition :one
WITH applied AS MATERIALIZED (
    SELECT aura.apply_adaptive_policy_transition(
        $1, $2, $3,
        $4, $5
    ) AS result
)
SELECT policy.epoch, policy.policy_version, policy.mode,
       policy.rollout_bps, policy.config, policy.updated_at
FROM (
    SELECT
        (to_jsonb(applied.result)->>'epoch')::bigint AS epoch,
        (to_jsonb(applied.result)->>'policy_version')::text AS policy_version,
        (to_jsonb(applied.result)->>'mode')::text AS mode,
        (to_jsonb(applied.result)->>'rollout_bps')::integer AS rollout_bps,
        (to_jsonb(applied.result)->'config')::jsonb AS config,
        (to_jsonb(applied.result)->>'updated_at')::timestamptz AS updated_at
    FROM applied
) AS policy
`

type ApplyAdaptivePolicyTransitionParams struct {
	ActorID       pgtype.UUID `json:"actor_id"`
	ExpectedEpoch int64       `json:"expected_epoch"`
	EvidenceID    pgtype.UUID `json:"evidence_id"`
	RolloutBps    int32       `json:"rollout_bps"`
	Reason        string      `json:"reason"`
}

type ApplyAdaptivePolicyTransitionRow struct {
	Epoch         int64              `json:"epoch"`
	PolicyVersion string             `json:"policy_version"`
	Mode          string             `json:"mode"`
	RolloutBps    int32              `json:"rollout_bps"`
	Config        []byte             `json:"config"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ApplyAdaptivePolicyTransition(ctx context.Context, arg ApplyAdaptivePolicyTransitionParams) (ApplyAdaptivePolicyTransitionRow, error) {
	row := q.db.QueryRow(ctx, applyAdaptivePolicyTransition,
		arg.ActorID,
		arg.ExpectedEpoch,
		arg.EvidenceID,
		arg.RolloutBps,
		arg.Reason,
	)
	var i ApplyAdaptivePolicyTransitionRow
	err := row.Scan(
		&i.Epoch,
		&i.PolicyVersion,
		&i.Mode,
		&i.RolloutBps,
		&i.Config,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdaptiveEvidenceArtifact = `-- name: GetAdaptiveEvidenceArtifact :one
SELECT id, owner_id, cohort_id, kind, schema_id, revision,
       sha256, artifact, artifact_json, created_at
FROM aura.adaptive_evidence_artifacts
WHERE owner_id = $1
  AND cohort_id = $2
  AND id = $3
  AND kind = $4
`

type GetAdaptiveEvidenceArtifactParams struct {
	OwnerID    pgtype.UUID `json:"owner_id"`
	CohortID   pgtype.UUID `json:"cohort_id"`
	ArtifactID pgtype.UUID `json:"artifact_id"`
	Kind       string      `json:"kind"`
}

func (q *Queries) GetAdaptiveEvidenceArtifact(ctx context.Context, arg GetAdaptiveEvidenceArtifactParams) (AuraAdaptiveEvidenceArtifacts, error) {
	row := q.db.QueryRow(ctx, getAdaptiveEvidenceArtifact,
		arg.OwnerID,
		arg.CohortID,
		arg.ArtifactID,
		arg.Kind,
	)
	var i AuraAdaptiveEvidenceArtifacts
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CohortID,
		&i.Kind,
		&i.SchemaID,
		&i.Revision,
		&i.Sha256,
		&i.Artifact,
		&i.ArtifactJson,
		&i.CreatedAt,
	)
	return i, err
}

const getAdaptivePolicy = `-- name: GetAdaptivePolicy :one
SELECT epoch, policy_version, mode, rollout_bps, config, updated_at
FROM aura.adaptive_policy_state
WHERE scope = 'global'
`

type GetAdaptivePolicyRow struct {
	Epoch         int64              `json:"epoch"`
	PolicyVersion string             `json:"policy_version"`
	Mode          string             `json:"mode"`
	RolloutBps    int32              `json:"rollout_bps"`
	Config        []byte             `json:"config"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAdaptivePolicy(ctx context.Context) (GetAdaptivePolicyRow, error) {
	row := q.db.QueryRow(ctx, getAdaptivePolicy)
	var i GetAdaptivePolicyRow
	err := row.Scan(
		&i.Epoch,
		&i.PolicyVersion,
		&i.Mode,
		&i.RolloutBps,
		&i.Config,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdaptiveSealedAdmission = `-- name: GetAdaptiveSealedAdmission :one
SELECT id, kind, owner_id, cohort_id, cohort_sha256, domain, provider_id,
       model_id, policy_epoch, policy_version, snapshot_id, snapshot_sha256,
       look_number, look_cutoff, predecessor_evidence_id, predecessor_sha256,
       disposition, eligible, body_sha256, sha256, artifact, artifact_json,
       sealer_actor_id, sealer_capability, created_at
FROM aura.adaptive_sealed_evidence
WHERE owner_id = $1
  AND cohort_id = $2
  AND kind = 'canary_admission'
`

type GetAdaptiveSealedAdmissionParams struct {
	OwnerID  pgtype.UUID `json:"owner_id"`
	CohortID pgtype.UUID `json:"cohort_id"`
}

func (q *Queries) GetAdaptiveSealedAdmission(ctx context.Context, arg GetAdaptiveSealedAdmissionParams) (AuraAdaptiveSealedEvidence, error) {
	row := q.db.QueryRow(ctx, getAdaptiveSealedAdmission, arg.OwnerID, arg.CohortID)
	var i AuraAdaptiveSealedEvidence
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerID,
		&i.CohortID,
		&i.CohortSha256,
		&i.Domain,
		&i.ProviderID,
		&i.ModelID,
		&i.PolicyEpoch,
		&i.PolicyVersion,
		&i.SnapshotID,
		&i.SnapshotSha256,
		&i.LookNumber,
		&i.LookCutoff,
		&i.PredecessorEvidenceID,
		&i.PredecessorSha256,
		&i.Disposition,
		&i.Eligible,
		&i.BodySha256,
		&i.Sha256,
		&i.Artifact,
		&i.ArtifactJson,
		&i.SealerActorID,
		&i.SealerCapability,
		&i.CreatedAt,
	)
	return i, err
}

const getAdaptiveSealedEvidence = `-- name: GetAdaptiveSealedEvidence :one
SELECT id, kind, owner_id, cohort_id, cohort_sha256, domain, provider_id,
       model_id, policy_epoch, policy_version, snapshot_id, snapshot_sha256,
       look_number, look_cutoff, predecessor_evidence_id, predecessor_sha256,
       disposition, eligible, body_sha256, sha256, artifact, artifact_json,
       sealer_actor_id, sealer_capability, created_at
FROM aura.adaptive_sealed_evidence
WHERE owner_id = $1
  AND id = $2
`

type GetAdaptiveSealedEvidenceParams struct {
	OwnerID    pgtype.UUID `json:"owner_id"`
	EvidenceID pgtype.UUID `json:"evidence_id"`
}

func (q *Queries) GetAdaptiveSealedEvidence(ctx context.Context, arg GetAdaptiveSealedEvidenceParams) (AuraAdaptiveSealedEvidence, error) {
	row := q.db.QueryRow(ctx, getAdaptiveSealedEvidence, arg.OwnerID, arg.EvidenceID)
	var i AuraAdaptiveSealedEvidence
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerID,
		&i.CohortID,
		&i.CohortSha256,
		&i.Domain,
		&i.ProviderID,
		&i.ModelID,
		&i.PolicyEpoch,
		&i.PolicyVersion,
		&i.SnapshotID,
		&i.SnapshotSha256,
		&i.LookNumber,
		&i.LookCutoff,
		&i.PredecessorEvidenceID,
		&i.PredecessorSha256,
		&i.Disposition,
		&i.Eligible,
		&i.BodySha256,
		&i.Sha256,
		&i.Artifact,
		&i.ArtifactJson,
		&i.SealerActorID,
		&i.SealerCapability,
		&i.CreatedAt,
	)
	return i, err
}

const getAdaptiveSealedOutcomeLook = `-- name: GetAdaptiveSealedOutcomeLook :one
SELECT id, kind, owner_id, cohort_id, cohort_sha256, domain, provider_id,
       model_id, policy_epoch, policy_version, snapshot_id, snapshot_sha256,
       look_number, look_cutoff, predecessor_evidence_id, predecessor_sha256,
       disposition, eligible, body_sha256, sha256, artifact, artifact_json,
       sealer_actor_id, sealer_capability, created_at
FROM aura.adaptive_sealed_evidence
WHERE owner_id = $1
  AND cohort_id = $2
  AND kind = 'canary_outcome'
  AND look_number = $3
`

type GetAdaptiveSealedOutcomeLookParams struct {
	OwnerID    pgtype.UUID `json:"owner_id"`
	CohortID   pgtype.UUID `json:"cohort_id"`
	LookNumber pgtype.Int4 `json:"look_number"`
}

func (q *Queries) GetAdaptiveSealedOutcomeLook(ctx context.Context, arg GetAdaptiveSealedOutcomeLookParams) (AuraAdaptiveSealedEvidence, error) {
	row := q.db.QueryRow(ctx, getAdaptiveSealedOutcomeLook, arg.OwnerID, arg.CohortID, arg.LookNumber)
	var i AuraAdaptiveSealedEvidence
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerID,
		&i.CohortID,
		&i.CohortSha256,
		&i.Domain,
		&i.ProviderID,
		&i.ModelID,
		&i.PolicyEpoch,
		&i.PolicyVersion,
		&i.SnapshotID,
		&i.SnapshotSha256,
		&i.LookNumber,
		&i.LookCutoff,
		&i.PredecessorEvidenceID,
		&i.PredecessorSha256,
		&i.Disposition,
		&i.Eligible,
		&i.BodySha256,
		&i.Sha256,
		&i.Artifact,
		&i.ArtifactJson,
		&i.SealerActorID,
		&i.SealerCapability,
		&i.CreatedAt,
	)
	return i, err
}

const insertAdaptiveRandomizationReceipt = `-- name: InsertAdaptiveRandomizationReceipt :one
INSERT INTO aura.adaptive_randomization_receipts (
    id, owner_id, cohort_id, request_id, claim_id, assignment_id,
    randomization_plan_sha256, analysis_stratum_schema_sha256,
    analysis_stratum_id, sha256, artifact, artifact_json
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7,
    $8,
    $9, $10,
    $11, $12
)
ON CONFLICT (owner_id, assignment_id) DO NOTHING
RETURNING id, owner_id, cohort_id, request_id, claim_id, assignment_id,
          randomization_plan_sha256, analysis_stratum_schema_sha256,
          analysis_stratum_id, sha256, artifact, artifact_json, created_at
`

type InsertAdaptiveRandomizationReceiptParams struct {
	ReceiptID                   pgtype.UUID `json:"receipt_id"`
	OwnerID                     pgtype.UUID `json:"owner_id"`
	CohortID                    pgtype.UUID `json:"cohort_id"`
	RequestID                   pgtype.UUID `json:"request_id"`
	ClaimID                     pgtype.UUID `json:"claim_id"`
	AssignmentID                pgtype.UUID `json:"assignment_id"`
	RandomizationPlanSha256     []byte      `json:"randomization_plan_sha256"`
	AnalysisStratumSchemaSha256 []byte      `json:"analysis_stratum_schema_sha256"`
	AnalysisStratumID           []byte      `json:"analysis_stratum_id"`
	ReceiptSha256               []byte      `json:"receipt_sha256"`
	Artifact                    []byte      `json:"artifact"`
	ArtifactJson                []byte      `json:"artifact_json"`
}

func (q *Queries) InsertAdaptiveRandomizationReceipt(ctx context.Context, arg InsertAdaptiveRandomizationReceiptParams) (AuraAdaptiveRandomizationReceipts, error) {
	row := q.db.QueryRow(ctx, insertAdaptiveRandomizationReceipt,
		arg.ReceiptID,
		arg.OwnerID,
		arg.CohortID,
		arg.RequestID,
		arg.ClaimID,
		arg.AssignmentID,
		arg.RandomizationPlanSha256,
		arg.AnalysisStratumSchemaSha256,
		arg.AnalysisStratumID,
		arg.ReceiptSha256,
		arg.Artifact,
		arg.ArtifactJson,
	)
	var i AuraAdaptiveRandomizationReceipts
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CohortID,
		&i.RequestID,
		&i.ClaimID,
		&i.AssignmentID,
		&i.RandomizationPlanSha256,
		&i.AnalysisStratumSchemaSha256,
		&i.AnalysisStratumID,
		&i.Sha256,
		&i.Artifact,
		&i.ArtifactJson,
		&i.CreatedAt,
	)
	return i, err
}

const listAdaptiveEvidenceArtifactsByKind = `-- name: ListAdaptiveEvidenceArtifactsByKind :many
SELECT id, owner_id, cohort_id, kind, schema_id, revision,
       sha256, artifact, artifact_json, created_at
FROM aura.adaptive_evidence_artifacts
WHERE owner_id = $1
  AND cohort_id = $2
  AND kind = $3
ORDER BY id
`

type ListAdaptiveEvidenceArtifactsByKindParams struct {
	OwnerID  pgtype.UUID `json:"owner_id"`
	CohortID pgtype.UUID `json:"cohort_id"`
	Kind     string      `json:"kind"`
}

func (q *Queries) ListAdaptiveEvidenceArtifactsByKind(ctx context.Context, arg ListAdaptiveEvidenceArtifactsByKindParams) ([]AuraAdaptiveEvidenceArtifacts, error) {
	rows, err := q.db.Query(ctx, listAdaptiveEvidenceArtifactsByKind, arg.OwnerID, arg.CohortID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraAdaptiveEvidenceArtifacts{}
	for rows.Next() {
		var i AuraAdaptiveEvidenceArtifacts
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.CohortID,
			&i.Kind,
			&i.SchemaID,
			&i.Revision,
			&i.Sha256,
			&i.Artifact,
			&i.ArtifactJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAdaptiveRandomizationReceipt = `-- name: LockAdaptiveRandomizationReceipt :one
SELECT id, owner_id, cohort_id, request_id, claim_id, assignment_id,
       randomization_plan_sha256, analysis_stratum_schema_sha256,
       analysis_stratum_id, sha256, artifact, artifact_json, created_at
FROM aura.adaptive_randomization_receipts
WHERE owner_id = $1
  AND assignment_id = $2
`

type LockAdaptiveRandomizationReceiptParams struct {
	OwnerID      pgtype.UUID `json:"owner_id"`
	AssignmentID pgtype.UUID `json:"assignment_id"`
}

func (q *Queries) LockAdaptiveRandomizationReceipt(ctx context.Context, arg LockAdaptiveRandomizationReceiptParams) (AuraAdaptiveRandomizationReceipts, error) {
	row := q.db.QueryRow(ctx, lockAdaptiveRandomizationReceipt, arg.OwnerID, arg.AssignmentID)
	var i AuraAdaptiveRandomizationReceipts
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CohortID,
		&i.RequestID,
		&i.ClaimID,
		&i.AssignmentID,
		&i.RandomizationPlanSha256,
		&i.AnalysisStratumSchemaSha256,
		&i.AnalysisStratumID,
		&i.Sha256,
		&i.Artifact,
		&i.ArtifactJson,
		&i.CreatedAt,
	)
	return i, err
}

const sealAdaptiveEvidence = `-- name: SealAdaptiveEvidence :one
SELECT id, kind, owner_id, cohort_id, cohort_sha256, domain, provider_id, model_id, policy_epoch, policy_version, snapshot_id, snapshot_sha256, look_number, look_cutoff, predecessor_evidence_id, predecessor_sha256, disposition, eligible, body_sha256, sha256, artifact, artifact_json, sealer_actor_id, sealer_capability, created_at
FROM aura.seal_adaptive_evidence(
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11,
    $12, $13,
    $14, $15,
    $16, $17,
    $18, $19,
    $20, $21,
    $22, $23,
    $24
)
`

type SealAdaptiveEvidenceParams struct {
	ActorID               pgtype.UUID        `json:"actor_id"`
	Kind                  string             `json:"kind"`
	EvidenceID            pgtype.UUID        `json:"evidence_id"`
	OwnerID               pgtype.UUID        `json:"owner_id"`
	CohortID              pgtype.UUID        `json:"cohort_id"`
	CohortSha256          []byte             `json:"cohort_sha256"`
	Domain                string             `json:"domain"`
	ProviderID            string             `json:"provider_id"`
	ModelID               string             `json:"model_id"`
	PolicyEpoch           int64              `json:"policy_epoch"`
	PolicyVersion         string             `json:"policy_version"`
	SnapshotID            pgtype.UUID        `json:"snapshot_id"`
	SnapshotSha256        []byte             `json:"snapshot_sha256"`
	LookNumber            pgtype.Int4        `json:"look_number"`
	LookCutoff            pgtype.Timestamptz `json:"look_cutoff"`
	PredecessorEvidenceID pgtype.UUID        `json:"predecessor_evidence_id"`
	PredecessorSha256     []byte             `json:"predecessor_sha256"`
	Disposition           pgtype.Text        `json:"disposition"`
	Eligible              bool               `json:"eligible"`
	BodySha256            []byte             `json:"body_sha256"`
	EvidenceSha256        []byte             `json:"evidence_sha256"`
	Artifact              []byte             `json:"artifact"`
	ArtifactJson          []byte             `json:"artifact_json"`
	SealerCapability      string             `json:"sealer_capability"`
}

func (q *Queries) SealAdaptiveEvidence(ctx context.Context, arg SealAdaptiveEvidenceParams) (AuraAdaptiveSealedEvidence, error) {
	row := q.db.QueryRow(ctx, sealAdaptiveEvidence,
		arg.ActorID,
		arg.Kind,
		arg.EvidenceID,
		arg.OwnerID,
		arg.CohortID,
		arg.CohortSha256,
		arg.Domain,
		arg.ProviderID,
		arg.ModelID,
		arg.PolicyEpoch,
		arg.PolicyVersion,
		arg.SnapshotID,
		arg.SnapshotSha256,
		arg.LookNumber,
		arg.LookCutoff,
		arg.PredecessorEvidenceID,
		arg.PredecessorSha256,
		arg.Disposition,
		arg.Eligible,
		arg.BodySha256,
		arg.EvidenceSha256,
		arg.Artifact,
		arg.ArtifactJson,
		arg.SealerCapability,
	)
	var i AuraAdaptiveSealedEvidence
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerID,
		&i.CohortID,
		&i.CohortSha256,
		&i.Domain,
		&i.ProviderID,
		&i.ModelID,
		&i.PolicyEpoch,
		&i.PolicyVersion,
		&i.SnapshotID,
		&i.SnapshotSha256,
		&i.LookNumber,
		&i.LookCutoff,
		&i.PredecessorEvidenceID,
		&i.PredecessorSha256,
		&i.Disposition,
		&i.Eligible,
		&i.BodySha256,
		&i.Sha256,
		&i.Artifact,
		&i.ArtifactJson,
		&i.SealerActorID,
		&i.SealerCapability,
		&i.CreatedAt,
	)
	return i, err
}

const storeAdaptiveEvidenceArtifact = `-- name: StoreAdaptiveEvidenceArtifact :one
SELECT id, owner_id, cohort_id, kind, schema_id, revision, sha256, artifact, artifact_json, created_at
FROM aura.store_adaptive_evidence_artifact(
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10
)
`

type StoreAdaptiveEvidenceArtifactParams struct {
	ActorID        pgtype.UUID `json:"actor_id"`
	OwnerID        pgtype.UUID `json:"owner_id"`
	CohortID       pgtype.UUID `json:"cohort_id"`
	Kind           string      `json:"kind"`
	ArtifactID     pgtype.UUID `json:"artifact_id"`
	SchemaID       string      `json:"schema_id"`
	Revision       int32       `json:"revision"`
	ArtifactSha256 []byte      `json:"artifact_sha256"`
	Artifact       []byte      `json:"artifact"`
	ArtifactJson   []byte      `json:"artifact_json"`
}

func (q *Queries) StoreAdaptiveEvidenceArtifact(ctx context.Context, arg StoreAdaptiveEvidenceArtifactParams) (AuraAdaptiveEvidenceArtifacts, error) {
	row := q.db.QueryRow(ctx, storeAdaptiveEvidenceArtifact,
		arg.ActorID,
		arg.OwnerID,
		arg.CohortID,
		arg.Kind,
		arg.ArtifactID,
		arg.SchemaID,
		arg.Revision,
		arg.ArtifactSha256,
		arg.Artifact,
		arg.ArtifactJson,
	)
	var i AuraAdaptiveEvidenceArtifacts
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CohortID,
		&i.Kind,
		&i.SchemaID,
		&i.Revision,
		&i.Sha256,
		&i.Artifact,
		&i.ArtifactJson,
		&i.CreatedAt,
	)
	return i, err
}
