// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adaptive_cohorts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adaptiveCohortReconstructionTime = `-- name: AdaptiveCohortReconstructionTime :one
SELECT statement_timestamp()::timestamptz AS closure_time
`

func (q *Queries) AdaptiveCohortReconstructionTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, adaptiveCohortReconstructionTime)
	var closure_time pgtype.Timestamptz
	err := row.Scan(&closure_time)
	return closure_time, err
}

const getAdaptiveFocalCohort = `-- name: GetAdaptiveFocalCohort :one
SELECT id, owner_id, provider_id, model_id, policy_epoch, policy_version,
       snapshot_id, snapshot_sha256, environment, domain, decision_point,
       point_ordinal, predicate_sha256, experiment_id, cutoff, sha256,
       artifact, artifact_json, created_at
FROM aura.adaptive_focal_cohorts
WHERE owner_id = $1
  AND id = $2
`

type GetAdaptiveFocalCohortParams struct {
	OwnerID  pgtype.UUID `json:"owner_id"`
	CohortID pgtype.UUID `json:"cohort_id"`
}

func (q *Queries) GetAdaptiveFocalCohort(ctx context.Context, arg GetAdaptiveFocalCohortParams) (AuraAdaptiveFocalCohorts, error) {
	row := q.db.QueryRow(ctx, getAdaptiveFocalCohort, arg.OwnerID, arg.CohortID)
	var i AuraAdaptiveFocalCohorts
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ProviderID,
		&i.ModelID,
		&i.PolicyEpoch,
		&i.PolicyVersion,
		&i.SnapshotID,
		&i.SnapshotSha256,
		&i.Environment,
		&i.Domain,
		&i.DecisionPoint,
		&i.PointOrdinal,
		&i.PredicateSha256,
		&i.ExperimentID,
		&i.Cutoff,
		&i.Sha256,
		&i.Artifact,
		&i.ArtifactJson,
		&i.CreatedAt,
	)
	return i, err
}

const getAdaptiveFocalCohortForReconstruction = `-- name: GetAdaptiveFocalCohortForReconstruction :one
SELECT id, owner_id, provider_id, model_id, policy_epoch, policy_version,
       snapshot_id, snapshot_sha256, environment, domain, decision_point,
       point_ordinal, predicate_sha256, experiment_id, cutoff, sha256,
       artifact, artifact_json, created_at
FROM aura.adaptive_focal_cohorts
WHERE owner_id = $1
  AND id = $2
`

type GetAdaptiveFocalCohortForReconstructionParams struct {
	OwnerID  pgtype.UUID `json:"owner_id"`
	CohortID pgtype.UUID `json:"cohort_id"`
}

func (q *Queries) GetAdaptiveFocalCohortForReconstruction(ctx context.Context, arg GetAdaptiveFocalCohortForReconstructionParams) (AuraAdaptiveFocalCohorts, error) {
	row := q.db.QueryRow(ctx, getAdaptiveFocalCohortForReconstruction, arg.OwnerID, arg.CohortID)
	var i AuraAdaptiveFocalCohorts
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ProviderID,
		&i.ModelID,
		&i.PolicyEpoch,
		&i.PolicyVersion,
		&i.SnapshotID,
		&i.SnapshotSha256,
		&i.Environment,
		&i.Domain,
		&i.DecisionPoint,
		&i.PointOrdinal,
		&i.PredicateSha256,
		&i.ExperimentID,
		&i.Cutoff,
		&i.Sha256,
		&i.Artifact,
		&i.ArtifactJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertAdaptiveFocalCohort = `-- name: InsertAdaptiveFocalCohort :execrows
INSERT INTO aura.adaptive_focal_cohorts (
    id, owner_id, provider_id, model_id, policy_epoch, policy_version,
    snapshot_id, snapshot_sha256, environment, domain, decision_point,
    point_ordinal, predicate_sha256, experiment_id, cutoff, sha256,
    artifact, artifact_json
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15,
    $16, $17, $18
)
ON CONFLICT (id) DO NOTHING
`

type InsertAdaptiveFocalCohortParams struct {
	CohortID        pgtype.UUID        `json:"cohort_id"`
	OwnerID         pgtype.UUID        `json:"owner_id"`
	ProviderID      string             `json:"provider_id"`
	ModelID         string             `json:"model_id"`
	PolicyEpoch     int64              `json:"policy_epoch"`
	PolicyVersion   string             `json:"policy_version"`
	SnapshotID      pgtype.UUID        `json:"snapshot_id"`
	SnapshotSha256  []byte             `json:"snapshot_sha256"`
	Environment     string             `json:"environment"`
	Domain          string             `json:"domain"`
	DecisionPoint   string             `json:"decision_point"`
	PointOrdinal    int64              `json:"point_ordinal"`
	PredicateSha256 []byte             `json:"predicate_sha256"`
	ExperimentID    string             `json:"experiment_id"`
	Cutoff          pgtype.Timestamptz `json:"cutoff"`
	CohortSha256    []byte             `json:"cohort_sha256"`
	Artifact        []byte             `json:"artifact"`
	ArtifactJson    []byte             `json:"artifact_json"`
}

func (q *Queries) InsertAdaptiveFocalCohort(ctx context.Context, arg InsertAdaptiveFocalCohortParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAdaptiveFocalCohort,
		arg.CohortID,
		arg.OwnerID,
		arg.ProviderID,
		arg.ModelID,
		arg.PolicyEpoch,
		arg.PolicyVersion,
		arg.SnapshotID,
		arg.SnapshotSha256,
		arg.Environment,
		arg.Domain,
		arg.DecisionPoint,
		arg.PointOrdinal,
		arg.PredicateSha256,
		arg.ExperimentID,
		arg.Cutoff,
		arg.CohortSha256,
		arg.Artifact,
		arg.ArtifactJson,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAdaptiveFocalCohortClaim = `-- name: InsertAdaptiveFocalCohortClaim :one
INSERT INTO aura.adaptive_focal_cohort_claims (
    owner_id, cohort_id, request_id, evaluation_conversation_id,
    assignment_id, domain, decision_point, point_ordinal, session_id,
    episode_id, time_block_start
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9, $10, $11
)
ON CONFLICT DO NOTHING
RETURNING id, owner_id, cohort_id, request_id, evaluation_conversation_id,
          assignment_id, domain, decision_point, point_ordinal, session_id,
          episode_id, time_block_start, claimed_at
`

type InsertAdaptiveFocalCohortClaimParams struct {
	OwnerID                  pgtype.UUID        `json:"owner_id"`
	CohortID                 pgtype.UUID        `json:"cohort_id"`
	RequestID                pgtype.UUID        `json:"request_id"`
	EvaluationConversationID pgtype.UUID        `json:"evaluation_conversation_id"`
	AssignmentID             pgtype.UUID        `json:"assignment_id"`
	Domain                   string             `json:"domain"`
	DecisionPoint            string             `json:"decision_point"`
	PointOrdinal             int64              `json:"point_ordinal"`
	SessionID                pgtype.UUID        `json:"session_id"`
	EpisodeID                pgtype.UUID        `json:"episode_id"`
	TimeBlockStart           pgtype.Timestamptz `json:"time_block_start"`
}

func (q *Queries) InsertAdaptiveFocalCohortClaim(ctx context.Context, arg InsertAdaptiveFocalCohortClaimParams) (AuraAdaptiveFocalCohortClaims, error) {
	row := q.db.QueryRow(ctx, insertAdaptiveFocalCohortClaim,
		arg.OwnerID,
		arg.CohortID,
		arg.RequestID,
		arg.EvaluationConversationID,
		arg.AssignmentID,
		arg.Domain,
		arg.DecisionPoint,
		arg.PointOrdinal,
		arg.SessionID,
		arg.EpisodeID,
		arg.TimeBlockStart,
	)
	var i AuraAdaptiveFocalCohortClaims
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CohortID,
		&i.RequestID,
		&i.EvaluationConversationID,
		&i.AssignmentID,
		&i.Domain,
		&i.DecisionPoint,
		&i.PointOrdinal,
		&i.SessionID,
		&i.EpisodeID,
		&i.TimeBlockStart,
		&i.ClaimedAt,
	)
	return i, err
}

const listAdaptiveFocalCohortClaimConflicts = `-- name: ListAdaptiveFocalCohortClaimConflicts :many
SELECT id, owner_id, cohort_id, request_id, evaluation_conversation_id,
       assignment_id, domain, decision_point, point_ordinal, session_id,
       episode_id, time_block_start, claimed_at
FROM aura.adaptive_focal_cohort_claims
WHERE owner_id = $1
  AND (
      evaluation_conversation_id = $2
      OR (
          cohort_id = $3
          AND (
              request_id = $4
              OR assignment_id = $5
          )
      )
  )
ORDER BY id
`

type ListAdaptiveFocalCohortClaimConflictsParams struct {
	OwnerID                  pgtype.UUID `json:"owner_id"`
	EvaluationConversationID pgtype.UUID `json:"evaluation_conversation_id"`
	CohortID                 pgtype.UUID `json:"cohort_id"`
	RequestID                pgtype.UUID `json:"request_id"`
	AssignmentID             pgtype.UUID `json:"assignment_id"`
}

func (q *Queries) ListAdaptiveFocalCohortClaimConflicts(ctx context.Context, arg ListAdaptiveFocalCohortClaimConflictsParams) ([]AuraAdaptiveFocalCohortClaims, error) {
	rows, err := q.db.Query(ctx, listAdaptiveFocalCohortClaimConflicts,
		arg.OwnerID,
		arg.EvaluationConversationID,
		arg.CohortID,
		arg.RequestID,
		arg.AssignmentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraAdaptiveFocalCohortClaims{}
	for rows.Next() {
		var i AuraAdaptiveFocalCohortClaims
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.CohortID,
			&i.RequestID,
			&i.EvaluationConversationID,
			&i.AssignmentID,
			&i.Domain,
			&i.DecisionPoint,
			&i.PointOrdinal,
			&i.SessionID,
			&i.EpisodeID,
			&i.TimeBlockStart,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdaptiveFocalCohortClaimsForReconstruction = `-- name: ListAdaptiveFocalCohortClaimsForReconstruction :many
SELECT id, owner_id, cohort_id, request_id, evaluation_conversation_id,
       assignment_id, domain, decision_point, point_ordinal, session_id,
       episode_id, time_block_start, claimed_at
FROM aura.adaptive_focal_cohort_claims
WHERE owner_id = $1
  AND cohort_id = $2
ORDER BY request_id, assignment_id, id
`

type ListAdaptiveFocalCohortClaimsForReconstructionParams struct {
	OwnerID  pgtype.UUID `json:"owner_id"`
	CohortID pgtype.UUID `json:"cohort_id"`
}

func (q *Queries) ListAdaptiveFocalCohortClaimsForReconstruction(ctx context.Context, arg ListAdaptiveFocalCohortClaimsForReconstructionParams) ([]AuraAdaptiveFocalCohortClaims, error) {
	rows, err := q.db.Query(ctx, listAdaptiveFocalCohortClaimsForReconstruction, arg.OwnerID, arg.CohortID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraAdaptiveFocalCohortClaims{}
	for rows.Next() {
		var i AuraAdaptiveFocalCohortClaims
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.CohortID,
			&i.RequestID,
			&i.EvaluationConversationID,
			&i.AssignmentID,
			&i.Domain,
			&i.DecisionPoint,
			&i.PointOrdinal,
			&i.SessionID,
			&i.EpisodeID,
			&i.TimeBlockStart,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdaptiveFocalCohortFactsForReconstruction = `-- name: ListAdaptiveFocalCohortFactsForReconstruction :many
WITH cohort_assignments AS (
    SELECT decision_id
    FROM aura.adaptive_outbox
    WHERE owner_id = $1
      AND event_kind = 'decision'
      AND payload->>'cohort_id' = $2::text
)
SELECT fact.id, fact.owner_id, fact.aggregate_id, fact.sequence,
       fact.decision_id, fact.event_kind, fact.payload, fact.payload_hash,
       fact.status, fact.attempts, fact.available_at, fact.lease_owner,
       fact.lease_expires_at, fact.created_at, fact.projected_at,
       fact.dead_letter_at, fact.last_error_class, fact.recorded_at
FROM aura.adaptive_outbox AS fact
WHERE fact.owner_id = $1
  AND (
      (fact.event_kind = 'decision' AND fact.payload->>'cohort_id' = $2::text)
      OR (
          fact.event_kind IN ('delivery', 'outcome', 'correction')
          AND fact.decision_id IN (SELECT decision_id FROM cohort_assignments)
      )
  )
ORDER BY fact.decision_id, fact.event_kind, fact.id
`

type ListAdaptiveFocalCohortFactsForReconstructionParams struct {
	OwnerID  pgtype.UUID `json:"owner_id"`
	CohortID string      `json:"cohort_id"`
}

func (q *Queries) ListAdaptiveFocalCohortFactsForReconstruction(ctx context.Context, arg ListAdaptiveFocalCohortFactsForReconstructionParams) ([]AuraAdaptiveOutbox, error) {
	rows, err := q.db.Query(ctx, listAdaptiveFocalCohortFactsForReconstruction, arg.OwnerID, arg.CohortID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraAdaptiveOutbox{}
	for rows.Next() {
		var i AuraAdaptiveOutbox
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AggregateID,
			&i.Sequence,
			&i.DecisionID,
			&i.EventKind,
			&i.Payload,
			&i.PayloadHash,
			&i.Status,
			&i.Attempts,
			&i.AvailableAt,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.ProjectedAt,
			&i.DeadLetterAt,
			&i.LastErrorClass,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAdaptiveOwnerForCohortReconstruction = `-- name: LockAdaptiveOwnerForCohortReconstruction :one
SELECT id
FROM aura.identities
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockAdaptiveOwnerForCohortReconstruction(ctx context.Context, ownerID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockAdaptiveOwnerForCohortReconstruction, ownerID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lockSchema2AdaptiveAssignmentEvents = `-- name: LockSchema2AdaptiveAssignmentEvents :many
SELECT id, owner_id, aggregate_id, sequence, decision_id, event_kind,
       payload, payload_hash, status, attempts, available_at,
       lease_owner, lease_expires_at, created_at, projected_at,
       dead_letter_at, last_error_class, recorded_at
FROM aura.adaptive_outbox
WHERE owner_id = $1
  AND decision_id = $2
  AND event_kind = 'decision'
  AND payload->>'schema_version' = '2.0'
FOR UPDATE
`

type LockSchema2AdaptiveAssignmentEventsParams struct {
	OwnerID      pgtype.UUID `json:"owner_id"`
	AssignmentID pgtype.UUID `json:"assignment_id"`
}

func (q *Queries) LockSchema2AdaptiveAssignmentEvents(ctx context.Context, arg LockSchema2AdaptiveAssignmentEventsParams) ([]AuraAdaptiveOutbox, error) {
	rows, err := q.db.Query(ctx, lockSchema2AdaptiveAssignmentEvents, arg.OwnerID, arg.AssignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraAdaptiveOutbox{}
	for rows.Next() {
		var i AuraAdaptiveOutbox
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AggregateID,
			&i.Sequence,
			&i.DecisionID,
			&i.EventKind,
			&i.Payload,
			&i.PayloadHash,
			&i.Status,
			&i.Attempts,
			&i.AvailableAt,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.ProjectedAt,
			&i.DeadLetterAt,
			&i.LastErrorClass,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
