// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_job_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeRun = `-- name: CompleteRun :exec
UPDATE aura.agent_job_runs
SET status = $2, summary = $3, last_error = $4, completed_with_hash = $5, completed_at = now()
WHERE id = $1
`

type CompleteRunParams struct {
	ID                pgtype.UUID `json:"id"`
	Status            string      `json:"status"`
	Summary           pgtype.Text `json:"summary"`
	LastError         pgtype.Text `json:"last_error"`
	CompletedWithHash pgtype.Text `json:"completed_with_hash"`
}

func (q *Queries) CompleteRun(ctx context.Context, arg CompleteRunParams) error {
	_, err := q.db.Exec(ctx, completeRun,
		arg.ID,
		arg.Status,
		arg.Summary,
		arg.LastError,
		arg.CompletedWithHash,
	)
	return err
}

const getRun = `-- name: GetRun :one
SELECT id, task_id, status, step_budget, started_at, last_heartbeat_at,
    completed_with_hash, summary, last_error, missed_since, paused_state_token, completed_at
FROM aura.agent_job_runs
WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (AuraAgentJobRuns, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i AuraAgentJobRuns
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Status,
		&i.StepBudget,
		&i.StartedAt,
		&i.LastHeartbeatAt,
		&i.CompletedWithHash,
		&i.Summary,
		&i.LastError,
		&i.MissedSince,
		&i.PausedStateToken,
		&i.CompletedAt,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :one
INSERT INTO aura.agent_job_runs (id, task_id, status, step_budget)
VALUES ($1, $2, 'running', $3)
RETURNING id, task_id, status, step_budget, started_at, last_heartbeat_at,
    completed_with_hash, summary, last_error, missed_since, paused_state_token, completed_at
`

type InsertRunParams struct {
	ID         pgtype.UUID `json:"id"`
	TaskID     pgtype.UUID `json:"task_id"`
	StepBudget pgtype.Int4 `json:"step_budget"`
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (AuraAgentJobRuns, error) {
	row := q.db.QueryRow(ctx, insertRun, arg.ID, arg.TaskID, arg.StepBudget)
	var i AuraAgentJobRuns
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Status,
		&i.StepBudget,
		&i.StartedAt,
		&i.LastHeartbeatAt,
		&i.CompletedWithHash,
		&i.Summary,
		&i.LastError,
		&i.MissedSince,
		&i.PausedStateToken,
		&i.CompletedAt,
	)
	return i, err
}

const listRunsForTask = `-- name: ListRunsForTask :many
SELECT id, task_id, status, step_budget, started_at, last_heartbeat_at,
    completed_with_hash, summary, last_error, missed_since, paused_state_token, completed_at
FROM aura.agent_job_runs
WHERE task_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListRunsForTaskParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListRunsForTask(ctx context.Context, arg ListRunsForTaskParams) ([]AuraAgentJobRuns, error) {
	rows, err := q.db.Query(ctx, listRunsForTask, arg.TaskID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraAgentJobRuns{}
	for rows.Next() {
		var i AuraAgentJobRuns
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Status,
			&i.StepBudget,
			&i.StartedAt,
			&i.LastHeartbeatAt,
			&i.CompletedWithHash,
			&i.Summary,
			&i.LastError,
			&i.MissedSince,
			&i.PausedStateToken,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUnknownRecovery = `-- name: MarkUnknownRecovery :exec
UPDATE aura.agent_job_runs
SET status = 'unknown_recovery', missed_since = now()
WHERE id = $1
`

func (q *Queries) MarkUnknownRecovery(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markUnknownRecovery, id)
	return err
}

const scanStaleRuns = `-- name: ScanStaleRuns :many
SELECT id, task_id
FROM aura.agent_job_runs
WHERE status = 'running'
  AND last_heartbeat_at < now() - make_interval(secs => $1)
`

type ScanStaleRunsRow struct {
	ID     pgtype.UUID `json:"id"`
	TaskID pgtype.UUID `json:"task_id"`
}

func (q *Queries) ScanStaleRuns(ctx context.Context, secs float64) ([]ScanStaleRunsRow, error) {
	rows, err := q.db.Query(ctx, scanStaleRuns, secs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanStaleRunsRow{}
	for rows.Next() {
		var i ScanStaleRunsRow
		if err := rows.Scan(&i.ID, &i.TaskID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHeartbeat = `-- name: UpdateHeartbeat :exec
UPDATE aura.agent_job_runs
SET last_heartbeat_at = now()
WHERE id = $1
`

func (q *Queries) UpdateHeartbeat(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateHeartbeat, id)
	return err
}
