// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO aura.assets (
    identity_id, source_kind, source_ref, thread_id, scope, modality,
    status, file_name, mime_type, declared_size_bytes, object_bucket,
    object_key, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13
)
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, searchable_at, completed_at, deleted_at, updated_at
`

type CreateAssetParams struct {
	IdentityID        pgtype.UUID `json:"identity_id"`
	SourceKind        string      `json:"source_kind"`
	SourceRef         string      `json:"source_ref"`
	ThreadID          string      `json:"thread_id"`
	Scope             string      `json:"scope"`
	Modality          string      `json:"modality"`
	Status            string      `json:"status"`
	FileName          string      `json:"file_name"`
	MimeType          string      `json:"mime_type"`
	DeclaredSizeBytes int64       `json:"declared_size_bytes"`
	ObjectBucket      string      `json:"object_bucket"`
	ObjectKey         string      `json:"object_key"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.IdentityID,
		arg.SourceKind,
		arg.SourceRef,
		arg.ThreadID,
		arg.Scope,
		arg.Modality,
		arg.Status,
		arg.FileName,
		arg.MimeType,
		arg.DeclaredSizeBytes,
		arg.ObjectBucket,
		arg.ObjectKey,
		arg.Metadata,
	)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.SearchableAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, searchable_at, completed_at, deleted_at, updated_at FROM aura.assets
WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id pgtype.UUID) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.SearchableAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetForIdentity = `-- name: GetAssetForIdentity :one
SELECT id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, searchable_at, completed_at, deleted_at, updated_at FROM aura.assets
WHERE id = $1
  AND identity_id = $2
  AND deleted_at IS NULL
`

type GetAssetForIdentityParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
}

func (q *Queries) GetAssetForIdentity(ctx context.Context, arg GetAssetForIdentityParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, getAssetForIdentity, arg.ID, arg.IdentityID)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.SearchableAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAssetEvent = `-- name: InsertAssetEvent :exec
INSERT INTO aura.asset_events (
    asset_id, seq, from_status, to_status, reason, detail
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type InsertAssetEventParams struct {
	AssetID    pgtype.UUID `json:"asset_id"`
	Seq        int32       `json:"seq"`
	FromStatus string      `json:"from_status"`
	ToStatus   string      `json:"to_status"`
	Reason     string      `json:"reason"`
	Detail     []byte      `json:"detail"`
}

func (q *Queries) InsertAssetEvent(ctx context.Context, arg InsertAssetEventParams) error {
	_, err := q.db.Exec(ctx, insertAssetEvent,
		arg.AssetID,
		arg.Seq,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
		arg.Detail,
	)
	return err
}

const listAssetsForLibrary = `-- name: ListAssetsForLibrary :many
SELECT id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, searchable_at, completed_at, deleted_at, updated_at FROM aura.assets
WHERE identity_id = $1
  AND scope = 'library'
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListAssetsForLibraryParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) ListAssetsForLibrary(ctx context.Context, arg ListAssetsForLibraryParams) ([]AuraAssets, error) {
	rows, err := q.db.Query(ctx, listAssetsForLibrary, arg.IdentityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraAssets{}
	for rows.Next() {
		var i AuraAssets
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.SourceKind,
			&i.SourceRef,
			&i.ThreadID,
			&i.Scope,
			&i.Modality,
			&i.Status,
			&i.FileName,
			&i.MimeType,
			&i.DeclaredSizeBytes,
			&i.SizeBytes,
			&i.ContentHash,
			&i.ObjectBucket,
			&i.ObjectKey,
			&i.ObjectEtag,
			&i.DocumentID,
			&i.Summary,
			&i.Metadata,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UploadedAt,
			&i.AcceptedAt,
			&i.ProcessedAt,
			&i.SearchableAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsForThread = `-- name: ListAssetsForThread :many
SELECT id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, searchable_at, completed_at, deleted_at, updated_at FROM aura.assets
WHERE identity_id = $1
  AND thread_id = $2
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListAssetsForThreadParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	ThreadID   string      `json:"thread_id"`
}

func (q *Queries) ListAssetsForThread(ctx context.Context, arg ListAssetsForThreadParams) ([]AuraAssets, error) {
	rows, err := q.db.Query(ctx, listAssetsForThread, arg.IdentityID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraAssets{}
	for rows.Next() {
		var i AuraAssets
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.SourceKind,
			&i.SourceRef,
			&i.ThreadID,
			&i.Scope,
			&i.Modality,
			&i.Status,
			&i.FileName,
			&i.MimeType,
			&i.DeclaredSizeBytes,
			&i.SizeBytes,
			&i.ContentHash,
			&i.ObjectBucket,
			&i.ObjectKey,
			&i.ObjectEtag,
			&i.DocumentID,
			&i.Summary,
			&i.Metadata,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UploadedAt,
			&i.AcceptedAt,
			&i.ProcessedAt,
			&i.SearchableAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAssetEventSeq = `-- name: NextAssetEventSeq :one
SELECT COALESCE(MAX(seq), 0) + 1::integer
FROM aura.asset_events
WHERE asset_id = $1
`

func (q *Queries) NextAssetEventSeq(ctx context.Context, assetID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextAssetEventSeq, assetID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const promoteAssetToLibrary = `-- name: PromoteAssetToLibrary :one
UPDATE aura.assets
SET scope = 'library',
    updated_at = now()
WHERE id = $1
  AND identity_id = $2
  AND deleted_at IS NULL
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, searchable_at, completed_at, deleted_at, updated_at
`

type PromoteAssetToLibraryParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
}

func (q *Queries) PromoteAssetToLibrary(ctx context.Context, arg PromoteAssetToLibraryParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, promoteAssetToLibrary, arg.ID, arg.IdentityID)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.SearchableAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteAsset = `-- name: SoftDeleteAsset :one
UPDATE aura.assets
SET status = 'deleted',
    deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND identity_id = $2
  AND deleted_at IS NULL
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, searchable_at, completed_at, deleted_at, updated_at
`

type SoftDeleteAssetParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
}

func (q *Queries) SoftDeleteAsset(ctx context.Context, arg SoftDeleteAssetParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, softDeleteAsset, arg.ID, arg.IdentityID)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.SearchableAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssetAccepted = `-- name: UpdateAssetAccepted :one
UPDATE aura.assets
SET status = 'accepted',
    size_bytes = $2,
    content_hash = $3,
    mime_type = $4,
    accepted_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, searchable_at, completed_at, deleted_at, updated_at
`

type UpdateAssetAcceptedParams struct {
	ID          pgtype.UUID `json:"id"`
	SizeBytes   int64       `json:"size_bytes"`
	ContentHash string      `json:"content_hash"`
	MimeType    string      `json:"mime_type"`
}

func (q *Queries) UpdateAssetAccepted(ctx context.Context, arg UpdateAssetAcceptedParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, updateAssetAccepted,
		arg.ID,
		arg.SizeBytes,
		arg.ContentHash,
		arg.MimeType,
	)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.SearchableAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssetResult = `-- name: UpdateAssetResult :one
UPDATE aura.assets
SET status = $2,
    document_id = $3,
    summary = $4,
    metadata = $5,
    error_code = '',
    error_message = '',
    processed_at = now(),
    searchable_at = CASE WHEN $2 = 'searchable' THEN now() ELSE searchable_at END,
    completed_at = CASE WHEN $2 = 'complete' THEN now() ELSE completed_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, searchable_at, completed_at, deleted_at, updated_at
`

type UpdateAssetResultParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	DocumentID string      `json:"document_id"`
	Summary    string      `json:"summary"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) UpdateAssetResult(ctx context.Context, arg UpdateAssetResultParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, updateAssetResult,
		arg.ID,
		arg.Status,
		arg.DocumentID,
		arg.Summary,
		arg.Metadata,
	)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.SearchableAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssetStatus = `-- name: UpdateAssetStatus :one
UPDATE aura.assets
SET status = $2,
    error_code = $3,
    error_message = $4,
    updated_at = now(),
    processed_at = CASE WHEN $2 IN ('searchable', 'complete', 'failed', 'refused') THEN now() ELSE processed_at END,
    searchable_at = CASE WHEN $2 = 'searchable' THEN now() ELSE searchable_at END,
    completed_at = CASE WHEN $2 = 'complete' THEN now() ELSE completed_at END,
    deleted_at = CASE WHEN $2 = 'deleted' THEN now() ELSE deleted_at END
WHERE id = $1
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, searchable_at, completed_at, deleted_at, updated_at
`

type UpdateAssetStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	ErrorCode    string      `json:"error_code"`
	ErrorMessage string      `json:"error_message"`
}

func (q *Queries) UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, updateAssetStatus,
		arg.ID,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.SearchableAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssetUploaded = `-- name: UpdateAssetUploaded :one
UPDATE aura.assets
SET status = 'uploaded',
    size_bytes = $2,
    object_etag = $3,
    uploaded_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, searchable_at, completed_at, deleted_at, updated_at
`

type UpdateAssetUploadedParams struct {
	ID         pgtype.UUID `json:"id"`
	SizeBytes  int64       `json:"size_bytes"`
	ObjectEtag string      `json:"object_etag"`
}

func (q *Queries) UpdateAssetUploaded(ctx context.Context, arg UpdateAssetUploadedParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, updateAssetUploaded, arg.ID, arg.SizeBytes, arg.ObjectEtag)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.SearchableAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
