// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adoptAssetIntoThread = `-- name: AdoptAssetIntoThread :one
UPDATE aura.assets
SET thread_id = $3,
    updated_at = now()
WHERE id = $1
  AND identity_id = $2
  AND thread_id = ''
  AND deleted_at IS NULL
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id
`

type AdoptAssetIntoThreadParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
	ThreadID   string      `json:"thread_id"`
}

// Claim an asset that was presigned before its conversation existed.
//
// The web composer presigns as soon as the file is chosen, and on a BRAND NEW chat there
// is no thread id yet, so the row is written with thread_id = ”. Nothing ever filled it
// in, and ListAssetsForThread filters on thread_id -- so the first attachment of a new
// conversation was invisible the moment the page reloaded (measured 2026-09-03: one such
// row, an image the model had already answered about).
//
// Only an UNCLAIMED asset is adopted. A row that already names a thread is left exactly as
// it is, so this can never move someone's attachment between conversations.
func (q *Queries) AdoptAssetIntoThread(ctx context.Context, arg AdoptAssetIntoThreadParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, adoptAssetIntoThread, arg.ID, arg.IdentityID, arg.ThreadID)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.PipelineGeneration,
		&i.ToolCallID,
	)
	return i, err
}

const assetKeysHeld = `-- name: AssetKeysHeld :many
SELECT object_key FROM aura.assets
WHERE identity_id = $1
  AND object_key = ANY($2::text[])
`

type AssetKeysHeldParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	ObjectKeys []string    `json:"object_keys"`
}

// The keys among object_keys some row of the identity holds, in any status. A file-manager
// write landing on one would replace an asset's bytes under its row, hand them to the sweep
// removing a deleting row's object, or collide with the per-identity key index.
func (q *Queries) AssetKeysHeld(ctx context.Context, arg AssetKeysHeldParams) ([]string, error) {
	rows, err := q.db.Query(ctx, assetKeysHeld, arg.IdentityID, arg.ObjectKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assetNamesByObjectKey = `-- name: AssetNamesByObjectKey :many
SELECT id, object_key, file_name FROM aura.assets
WHERE identity_id = $1
  AND object_key = ANY($2::text[])
  AND file_name <> ''
  AND deleted_at IS NULL
`

type AssetNamesByObjectKeyParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	ObjectKeys []string    `json:"object_keys"`
}

type AssetNamesByObjectKeyRow struct {
	ID        pgtype.UUID `json:"id"`
	ObjectKey string      `json:"object_key"`
	FileName  string      `json:"file_name"`
}

// The file manager lists bucket KEYS, which deliberately carry no name (a chat attachment
// is chat/<assetID>.<ext> so the name cannot leak through a presigned URL or an access log).
// The name it needs is on the same row as the key, so the listing resolves it here rather
// than deriving a search id and asking the document index — which failed whole-listing once
// a page held more keys than that index accepts filters.
// A key with no row simply has no entry, and the caller keeps the key tail it already shows.
// The id rides along so a file opened from the manager can be edited AS its asset: without
// it the editor took every file for a foreign object and uploaded a copy on each open.
func (q *Queries) AssetNamesByObjectKey(ctx context.Context, arg AssetNamesByObjectKeyParams) ([]AssetNamesByObjectKeyRow, error) {
	rows, err := q.db.Query(ctx, assetNamesByObjectKey, arg.IdentityID, arg.ObjectKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetNamesByObjectKeyRow{}
	for rows.Next() {
		var i AssetNamesByObjectKeyRow
		if err := rows.Scan(&i.ID, &i.ObjectKey, &i.FileName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO aura.assets (
    identity_id, source_kind, source_ref, thread_id, scope, modality,
    status, file_name, mime_type, declared_size_bytes, object_bucket,
    object_key, metadata, tool_call_id
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14
)
ON CONFLICT (identity_id, source_kind, source_ref)
    WHERE source_kind = 'agent' AND source_ref <> ''
DO UPDATE SET updated_at = aura.assets.updated_at
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id
`

type CreateAssetParams struct {
	IdentityID        pgtype.UUID `json:"identity_id"`
	SourceKind        string      `json:"source_kind"`
	SourceRef         string      `json:"source_ref"`
	ThreadID          string      `json:"thread_id"`
	Scope             string      `json:"scope"`
	Modality          string      `json:"modality"`
	Status            string      `json:"status"`
	FileName          string      `json:"file_name"`
	MimeType          string      `json:"mime_type"`
	DeclaredSizeBytes int64       `json:"declared_size_bytes"`
	ObjectBucket      string      `json:"object_bucket"`
	ObjectKey         string      `json:"object_key"`
	Metadata          []byte      `json:"metadata"`
	ToolCallID        string      `json:"tool_call_id"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.IdentityID,
		arg.SourceKind,
		arg.SourceRef,
		arg.ThreadID,
		arg.Scope,
		arg.Modality,
		arg.Status,
		arg.FileName,
		arg.MimeType,
		arg.DeclaredSizeBytes,
		arg.ObjectBucket,
		arg.ObjectKey,
		arg.Metadata,
		arg.ToolCallID,
	)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.PipelineGeneration,
		&i.ToolCallID,
	)
	return i, err
}

const finalizeAsset = `-- name: FinalizeAsset :execrows
DELETE FROM aura.assets
WHERE assets.id = $1
  AND assets.identity_id = $2
  AND assets.status = 'deleting'
  AND NOT EXISTS (SELECT 1 FROM aura.media_job WHERE media_job.asset_id = assets.id)
`

type FinalizeAssetParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
}

// Removes a deleting row whose object is gone. A row a media_job points at is left for
// MarkAssetDeleted instead: that key has no ON DELETE action (migration 0128) because a paid
// clip keeps its pointer.
func (q *Queries) FinalizeAsset(ctx context.Context, arg FinalizeAssetParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeAsset, arg.ID, arg.IdentityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAsset = `-- name: GetAsset :one
SELECT id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id FROM aura.assets
WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id pgtype.UUID) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.PipelineGeneration,
		&i.ToolCallID,
	)
	return i, err
}

const getAssetByObjectKey = `-- name: GetAssetByObjectKey :one
SELECT id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id FROM aura.assets
WHERE identity_id = $1
  AND object_key = $2
  AND deleted_at IS NULL
`

type GetAssetByObjectKeyParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	ObjectKey  string      `json:"object_key"`
}

func (q *Queries) GetAssetByObjectKey(ctx context.Context, arg GetAssetByObjectKeyParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, getAssetByObjectKey, arg.IdentityID, arg.ObjectKey)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.PipelineGeneration,
		&i.ToolCallID,
	)
	return i, err
}

const getAssetForIdentity = `-- name: GetAssetForIdentity :one
SELECT id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id FROM aura.assets
WHERE id = $1
  AND identity_id = $2
  AND deleted_at IS NULL
`

type GetAssetForIdentityParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
}

func (q *Queries) GetAssetForIdentity(ctx context.Context, arg GetAssetForIdentityParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, getAssetForIdentity, arg.ID, arg.IdentityID)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.PipelineGeneration,
		&i.ToolCallID,
	)
	return i, err
}

const insertAssetEvent = `-- name: InsertAssetEvent :exec
INSERT INTO aura.asset_events (
    asset_id, seq, from_status, to_status, reason, detail
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type InsertAssetEventParams struct {
	AssetID    pgtype.UUID `json:"asset_id"`
	Seq        int32       `json:"seq"`
	FromStatus string      `json:"from_status"`
	ToStatus   string      `json:"to_status"`
	Reason     string      `json:"reason"`
	Detail     []byte      `json:"detail"`
}

func (q *Queries) InsertAssetEvent(ctx context.Context, arg InsertAssetEventParams) error {
	_, err := q.db.Exec(ctx, insertAssetEvent,
		arg.AssetID,
		arg.Seq,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
		arg.Detail,
	)
	return err
}

const listAssetsForLibrary = `-- name: ListAssetsForLibrary :many
SELECT id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id FROM aura.assets
WHERE identity_id = $1
  AND scope = 'library'
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListAssetsForLibraryParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) ListAssetsForLibrary(ctx context.Context, arg ListAssetsForLibraryParams) ([]AuraAssets, error) {
	rows, err := q.db.Query(ctx, listAssetsForLibrary, arg.IdentityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraAssets{}
	for rows.Next() {
		var i AuraAssets
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.SourceKind,
			&i.SourceRef,
			&i.ThreadID,
			&i.Scope,
			&i.Modality,
			&i.Status,
			&i.FileName,
			&i.MimeType,
			&i.DeclaredSizeBytes,
			&i.SizeBytes,
			&i.ContentHash,
			&i.ObjectBucket,
			&i.ObjectKey,
			&i.ObjectEtag,
			&i.DocumentID,
			&i.Summary,
			&i.Metadata,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UploadedAt,
			&i.AcceptedAt,
			&i.ProcessedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.PipelineGeneration,
			&i.ToolCallID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsForThread = `-- name: ListAssetsForThread :many
SELECT id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id FROM aura.assets
WHERE identity_id = $1
  AND thread_id = $2
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListAssetsForThreadParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	ThreadID   string      `json:"thread_id"`
}

func (q *Queries) ListAssetsForThread(ctx context.Context, arg ListAssetsForThreadParams) ([]AuraAssets, error) {
	rows, err := q.db.Query(ctx, listAssetsForThread, arg.IdentityID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraAssets{}
	for rows.Next() {
		var i AuraAssets
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.SourceKind,
			&i.SourceRef,
			&i.ThreadID,
			&i.Scope,
			&i.Modality,
			&i.Status,
			&i.FileName,
			&i.MimeType,
			&i.DeclaredSizeBytes,
			&i.SizeBytes,
			&i.ContentHash,
			&i.ObjectBucket,
			&i.ObjectKey,
			&i.ObjectEtag,
			&i.DocumentID,
			&i.Summary,
			&i.Metadata,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UploadedAt,
			&i.AcceptedAt,
			&i.ProcessedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.PipelineGeneration,
			&i.ToolCallID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletingAssets = `-- name: ListDeletingAssets :many
SELECT id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id FROM aura.assets
WHERE identity_id = $1
  AND status = 'deleting'
ORDER BY created_at ASC, id ASC
LIMIT $2
`

type ListDeletingAssetsParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Limit      int32       `json:"limit"`
}

// What a delete left unfinished, oldest first, whether or not deleted_at was stamped: rows
// soft-deleted before SoftDeleteAsset stamped it are the backlog this drains.
func (q *Queries) ListDeletingAssets(ctx context.Context, arg ListDeletingAssetsParams) ([]AuraAssets, error) {
	rows, err := q.db.Query(ctx, listDeletingAssets, arg.IdentityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraAssets{}
	for rows.Next() {
		var i AuraAssets
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.SourceKind,
			&i.SourceRef,
			&i.ThreadID,
			&i.Scope,
			&i.Modality,
			&i.Status,
			&i.FileName,
			&i.MimeType,
			&i.DeclaredSizeBytes,
			&i.SizeBytes,
			&i.ContentHash,
			&i.ObjectBucket,
			&i.ObjectKey,
			&i.ObjectEtag,
			&i.DocumentID,
			&i.Summary,
			&i.Metadata,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UploadedAt,
			&i.AcceptedAt,
			&i.ProcessedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.PipelineGeneration,
			&i.ToolCallID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAssets = `-- name: ListRecentAssets :many
SELECT id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id FROM aura.assets
WHERE assets.identity_id = $1
  AND assets.modality = ANY($2::text[])
  AND assets.status IN ('accepted', 'processing', 'complete')
  AND assets.deleted_at IS NULL
  AND ($3::uuid IS NULL OR (assets.created_at, assets.id) < (
      SELECT b.created_at, b.id FROM aura.assets b
      WHERE b.id = $3::uuid AND b.identity_id = $1))
ORDER BY assets.created_at DESC, assets.id DESC
LIMIT $4
`

type ListRecentAssetsParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Modalities []string    `json:"modalities"`
	BeforeID   pgtype.UUID `json:"before_id"`
	RowLimit   int32       `json:"row_limit"`
}

// The assets of the asked kinds an identity can pick in a Studio — a frame or a reference in the
// image Studio, a sound or a clip in the video Studio: usable (the statuses the cockpit's
// isReadyAsset accepts) and not deleted, newest first, from any thread or none.
// One page: before_id is the last row of the previous page; an id the owner does not hold
// compares as NULL and yields an empty page.
func (q *Queries) ListRecentAssets(ctx context.Context, arg ListRecentAssetsParams) ([]AuraAssets, error) {
	rows, err := q.db.Query(ctx, listRecentAssets,
		arg.IdentityID,
		arg.Modalities,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraAssets{}
	for rows.Next() {
		var i AuraAssets
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.SourceKind,
			&i.SourceRef,
			&i.ThreadID,
			&i.Scope,
			&i.Modality,
			&i.Status,
			&i.FileName,
			&i.MimeType,
			&i.DeclaredSizeBytes,
			&i.SizeBytes,
			&i.ContentHash,
			&i.ObjectBucket,
			&i.ObjectKey,
			&i.ObjectEtag,
			&i.DocumentID,
			&i.Summary,
			&i.Metadata,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UploadedAt,
			&i.AcceptedAt,
			&i.ProcessedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.PipelineGeneration,
			&i.ToolCallID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAssetDeleted = `-- name: MarkAssetDeleted :one
UPDATE aura.assets
SET status = 'deleted', deleted_at = COALESCE(deleted_at, now()), updated_at = now()
WHERE id = $1
  AND identity_id = $2
  AND status = 'deleting'
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id
`

type MarkAssetDeletedParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
}

func (q *Queries) MarkAssetDeleted(ctx context.Context, arg MarkAssetDeletedParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, markAssetDeleted, arg.ID, arg.IdentityID)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.PipelineGeneration,
		&i.ToolCallID,
	)
	return i, err
}

const nextAssetEventSeq = `-- name: NextAssetEventSeq :one
SELECT COALESCE(MAX(seq), 0) + 1::integer
FROM aura.asset_events
WHERE asset_id = $1
`

func (q *Queries) NextAssetEventSeq(ctx context.Context, assetID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextAssetEventSeq, assetID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const promoteAssetToLibrary = `-- name: PromoteAssetToLibrary :one
UPDATE aura.assets
SET scope = 'library',
    updated_at = now()
WHERE id = $1
  AND identity_id = $2
  AND deleted_at IS NULL
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id
`

type PromoteAssetToLibraryParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
}

func (q *Queries) PromoteAssetToLibrary(ctx context.Context, arg PromoteAssetToLibraryParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, promoteAssetToLibrary, arg.ID, arg.IdentityID)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.PipelineGeneration,
		&i.ToolCallID,
	)
	return i, err
}

const relocateAsset = `-- name: RelocateAsset :exec
UPDATE aura.assets
SET object_key = $1,
    file_name = CASE WHEN $2::text <> '' THEN $2::text ELSE file_name END,
    updated_at = now()
WHERE identity_id = $3
  AND object_bucket = $4
  AND object_key = $5
`

type RelocateAssetParams struct {
	ToKey        string      `json:"to_key"`
	NewName      string      `json:"new_name"`
	IdentityID   pgtype.UUID `json:"identity_id"`
	ObjectBucket string      `json:"object_bucket"`
	FromKey      string      `json:"from_key"`
}

// Moves the identity's row in one bucket from from_key to to_key, taking new_name when the
// move carries one. The file manager copies the object first and deletes the source after,
// so the row never names a key without bytes.
func (q *Queries) RelocateAsset(ctx context.Context, arg RelocateAssetParams) error {
	_, err := q.db.Exec(ctx, relocateAsset,
		arg.ToKey,
		arg.NewName,
		arg.IdentityID,
		arg.ObjectBucket,
		arg.FromKey,
	)
	return err
}

const resetAssetForIngestionRetry = `-- name: ResetAssetForIngestionRetry :one
UPDATE aura.assets
SET status = 'accepted', error_code = '', error_message = '',
    processed_at = NULL, completed_at = NULL, updated_at = now()
WHERE id = $1
  AND identity_id = $2
  AND status IN ('failed', 'refused', 'canceled')
  AND deleted_at IS NULL
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id
`

type ResetAssetForIngestionRetryParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
}

func (q *Queries) ResetAssetForIngestionRetry(ctx context.Context, arg ResetAssetForIngestionRetryParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, resetAssetForIngestionRetry, arg.ID, arg.IdentityID)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.PipelineGeneration,
		&i.ToolCallID,
	)
	return i, err
}

const retireIdleAssets = `-- name: RetireIdleAssets :exec
UPDATE aura.assets
SET status = 'deleting',
    deleted_at = now(),
    updated_at = now()
WHERE assets.id IN (
    SELECT idle.id FROM aura.assets AS idle
    WHERE idle.identity_id = $1
      AND idle.status = ANY($2::text[])
      AND idle.deleted_at IS NULL
      AND idle.updated_at < $3
    ORDER BY idle.updated_at ASC, idle.id ASC
    LIMIT $4
)
  AND assets.status = ANY($2::text[])
  AND assets.deleted_at IS NULL
  AND assets.updated_at < $3
`

type RetireIdleAssetsParams struct {
	IdentityID pgtype.UUID        `json:"identity_id"`
	Statuses   []string           `json:"statuses"`
	Cutoff     pgtype.Timestamptz `json:"cutoff"`
	RowLimit   int32              `json:"row_limit"`
}

// Marks deleting, oldest first, the identity's rows in one of the given statuses that nothing
// has written since the cutoff: an abandoned upload, or a refused or failed one kept past its
// lifetime. The outer conditions repeat the inner ones because Postgres re-checks only the
// outer ones on a row a concurrent write changed while this waited for its lock: a row a
// finalize or a retry moved on meanwhile is left alone.
func (q *Queries) RetireIdleAssets(ctx context.Context, arg RetireIdleAssetsParams) error {
	_, err := q.db.Exec(ctx, retireIdleAssets,
		arg.IdentityID,
		arg.Statuses,
		arg.Cutoff,
		arg.RowLimit,
	)
	return err
}

const softDeleteAsset = `-- name: SoftDeleteAsset :one
UPDATE aura.assets
SET status = 'deleting',
    deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND identity_id = $2
  AND deleted_at IS NULL
  AND status NOT IN ('deleting', 'deleted')
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id
`

type SoftDeleteAssetParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
}

// The durable intent of a delete. Stamping deleted_at hides the row from every identity-scoped
// read and every status write, so a job finishing on it later cannot bring it back;
// FinalizeAsset or MarkAssetDeleted then ends it once its object is gone.
func (q *Queries) SoftDeleteAsset(ctx context.Context, arg SoftDeleteAssetParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, softDeleteAsset, arg.ID, arg.IdentityID)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.PipelineGeneration,
		&i.ToolCallID,
	)
	return i, err
}

const updateAssetAccepted = `-- name: UpdateAssetAccepted :one
UPDATE aura.assets
SET status = 'accepted',
    size_bytes = $3,
    content_hash = $4,
    mime_type = $5,
    accepted_at = now(),
    updated_at = now()
WHERE id = $1
  AND identity_id = $2
  AND deleted_at IS NULL
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id
`

type UpdateAssetAcceptedParams struct {
	ID          pgtype.UUID `json:"id"`
	IdentityID  pgtype.UUID `json:"identity_id"`
	SizeBytes   int64       `json:"size_bytes"`
	ContentHash string      `json:"content_hash"`
	MimeType    string      `json:"mime_type"`
}

func (q *Queries) UpdateAssetAccepted(ctx context.Context, arg UpdateAssetAcceptedParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, updateAssetAccepted,
		arg.ID,
		arg.IdentityID,
		arg.SizeBytes,
		arg.ContentHash,
		arg.MimeType,
	)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.PipelineGeneration,
		&i.ToolCallID,
	)
	return i, err
}

const updateAssetResult = `-- name: UpdateAssetResult :one
UPDATE aura.assets
SET status = $3,
    document_id = $4,
    summary = $5,
    metadata = $6,
    error_code = '',
    error_message = '',
    processed_at = now(),
    completed_at = CASE WHEN $3 = 'complete' THEN now() ELSE completed_at END,
    updated_at = now()
WHERE id = $1
  AND identity_id = $2
  AND deleted_at IS NULL
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id
`

type UpdateAssetResultParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
	Status     string      `json:"status"`
	DocumentID string      `json:"document_id"`
	Summary    string      `json:"summary"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) UpdateAssetResult(ctx context.Context, arg UpdateAssetResultParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, updateAssetResult,
		arg.ID,
		arg.IdentityID,
		arg.Status,
		arg.DocumentID,
		arg.Summary,
		arg.Metadata,
	)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.PipelineGeneration,
		&i.ToolCallID,
	)
	return i, err
}

const updateAssetStatus = `-- name: UpdateAssetStatus :one
UPDATE aura.assets
SET status = $3,
    error_code = $4,
    error_message = $5,
    updated_at = now(),
    processed_at = CASE WHEN $3 IN ('complete', 'failed', 'refused') THEN now() ELSE processed_at END,
    completed_at = CASE WHEN $3 = 'complete' THEN now() ELSE completed_at END,
    deleted_at = CASE WHEN $3 = 'deleted' THEN now() ELSE deleted_at END
WHERE id = $1
  AND identity_id = $2
  AND deleted_at IS NULL
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id
`

type UpdateAssetStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	IdentityID   pgtype.UUID `json:"identity_id"`
	Status       string      `json:"status"`
	ErrorCode    string      `json:"error_code"`
	ErrorMessage string      `json:"error_message"`
}

func (q *Queries) UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, updateAssetStatus,
		arg.ID,
		arg.IdentityID,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.PipelineGeneration,
		&i.ToolCallID,
	)
	return i, err
}

const updateAssetUploaded = `-- name: UpdateAssetUploaded :one
UPDATE aura.assets
SET status = 'uploaded',
    size_bytes = $3,
    object_etag = $4,
    uploaded_at = now(),
    updated_at = now()
WHERE id = $1
  AND identity_id = $2
  AND deleted_at IS NULL
RETURNING id, identity_id, source_kind, source_ref, thread_id, scope, modality, status, file_name, mime_type, declared_size_bytes, size_bytes, content_hash, object_bucket, object_key, object_etag, document_id, summary, metadata, error_code, error_message, created_at, uploaded_at, accepted_at, processed_at, completed_at, deleted_at, updated_at, pipeline_generation, tool_call_id
`

type UpdateAssetUploadedParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
	SizeBytes  int64       `json:"size_bytes"`
	ObjectEtag string      `json:"object_etag"`
}

func (q *Queries) UpdateAssetUploaded(ctx context.Context, arg UpdateAssetUploadedParams) (AuraAssets, error) {
	row := q.db.QueryRow(ctx, updateAssetUploaded,
		arg.ID,
		arg.IdentityID,
		arg.SizeBytes,
		arg.ObjectEtag,
	)
	var i AuraAssets
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SourceKind,
		&i.SourceRef,
		&i.ThreadID,
		&i.Scope,
		&i.Modality,
		&i.Status,
		&i.FileName,
		&i.MimeType,
		&i.DeclaredSizeBytes,
		&i.SizeBytes,
		&i.ContentHash,
		&i.ObjectBucket,
		&i.ObjectKey,
		&i.ObjectEtag,
		&i.DocumentID,
		&i.Summary,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.AcceptedAt,
		&i.ProcessedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.PipelineGeneration,
		&i.ToolCallID,
	)
	return i, err
}
