// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBoardCard = `-- name: DeleteBoardCard :execrows
DELETE FROM aura.board_cards WHERE id = $1
`

func (q *Queries) DeleteBoardCard(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoardCard, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBoardView = `-- name: DeleteBoardView :execrows
DELETE FROM aura.board_views WHERE id = $1
`

func (q *Queries) DeleteBoardView(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoardView, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureBoard = `-- name: EnsureBoard :one
INSERT INTO aura.boards (identity_id, name, columns)
VALUES ($1, $2, $3)
ON CONFLICT (identity_id, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, identity_id, name, columns, created_at, updated_at
`

type EnsureBoardParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Name       string      `json:"name"`
	Columns    []byte      `json:"columns"`
}

// Creates the identity's board on first use and returns it either way. The no-op update makes
// RETURNING yield the existing row on conflict.
func (q *Queries) EnsureBoard(ctx context.Context, arg EnsureBoardParams) (AuraBoards, error) {
	row := q.db.QueryRow(ctx, ensureBoard, arg.IdentityID, arg.Name, arg.Columns)
	var i AuraBoards
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Name,
		&i.Columns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoardCard = `-- name: GetBoardCard :one
SELECT id, board_id, identity_id, column_id, position, label, description, priority, tags, due_at, conversation_id, task_id, source, updated_by, created_at, updated_at FROM aura.board_cards WHERE id = $1
`

func (q *Queries) GetBoardCard(ctx context.Context, id pgtype.UUID) (AuraBoardCards, error) {
	row := q.db.QueryRow(ctx, getBoardCard, id)
	var i AuraBoardCards
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.IdentityID,
		&i.ColumnID,
		&i.Position,
		&i.Label,
		&i.Description,
		&i.Priority,
		&i.Tags,
		&i.DueAt,
		&i.ConversationID,
		&i.TaskID,
		&i.Source,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBoardCard = `-- name: InsertBoardCard :one
INSERT INTO aura.board_cards (
    board_id, identity_id, column_id, position, label, description, priority, tags, due_at,
    conversation_id, task_id, source, updated_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, board_id, identity_id, column_id, position, label, description, priority, tags, due_at, conversation_id, task_id, source, updated_by, created_at, updated_at
`

type InsertBoardCardParams struct {
	BoardID        pgtype.UUID        `json:"board_id"`
	IdentityID     pgtype.UUID        `json:"identity_id"`
	ColumnID       string             `json:"column_id"`
	Position       float64            `json:"position"`
	Label          string             `json:"label"`
	Description    string             `json:"description"`
	Priority       int16              `json:"priority"`
	Tags           []string           `json:"tags"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	TaskID         pgtype.UUID        `json:"task_id"`
	Source         string             `json:"source"`
	UpdatedBy      string             `json:"updated_by"`
}

func (q *Queries) InsertBoardCard(ctx context.Context, arg InsertBoardCardParams) (AuraBoardCards, error) {
	row := q.db.QueryRow(ctx, insertBoardCard,
		arg.BoardID,
		arg.IdentityID,
		arg.ColumnID,
		arg.Position,
		arg.Label,
		arg.Description,
		arg.Priority,
		arg.Tags,
		arg.DueAt,
		arg.ConversationID,
		arg.TaskID,
		arg.Source,
		arg.UpdatedBy,
	)
	var i AuraBoardCards
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.IdentityID,
		&i.ColumnID,
		&i.Position,
		&i.Label,
		&i.Description,
		&i.Priority,
		&i.Tags,
		&i.DueAt,
		&i.ConversationID,
		&i.TaskID,
		&i.Source,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoardCards = `-- name: ListBoardCards :many
SELECT id, board_id, identity_id, column_id, position, label, description, priority, tags, due_at, conversation_id, task_id, source, updated_by, created_at, updated_at FROM aura.board_cards
WHERE board_id = $1
ORDER BY column_id, position
`

func (q *Queries) ListBoardCards(ctx context.Context, boardID pgtype.UUID) ([]AuraBoardCards, error) {
	rows, err := q.db.Query(ctx, listBoardCards, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraBoardCards{}
	for rows.Next() {
		var i AuraBoardCards
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.IdentityID,
			&i.ColumnID,
			&i.Position,
			&i.Label,
			&i.Description,
			&i.Priority,
			&i.Tags,
			&i.DueAt,
			&i.ConversationID,
			&i.TaskID,
			&i.Source,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardColumnCards = `-- name: ListBoardColumnCards :many
SELECT id, board_id, identity_id, column_id, position, label, description, priority, tags, due_at, conversation_id, task_id, source, updated_by, created_at, updated_at FROM aura.board_cards
WHERE board_id = $1 AND column_id = $2
ORDER BY position
`

type ListBoardColumnCardsParams struct {
	BoardID  pgtype.UUID `json:"board_id"`
	ColumnID string      `json:"column_id"`
}

func (q *Queries) ListBoardColumnCards(ctx context.Context, arg ListBoardColumnCardsParams) ([]AuraBoardCards, error) {
	rows, err := q.db.Query(ctx, listBoardColumnCards, arg.BoardID, arg.ColumnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraBoardCards{}
	for rows.Next() {
		var i AuraBoardCards
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.IdentityID,
			&i.ColumnID,
			&i.Position,
			&i.Label,
			&i.Description,
			&i.Priority,
			&i.Tags,
			&i.DueAt,
			&i.ConversationID,
			&i.TaskID,
			&i.Source,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardViews = `-- name: ListBoardViews :many
SELECT id, identity_id, name, filters, pinned, created_at FROM aura.board_views
WHERE identity_id = $1
ORDER BY pinned DESC, name
`

func (q *Queries) ListBoardViews(ctx context.Context, identityID pgtype.UUID) ([]AuraBoardViews, error) {
	rows, err := q.db.Query(ctx, listBoardViews, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraBoardViews{}
	for rows.Next() {
		var i AuraBoardViews
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Name,
			&i.Filters,
			&i.Pinned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveBoardCard = `-- name: MoveBoardCard :one
UPDATE aura.board_cards
SET column_id = $2, position = $3, updated_by = $4, updated_at = now()
WHERE id = $1
RETURNING id, board_id, identity_id, column_id, position, label, description, priority, tags, due_at, conversation_id, task_id, source, updated_by, created_at, updated_at
`

type MoveBoardCardParams struct {
	ID        pgtype.UUID `json:"id"`
	ColumnID  string      `json:"column_id"`
	Position  float64     `json:"position"`
	UpdatedBy string      `json:"updated_by"`
}

func (q *Queries) MoveBoardCard(ctx context.Context, arg MoveBoardCardParams) (AuraBoardCards, error) {
	row := q.db.QueryRow(ctx, moveBoardCard,
		arg.ID,
		arg.ColumnID,
		arg.Position,
		arg.UpdatedBy,
	)
	var i AuraBoardCards
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.IdentityID,
		&i.ColumnID,
		&i.Position,
		&i.Label,
		&i.Description,
		&i.Priority,
		&i.Tags,
		&i.DueAt,
		&i.ConversationID,
		&i.TaskID,
		&i.Source,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchBoardCards = `-- name: SearchBoardCards :many
SELECT id, board_id, identity_id, column_id, position, label, description, priority, tags, due_at, conversation_id, task_id, source, updated_by, created_at, updated_at FROM aura.board_cards
WHERE board_id = $1
  AND (label ILIKE '%' || $2::text || '%'
       OR description ILIKE '%' || $2::text || '%'
       OR $2::text = ANY (tags))
ORDER BY updated_at DESC
LIMIT $3
`

type SearchBoardCardsParams struct {
	BoardID  pgtype.UUID `json:"board_id"`
	Query    string      `json:"query"`
	RowLimit int32       `json:"row_limit"`
}

func (q *Queries) SearchBoardCards(ctx context.Context, arg SearchBoardCardsParams) ([]AuraBoardCards, error) {
	rows, err := q.db.Query(ctx, searchBoardCards, arg.BoardID, arg.Query, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraBoardCards{}
	for rows.Next() {
		var i AuraBoardCards
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.IdentityID,
			&i.ColumnID,
			&i.Position,
			&i.Label,
			&i.Description,
			&i.Priority,
			&i.Tags,
			&i.DueAt,
			&i.ConversationID,
			&i.TaskID,
			&i.Source,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBoardCardPosition = `-- name: SetBoardCardPosition :exec
UPDATE aura.board_cards SET position = $2 WHERE id = $1
`

type SetBoardCardPositionParams struct {
	ID       pgtype.UUID `json:"id"`
	Position float64     `json:"position"`
}

func (q *Queries) SetBoardCardPosition(ctx context.Context, arg SetBoardCardPositionParams) error {
	_, err := q.db.Exec(ctx, setBoardCardPosition, arg.ID, arg.Position)
	return err
}

const updateBoardCard = `-- name: UpdateBoardCard :one
UPDATE aura.board_cards
SET label = $2, description = $3, priority = $4, tags = $5, due_at = $6, task_id = $7,
    updated_by = $8, updated_at = now()
WHERE id = $1
RETURNING id, board_id, identity_id, column_id, position, label, description, priority, tags, due_at, conversation_id, task_id, source, updated_by, created_at, updated_at
`

type UpdateBoardCardParams struct {
	ID          pgtype.UUID        `json:"id"`
	Label       string             `json:"label"`
	Description string             `json:"description"`
	Priority    int16              `json:"priority"`
	Tags        []string           `json:"tags"`
	DueAt       pgtype.Timestamptz `json:"due_at"`
	TaskID      pgtype.UUID        `json:"task_id"`
	UpdatedBy   string             `json:"updated_by"`
}

func (q *Queries) UpdateBoardCard(ctx context.Context, arg UpdateBoardCardParams) (AuraBoardCards, error) {
	row := q.db.QueryRow(ctx, updateBoardCard,
		arg.ID,
		arg.Label,
		arg.Description,
		arg.Priority,
		arg.Tags,
		arg.DueAt,
		arg.TaskID,
		arg.UpdatedBy,
	)
	var i AuraBoardCards
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.IdentityID,
		&i.ColumnID,
		&i.Position,
		&i.Label,
		&i.Description,
		&i.Priority,
		&i.Tags,
		&i.DueAt,
		&i.ConversationID,
		&i.TaskID,
		&i.Source,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBoardColumns = `-- name: UpdateBoardColumns :one
UPDATE aura.boards
SET columns = $2, updated_at = now()
WHERE id = $1
RETURNING id, identity_id, name, columns, created_at, updated_at
`

type UpdateBoardColumnsParams struct {
	ID      pgtype.UUID `json:"id"`
	Columns []byte      `json:"columns"`
}

func (q *Queries) UpdateBoardColumns(ctx context.Context, arg UpdateBoardColumnsParams) (AuraBoards, error) {
	row := q.db.QueryRow(ctx, updateBoardColumns, arg.ID, arg.Columns)
	var i AuraBoards
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Name,
		&i.Columns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBoardView = `-- name: UpsertBoardView :one
INSERT INTO aura.board_views (identity_id, name, filters, pinned)
VALUES ($1, $2, $3, $4)
ON CONFLICT (identity_id, name) DO UPDATE SET filters = EXCLUDED.filters, pinned = EXCLUDED.pinned
RETURNING id, identity_id, name, filters, pinned, created_at
`

type UpsertBoardViewParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Name       string      `json:"name"`
	Filters    []byte      `json:"filters"`
	Pinned     bool        `json:"pinned"`
}

func (q *Queries) UpsertBoardView(ctx context.Context, arg UpsertBoardViewParams) (AuraBoardViews, error) {
	row := q.db.QueryRow(ctx, upsertBoardView,
		arg.IdentityID,
		arg.Name,
		arg.Filters,
		arg.Pinned,
	)
	var i AuraBoardViews
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Name,
		&i.Filters,
		&i.Pinned,
		&i.CreatedAt,
	)
	return i, err
}
