// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capability_grants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const grantCapability = `-- name: GrantCapability :exec
INSERT INTO aura.capability_grants (identity_id, capability)
VALUES ($1, $2)
ON CONFLICT (identity_id, capability) DO NOTHING
`

type GrantCapabilityParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Capability string      `json:"capability"`
}

func (q *Queries) GrantCapability(ctx context.Context, arg GrantCapabilityParams) error {
	_, err := q.db.Exec(ctx, grantCapability, arg.IdentityID, arg.Capability)
	return err
}

const hasCapability = `-- name: HasCapability :one
SELECT EXISTS (
    SELECT 1
    FROM aura.capability_grants
    WHERE identity_id = $1
      AND (capability = '*' OR capability = $2)
) AS has_capability
`

type HasCapabilityParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Capability string      `json:"capability"`
}

func (q *Queries) HasCapability(ctx context.Context, arg HasCapabilityParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasCapability, arg.IdentityID, arg.Capability)
	var has_capability bool
	err := row.Scan(&has_capability)
	return has_capability, err
}

const listCapabilities = `-- name: ListCapabilities :many
SELECT identity_id, capability, granted_at
FROM aura.capability_grants
WHERE identity_id = $1
ORDER BY capability ASC
`

func (q *Queries) ListCapabilities(ctx context.Context, identityID pgtype.UUID) ([]AuraCapabilityGrants, error) {
	rows, err := q.db.Query(ctx, listCapabilities, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraCapabilityGrants{}
	for rows.Next() {
		var i AuraCapabilityGrants
		if err := rows.Scan(&i.IdentityID, &i.Capability, &i.GrantedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCapability = `-- name: RevokeCapability :exec
DELETE FROM aura.capability_grants
WHERE identity_id = $1
  AND capability = $2
`

type RevokeCapabilityParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Capability string      `json:"capability"`
}

func (q *Queries) RevokeCapability(ctx context.Context, arg RevokeCapabilityParams) error {
	_, err := q.db.Exec(ctx, revokeCapability, arg.IdentityID, arg.Capability)
	return err
}
