// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compaction_rollout.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendCompactionRolloutDecision = `-- name: AppendCompactionRolloutDecision :one
INSERT INTO aura.compaction_rollout_decisions (
    scope_id, evidence_id, expected_version, resulting_version,
    decision_kind, from_stage, to_stage, reason_code
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, scope_id, evidence_id, expected_version, resulting_version, decision_kind, from_stage, to_stage, reason_code, created_at
`

type AppendCompactionRolloutDecisionParams struct {
	ScopeID          string      `json:"scope_id"`
	EvidenceID       pgtype.UUID `json:"evidence_id"`
	ExpectedVersion  int64       `json:"expected_version"`
	ResultingVersion int64       `json:"resulting_version"`
	DecisionKind     string      `json:"decision_kind"`
	FromStage        string      `json:"from_stage"`
	ToStage          string      `json:"to_stage"`
	ReasonCode       string      `json:"reason_code"`
}

func (q *Queries) AppendCompactionRolloutDecision(ctx context.Context, arg AppendCompactionRolloutDecisionParams) (AuraCompactionRolloutDecisions, error) {
	row := q.db.QueryRow(ctx, appendCompactionRolloutDecision,
		arg.ScopeID,
		arg.EvidenceID,
		arg.ExpectedVersion,
		arg.ResultingVersion,
		arg.DecisionKind,
		arg.FromStage,
		arg.ToStage,
		arg.ReasonCode,
	)
	var i AuraCompactionRolloutDecisions
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.EvidenceID,
		&i.ExpectedVersion,
		&i.ResultingVersion,
		&i.DecisionKind,
		&i.FromStage,
		&i.ToStage,
		&i.ReasonCode,
		&i.CreatedAt,
	)
	return i, err
}

const appendCompactionRolloutEvidence = `-- name: AppendCompactionRolloutEvidence :one
INSERT INTO aura.compaction_rollout_evidence (
    scope_id, evidence_digest, evaluator_version, scorer_version,
    config_version, corpus_version, snapshot
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (scope_id, evidence_digest) DO NOTHING
RETURNING id, scope_id, evidence_digest, evaluator_version, scorer_version, config_version, corpus_version, snapshot, created_at
`

type AppendCompactionRolloutEvidenceParams struct {
	ScopeID          string `json:"scope_id"`
	EvidenceDigest   string `json:"evidence_digest"`
	EvaluatorVersion string `json:"evaluator_version"`
	ScorerVersion    string `json:"scorer_version"`
	ConfigVersion    string `json:"config_version"`
	CorpusVersion    string `json:"corpus_version"`
	Snapshot         []byte `json:"snapshot"`
}

// Digest-addressed and idempotent: a byte-identical observation (same scope_id +
// evidence_digest) re-appended by a repeated evaluator decision is a no-op instead of
// a fatal 23505. DO NOTHING (not DO UPDATE) is mandatory — the ledger's BEFORE-UPDATE
// immutability trigger forbids UPDATE — so the wrapper re-fetches the existing row via
// GetCompactionRolloutEvidenceByDigest on the resulting no-rows return (Wave 0.1).
func (q *Queries) AppendCompactionRolloutEvidence(ctx context.Context, arg AppendCompactionRolloutEvidenceParams) (AuraCompactionRolloutEvidence, error) {
	row := q.db.QueryRow(ctx, appendCompactionRolloutEvidence,
		arg.ScopeID,
		arg.EvidenceDigest,
		arg.EvaluatorVersion,
		arg.ScorerVersion,
		arg.ConfigVersion,
		arg.CorpusVersion,
		arg.Snapshot,
	)
	var i AuraCompactionRolloutEvidence
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.EvidenceDigest,
		&i.EvaluatorVersion,
		&i.ScorerVersion,
		&i.ConfigVersion,
		&i.CorpusVersion,
		&i.Snapshot,
		&i.CreatedAt,
	)
	return i, err
}

const cASRollbackCompactionRollout = `-- name: CASRollbackCompactionRollout :one
UPDATE aura.compaction_rollout_states
SET version = version + 1,
    stage = 'disabled',
    stage_started_at = now(),
    active_config = last_known_good_config,
    stratum_snapshots = '{}'::jsonb,
    failure_window = '{}'::jsonb,
    latency_window = '{}'::jsonb,
    restore_window = '{}'::jsonb,
    updated_at = now()
WHERE scope_id = $1 AND version = $2
RETURNING scope_id, version, stage, stage_started_at, eligible_attempts, evaluator_version, scorer_version, config_version, corpus_version, stratum_snapshots, failure_window, latency_window, restore_window, active_config, last_known_good_config, last_known_good_policy, created_at, updated_at
`

type CASRollbackCompactionRolloutParams struct {
	ScopeID         string `json:"scope_id"`
	ExpectedVersion int64  `json:"expected_version"`
}

func (q *Queries) CASRollbackCompactionRollout(ctx context.Context, arg CASRollbackCompactionRolloutParams) (AuraCompactionRolloutStates, error) {
	row := q.db.QueryRow(ctx, cASRollbackCompactionRollout, arg.ScopeID, arg.ExpectedVersion)
	var i AuraCompactionRolloutStates
	err := row.Scan(
		&i.ScopeID,
		&i.Version,
		&i.Stage,
		&i.StageStartedAt,
		&i.EligibleAttempts,
		&i.EvaluatorVersion,
		&i.ScorerVersion,
		&i.ConfigVersion,
		&i.CorpusVersion,
		&i.StratumSnapshots,
		&i.FailureWindow,
		&i.LatencyWindow,
		&i.RestoreWindow,
		&i.ActiveConfig,
		&i.LastKnownGoodConfig,
		&i.LastKnownGoodPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cASTransitionCompactionRollout = `-- name: CASTransitionCompactionRollout :one
UPDATE aura.compaction_rollout_states
SET version = version + 1,
    stage = $1,
    stage_started_at = $2,
    eligible_attempts = $3,
    evaluator_version = $4,
    scorer_version = $5,
    config_version = $6,
    corpus_version = $7,
    stratum_snapshots = $8,
    failure_window = $9,
    latency_window = $10,
    restore_window = $11,
    active_config = $12,
    last_known_good_config = $13,
    last_known_good_policy = $14,
    updated_at = now()
WHERE scope_id = $15 AND version = $16
RETURNING scope_id, version, stage, stage_started_at, eligible_attempts, evaluator_version, scorer_version, config_version, corpus_version, stratum_snapshots, failure_window, latency_window, restore_window, active_config, last_known_good_config, last_known_good_policy, created_at, updated_at
`

type CASTransitionCompactionRolloutParams struct {
	Stage               string             `json:"stage"`
	StageStartedAt      pgtype.Timestamptz `json:"stage_started_at"`
	EligibleAttempts    int64              `json:"eligible_attempts"`
	EvaluatorVersion    string             `json:"evaluator_version"`
	ScorerVersion       string             `json:"scorer_version"`
	ConfigVersion       string             `json:"config_version"`
	CorpusVersion       string             `json:"corpus_version"`
	StratumSnapshots    []byte             `json:"stratum_snapshots"`
	FailureWindow       []byte             `json:"failure_window"`
	LatencyWindow       []byte             `json:"latency_window"`
	RestoreWindow       []byte             `json:"restore_window"`
	ActiveConfig        []byte             `json:"active_config"`
	LastKnownGoodConfig []byte             `json:"last_known_good_config"`
	LastKnownGoodPolicy []byte             `json:"last_known_good_policy"`
	ScopeID             string             `json:"scope_id"`
	ExpectedVersion     int64              `json:"expected_version"`
}

func (q *Queries) CASTransitionCompactionRollout(ctx context.Context, arg CASTransitionCompactionRolloutParams) (AuraCompactionRolloutStates, error) {
	row := q.db.QueryRow(ctx, cASTransitionCompactionRollout,
		arg.Stage,
		arg.StageStartedAt,
		arg.EligibleAttempts,
		arg.EvaluatorVersion,
		arg.ScorerVersion,
		arg.ConfigVersion,
		arg.CorpusVersion,
		arg.StratumSnapshots,
		arg.FailureWindow,
		arg.LatencyWindow,
		arg.RestoreWindow,
		arg.ActiveConfig,
		arg.LastKnownGoodConfig,
		arg.LastKnownGoodPolicy,
		arg.ScopeID,
		arg.ExpectedVersion,
	)
	var i AuraCompactionRolloutStates
	err := row.Scan(
		&i.ScopeID,
		&i.Version,
		&i.Stage,
		&i.StageStartedAt,
		&i.EligibleAttempts,
		&i.EvaluatorVersion,
		&i.ScorerVersion,
		&i.ConfigVersion,
		&i.CorpusVersion,
		&i.StratumSnapshots,
		&i.FailureWindow,
		&i.LatencyWindow,
		&i.RestoreWindow,
		&i.ActiveConfig,
		&i.LastKnownGoodConfig,
		&i.LastKnownGoodPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCompactionRolloutDecisions = `-- name: CountCompactionRolloutDecisions :one
SELECT count(*) FROM aura.compaction_rollout_decisions WHERE scope_id = $1
`

func (q *Queries) CountCompactionRolloutDecisions(ctx context.Context, scopeID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCompactionRolloutDecisions, scopeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompactionRolloutState = `-- name: CreateCompactionRolloutState :one
INSERT INTO aura.compaction_rollout_states (
    scope_id, evaluator_version, scorer_version, config_version, corpus_version,
    active_config, last_known_good_config, last_known_good_policy
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (scope_id) DO NOTHING
RETURNING scope_id, version, stage, stage_started_at, eligible_attempts, evaluator_version, scorer_version, config_version, corpus_version, stratum_snapshots, failure_window, latency_window, restore_window, active_config, last_known_good_config, last_known_good_policy, created_at, updated_at
`

type CreateCompactionRolloutStateParams struct {
	ScopeID             string `json:"scope_id"`
	EvaluatorVersion    string `json:"evaluator_version"`
	ScorerVersion       string `json:"scorer_version"`
	ConfigVersion       string `json:"config_version"`
	CorpusVersion       string `json:"corpus_version"`
	ActiveConfig        []byte `json:"active_config"`
	LastKnownGoodConfig []byte `json:"last_known_good_config"`
	LastKnownGoodPolicy []byte `json:"last_known_good_policy"`
}

func (q *Queries) CreateCompactionRolloutState(ctx context.Context, arg CreateCompactionRolloutStateParams) (AuraCompactionRolloutStates, error) {
	row := q.db.QueryRow(ctx, createCompactionRolloutState,
		arg.ScopeID,
		arg.EvaluatorVersion,
		arg.ScorerVersion,
		arg.ConfigVersion,
		arg.CorpusVersion,
		arg.ActiveConfig,
		arg.LastKnownGoodConfig,
		arg.LastKnownGoodPolicy,
	)
	var i AuraCompactionRolloutStates
	err := row.Scan(
		&i.ScopeID,
		&i.Version,
		&i.Stage,
		&i.StageStartedAt,
		&i.EligibleAttempts,
		&i.EvaluatorVersion,
		&i.ScorerVersion,
		&i.ConfigVersion,
		&i.CorpusVersion,
		&i.StratumSnapshots,
		&i.FailureWindow,
		&i.LatencyWindow,
		&i.RestoreWindow,
		&i.ActiveConfig,
		&i.LastKnownGoodConfig,
		&i.LastKnownGoodPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompactionRolloutEvidenceByDigest = `-- name: GetCompactionRolloutEvidenceByDigest :one
SELECT id, scope_id, evidence_digest, evaluator_version, scorer_version, config_version, corpus_version, snapshot, created_at FROM aura.compaction_rollout_evidence
WHERE scope_id = $1 AND evidence_digest = $2
`

type GetCompactionRolloutEvidenceByDigestParams struct {
	ScopeID        string `json:"scope_id"`
	EvidenceDigest string `json:"evidence_digest"`
}

func (q *Queries) GetCompactionRolloutEvidenceByDigest(ctx context.Context, arg GetCompactionRolloutEvidenceByDigestParams) (AuraCompactionRolloutEvidence, error) {
	row := q.db.QueryRow(ctx, getCompactionRolloutEvidenceByDigest, arg.ScopeID, arg.EvidenceDigest)
	var i AuraCompactionRolloutEvidence
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.EvidenceDigest,
		&i.EvaluatorVersion,
		&i.ScorerVersion,
		&i.ConfigVersion,
		&i.CorpusVersion,
		&i.Snapshot,
		&i.CreatedAt,
	)
	return i, err
}

const getCompactionRolloutState = `-- name: GetCompactionRolloutState :one
SELECT scope_id, version, stage, stage_started_at, eligible_attempts, evaluator_version, scorer_version, config_version, corpus_version, stratum_snapshots, failure_window, latency_window, restore_window, active_config, last_known_good_config, last_known_good_policy, created_at, updated_at FROM aura.compaction_rollout_states WHERE scope_id = $1
`

func (q *Queries) GetCompactionRolloutState(ctx context.Context, scopeID string) (AuraCompactionRolloutStates, error) {
	row := q.db.QueryRow(ctx, getCompactionRolloutState, scopeID)
	var i AuraCompactionRolloutStates
	err := row.Scan(
		&i.ScopeID,
		&i.Version,
		&i.Stage,
		&i.StageStartedAt,
		&i.EligibleAttempts,
		&i.EvaluatorVersion,
		&i.ScorerVersion,
		&i.ConfigVersion,
		&i.CorpusVersion,
		&i.StratumSnapshots,
		&i.FailureWindow,
		&i.LatencyWindow,
		&i.RestoreWindow,
		&i.ActiveConfig,
		&i.LastKnownGoodConfig,
		&i.LastKnownGoodPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
