// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context_rot_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertContextRotEvent = `-- name: InsertContextRotEvent :exec
INSERT INTO aura.context_rot_events (
    conversation_id, action, pairs_dropped, tokens_before, tokens_after
) VALUES ($1, $2, $3, $4, $5)
`

type InsertContextRotEventParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Action         string      `json:"action"`
	PairsDropped   int32       `json:"pairs_dropped"`
	TokensBefore   int32       `json:"tokens_before"`
	TokensAfter    int32       `json:"tokens_after"`
}

func (q *Queries) InsertContextRotEvent(ctx context.Context, arg InsertContextRotEventParams) error {
	_, err := q.db.Exec(ctx, insertContextRotEvent,
		arg.ConversationID,
		arg.Action,
		arg.PairsDropped,
		arg.TokensBefore,
		arg.TokensAfter,
	)
	return err
}

const listContextRotEvents = `-- name: ListContextRotEvents :many
SELECT ts, conversation_id, action, pairs_dropped, tokens_before, tokens_after
FROM aura.context_rot_events
WHERE conversation_id = $1
ORDER BY ts ASC
`

func (q *Queries) ListContextRotEvents(ctx context.Context, conversationID pgtype.UUID) ([]AuraContextRotEvents, error) {
	rows, err := q.db.Query(ctx, listContextRotEvents, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraContextRotEvents{}
	for rows.Next() {
		var i AuraContextRotEvents
		if err := rows.Scan(
			&i.Ts,
			&i.ConversationID,
			&i.Action,
			&i.PairsDropped,
			&i.TokensBefore,
			&i.TokensAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
