// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_turns.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const canonicalBranchLeafSeq = `-- name: CanonicalBranchLeafSeq :one
SELECT COALESCE(MAX(seq), 0)::int AS leaf_seq
FROM aura.conversation_turns
WHERE conversation_id = $1
  AND branch_id = '00000000-0000-0000-0000-000000000000'
`

// D-09 (CHAT-05): the leaf (deepest) seq of a conversation's canonical branch — the
// all-zero sentinel branch every pre-0017 turn is backfilled onto. For a non-branched
// conversation this is just MAX(seq), so a branch-path walk from this leaf reconstructs
// the same linear history ListTurnsBySeq returns (byte-identity, store.go:250). Returns
// 0 when the conversation has no turns.
func (q *Queries) CanonicalBranchLeafSeq(ctx context.Context, conversationID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, canonicalBranchLeafSeq, conversationID)
	var leaf_seq int32
	err := row.Scan(&leaf_seq)
	return leaf_seq, err
}

const countTurns = `-- name: CountTurns :one
SELECT count(*) AS turn_count
FROM aura.conversation_turns
WHERE conversation_id = $1
`

func (q *Queries) CountTurns(ctx context.Context, conversationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTurns, conversationID)
	var turn_count int64
	err := row.Scan(&turn_count)
	return turn_count, err
}

const getConversationCompaction = `-- name: GetConversationCompaction :one
SELECT conversation_id, branch_id, covers_through_seq, summary, model, source_turns,
       created_at, updated_at
FROM aura.conversation_compactions
WHERE conversation_id = $1 AND branch_id = $2
`

type GetConversationCompactionParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	BranchID       pgtype.UUID `json:"branch_id"`
}

// The durable summary of this branch's earlier turns (migration 0096, HANDOFF 6.1).
// Returns pgx.ErrNoRows when the branch has never been compacted, which is the normal
// state of every conversation short enough to fit its window.
func (q *Queries) GetConversationCompaction(ctx context.Context, arg GetConversationCompactionParams) (AuraConversationCompactions, error) {
	row := q.db.QueryRow(ctx, getConversationCompaction, arg.ConversationID, arg.BranchID)
	var i AuraConversationCompactions
	err := row.Scan(
		&i.ConversationID,
		&i.BranchID,
		&i.CoversThroughSeq,
		&i.Summary,
		&i.Model,
		&i.SourceTurns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTurnPointers = `-- name: GetTurnPointers :one
SELECT seq, branch_id, parent_seq, role
FROM aura.conversation_turns
WHERE conversation_id = $1 AND seq = $2
`

type GetTurnPointersParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Seq            int32       `json:"seq"`
}

type GetTurnPointersRow struct {
	Seq       int32       `json:"seq"`
	BranchID  pgtype.UUID `json:"branch_id"`
	ParentSeq pgtype.Int4 `json:"parent_seq"`
	Role      string      `json:"role"`
}

// D-09 (CHAT-05): a turn's own branch/parent pointers, used by the fork path to read the
// diverging turn's parent_seq (the new sibling chains off the SAME parent so it replaces
// the diverging turn rather than appending after it). Returns pgx.ErrNoRows when the seq
// is absent (mapped to a clean 404 at the boundary).
func (q *Queries) GetTurnPointers(ctx context.Context, arg GetTurnPointersParams) (GetTurnPointersRow, error) {
	row := q.db.QueryRow(ctx, getTurnPointers, arg.ConversationID, arg.Seq)
	var i GetTurnPointersRow
	err := row.Scan(
		&i.Seq,
		&i.BranchID,
		&i.ParentSeq,
		&i.Role,
	)
	return i, err
}

const insertConversationTurn = `-- name: InsertConversationTurn :execrows
INSERT INTO aura.conversation_turns (
    conversation_id, seq, role, content, content_sidecar_path,
    tool_call_id, tool_calls, input_tokens, output_tokens, cached_tokens,
    reasoning, reasoning_duration_ms, context_tokens, parent_seq, delivery_key,
    attachment_ids
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
    NULLIF($2::int - 1, 0), $14, $15
)
ON CONFLICT (conversation_id, delivery_key) WHERE delivery_key IS NOT NULL
DO NOTHING
`

type InsertConversationTurnParams struct {
	ConversationID      pgtype.UUID   `json:"conversation_id"`
	Seq                 int32         `json:"seq"`
	Role                string        `json:"role"`
	Content             pgtype.Text   `json:"content"`
	ContentSidecarPath  pgtype.Text   `json:"content_sidecar_path"`
	ToolCallID          pgtype.Text   `json:"tool_call_id"`
	ToolCalls           []byte        `json:"tool_calls"`
	InputTokens         int32         `json:"input_tokens"`
	OutputTokens        int32         `json:"output_tokens"`
	CachedTokens        int32         `json:"cached_tokens"`
	Reasoning           pgtype.Text   `json:"reasoning"`
	ReasoningDurationMs pgtype.Int8   `json:"reasoning_duration_ms"`
	ContextTokens       int32         `json:"context_tokens"`
	DeliveryKey         pgtype.Text   `json:"delivery_key"`
	AttachmentIds       []pgtype.UUID `json:"attachment_ids"`
}

// parent_seq maintains the canonical leaf->root chain the branch walk recurses on
// (ListManagedBranchPathPage joins `t.seq = p.parent_seq`). It is derived here rather
// than bound as a parameter so no call site can forget it — which is exactly what
// happened: 0017 added the column, backfilled `seq - 1` for the rows present at
// migration time, and gave it no default, so EVERY turn appended since carried NULL. A
// NULL breaks the join, so a forked branch reconstructed to the forked turn ALONE —
// measured 2026-08-13 against the live schema, one turn, not even the system head — and
// the model lost the whole prior conversation on any edit/regenerate.
// NULLIF keeps seq=1 (the root) at NULL, matching that backfill's `WHERE seq > 1`.
func (q *Queries) InsertConversationTurn(ctx context.Context, arg InsertConversationTurnParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertConversationTurn,
		arg.ConversationID,
		arg.Seq,
		arg.Role,
		arg.Content,
		arg.ContentSidecarPath,
		arg.ToolCallID,
		arg.ToolCalls,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.Reasoning,
		arg.ReasoningDurationMs,
		arg.ContextTokens,
		arg.DeliveryKey,
		arg.AttachmentIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAssistantTurnReasoning = `-- name: ListAssistantTurnReasoning :many
SELECT seq, reasoning, reasoning_duration_ms
FROM aura.conversation_turns
WHERE conversation_id = $1
  AND role = 'assistant'
  AND (tool_calls IS NULL OR tool_calls = '[]'::jsonb OR tool_calls = 'null'::jsonb)
ORDER BY seq ASC
`

type ListAssistantTurnReasoningRow struct {
	Seq                 int32       `json:"seq"`
	Reasoning           pgtype.Text `json:"reasoning"`
	ReasoningDurationMs pgtype.Int8 `json:"reasoning_duration_ms"`
}

// Amendment #91 (fix-plan 1.12) display-only read: the reasoning columns for every
// answer-shaped assistant turn (no tool_calls payload), ordered by seq. Deliberately
// SEPARATE from ListTurnsBySeq so the llm.Message history rebuild can never select
// reasoning. Scope mirrors ListTurnsBySeq exactly (conversation-wide, no branch
// filter) so the snapshot merge pairs positionally with the LoadHistory projection.
// The tool_calls filter mirrors turnToMessage's Go semantics: rows whose tool_calls
// decode to zero calls ('[]'/'null') count as answer-shaped there too.
func (q *Queries) ListAssistantTurnReasoning(ctx context.Context, conversationID pgtype.UUID) ([]ListAssistantTurnReasoningRow, error) {
	rows, err := q.db.Query(ctx, listAssistantTurnReasoning, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssistantTurnReasoningRow{}
	for rows.Next() {
		var i ListAssistantTurnReasoningRow
		if err := rows.Scan(&i.Seq, &i.Reasoning, &i.ReasoningDurationMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranchLeaves = `-- name: ListBranchLeaves :many
SELECT leaf.seq, leaf.branch_id, leaf.parent_seq
FROM aura.conversation_turns leaf
WHERE leaf.conversation_id = $1
  AND NOT EXISTS (
      SELECT 1
      FROM aura.conversation_turns child
      WHERE child.conversation_id = leaf.conversation_id
        AND child.parent_seq = leaf.seq
  )
ORDER BY leaf.branch_id ASC, leaf.seq ASC
`

type ListBranchLeavesRow struct {
	Seq       int32       `json:"seq"`
	BranchID  pgtype.UUID `json:"branch_id"`
	ParentSeq pgtype.Int4 `json:"parent_seq"`
}

// D-09 (CHAT-05): the navigable branch set. A leaf is a turn that is NOT the parent of
// any other turn (no row's parent_seq points at it) — i.e. the tip of a branch path. The
// BranchPicker navigates among these sibling leaves; a re-run continues over the selected
// leaf's path (ListTurnsByBranchPath). Ordered by branch_id then seq so the canonical
// (all-zero) branch sorts first and the order is stable across calls.
func (q *Queries) ListBranchLeaves(ctx context.Context, conversationID pgtype.UUID) ([]ListBranchLeavesRow, error) {
	rows, err := q.db.Query(ctx, listBranchLeaves, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBranchLeavesRow{}
	for rows.Next() {
		var i ListBranchLeavesRow
		if err := rows.Scan(&i.Seq, &i.BranchID, &i.ParentSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedBranchPathPage = `-- name: ListManagedBranchPathPage :many
WITH RECURSIVE path AS (
    SELECT ct.conversation_id, ct.seq, ct.role, ct.content, ct.content_sidecar_path,
           ct.tool_call_id, ct.tool_calls, ct.created_at, ct.input_tokens, ct.output_tokens,
           ct.cached_tokens, ct.branch_id, ct.parent_seq, 1::int AS depth
    FROM aura.conversation_turns ct
    WHERE ct.conversation_id = $1
      AND ct.seq = $2
    UNION ALL
    SELECT t.conversation_id, t.seq, t.role, t.content, t.content_sidecar_path,
           t.tool_call_id, t.tool_calls, t.created_at, t.input_tokens, t.output_tokens,
           t.cached_tokens, t.branch_id, t.parent_seq, p.depth + 1
    FROM aura.conversation_turns t
    JOIN path p
      ON t.conversation_id = p.conversation_id
     AND t.seq = p.parent_seq
    WHERE p.depth < GREATEST($3::int, 1)
)
SELECT path.conversation_id, path.seq, path.role, path.content,
       path.content_sidecar_path, path.tool_call_id, path.tool_calls,
       path.created_at, path.input_tokens, path.output_tokens, path.cached_tokens,
       path.parent_seq, path.depth
FROM path
ORDER BY path.depth ASC
`

type ListManagedBranchPathPageParams struct {
	TargetConversationID pgtype.UUID `json:"target_conversation_id"`
	CursorSeq            int32       `json:"cursor_seq"`
	PageSize             int32       `json:"page_size"`
}

type ListManagedBranchPathPageRow struct {
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Seq                int32              `json:"seq"`
	Role               string             `json:"role"`
	Content            pgtype.Text        `json:"content"`
	ContentSidecarPath pgtype.Text        `json:"content_sidecar_path"`
	ToolCallID         pgtype.Text        `json:"tool_call_id"`
	ToolCalls          []byte             `json:"tool_calls"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	InputTokens        int32              `json:"input_tokens"`
	OutputTokens       int32              `json:"output_tokens"`
	CachedTokens       int32              `json:"cached_tokens"`
	ParentSeq          pgtype.Int4        `json:"parent_seq"`
	Depth              int32              `json:"depth"`
}

// One bounded leaf->root page. Go resumes from the last row's parent_seq, checks strict
// monotonicity/cycles, and stops only at the exact durable watermark or NULL root.
func (q *Queries) ListManagedBranchPathPage(ctx context.Context, arg ListManagedBranchPathPageParams) ([]ListManagedBranchPathPageRow, error) {
	rows, err := q.db.Query(ctx, listManagedBranchPathPage, arg.TargetConversationID, arg.CursorSeq, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManagedBranchPathPageRow{}
	for rows.Next() {
		var i ListManagedBranchPathPageRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.ContentSidecarPath,
			&i.ToolCallID,
			&i.ToolCalls,
			&i.CreatedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
			&i.ParentSeq,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedHistoryHead = `-- name: ListManagedHistoryHead :many
SELECT conversation_id, seq, role, content, content_sidecar_path,
       tool_call_id, tool_calls, created_at, input_tokens, output_tokens, cached_tokens
FROM aura.conversation_turns
WHERE conversation_id = $1 AND role = 'system'
ORDER BY seq ASC
LIMIT 1
`

type ListManagedHistoryHeadRow struct {
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Seq                int32              `json:"seq"`
	Role               string             `json:"role"`
	Content            pgtype.Text        `json:"content"`
	ContentSidecarPath pgtype.Text        `json:"content_sidecar_path"`
	ToolCallID         pgtype.Text        `json:"tool_call_id"`
	ToolCalls          []byte             `json:"tool_calls"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	InputTokens        int32              `json:"input_tokens"`
	OutputTokens       int32              `json:"output_tokens"`
	CachedTokens       int32              `json:"cached_tokens"`
}

// The protected system root is fetched once, independently of body pagination. :many
// deliberately represents an empty conversation without pgx.ErrNoRows.
func (q *Queries) ListManagedHistoryHead(ctx context.Context, conversationID pgtype.UUID) ([]ListManagedHistoryHeadRow, error) {
	rows, err := q.db.Query(ctx, listManagedHistoryHead, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManagedHistoryHeadRow{}
	for rows.Next() {
		var i ListManagedHistoryHeadRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.ContentSidecarPath,
			&i.ToolCallID,
			&i.ToolCalls,
			&i.CreatedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedTurnsPageBySeq = `-- name: ListManagedTurnsPageBySeq :many
SELECT conversation_id, seq, role, content, content_sidecar_path,
       tool_call_id, tool_calls, created_at, input_tokens, output_tokens, cached_tokens
FROM aura.conversation_turns
WHERE conversation_id = $1
  AND role <> 'system'
  AND seq <= $2
ORDER BY seq DESC
LIMIT $3
`

type ListManagedTurnsPageBySeqParams struct {
	TargetConversationID pgtype.UUID `json:"target_conversation_id"`
	CursorSeq            int32       `json:"cursor_seq"`
	PageSize             int32       `json:"page_size"`
}

type ListManagedTurnsPageBySeqRow struct {
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Seq                int32              `json:"seq"`
	Role               string             `json:"role"`
	Content            pgtype.Text        `json:"content"`
	ContentSidecarPath pgtype.Text        `json:"content_sidecar_path"`
	ToolCallID         pgtype.Text        `json:"tool_call_id"`
	ToolCalls          []byte             `json:"tool_calls"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	InputTokens        int32              `json:"input_tokens"`
	OutputTokens       int32              `json:"output_tokens"`
	CachedTokens       int32              `json:"cached_tokens"`
}

// AURA_HISTORY_HARD_CAP_TURNS is a keyset page size, never a recall boundary. The
// caller keeps paging until the exact durable watermark or the root is observed.
func (q *Queries) ListManagedTurnsPageBySeq(ctx context.Context, arg ListManagedTurnsPageBySeqParams) ([]ListManagedTurnsPageBySeqRow, error) {
	rows, err := q.db.Query(ctx, listManagedTurnsPageBySeq, arg.TargetConversationID, arg.CursorSeq, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManagedTurnsPageBySeqRow{}
	for rows.Next() {
		var i ListManagedTurnsPageBySeqRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.ContentSidecarPath,
			&i.ToolCallID,
			&i.ToolCalls,
			&i.CreatedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpilledSeqsForConversation = `-- name: ListSpilledSeqsForConversation :many
SELECT seq
FROM aura.conversation_turns
WHERE conversation_id = $1
  AND content_sidecar_path IS NOT NULL
`

// D-09 (LOOP-09): every seq whose content spilled to a <seq>.content sidecar
// (content_sidecar_path IS NOT NULL) in one conversation. The crash-orphan GC
// (orphan_scan.go) reconciles the live .content files against this referenced
// set, so no ORDER BY is needed. Read-only — no schema change (D-07 holds).
func (q *Queries) ListSpilledSeqsForConversation(ctx context.Context, conversationID pgtype.UUID) ([]int32, error) {
	rows, err := q.db.Query(ctx, listSpilledSeqsForConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var seq int32
		if err := rows.Scan(&seq); err != nil {
			return nil, err
		}
		items = append(items, seq)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurnsByBranchPath = `-- name: ListTurnsByBranchPath :many
WITH RECURSIVE path AS (
    SELECT ct.conversation_id, ct.seq, ct.role, ct.content, ct.content_sidecar_path,
           ct.tool_call_id, ct.tool_calls, ct.created_at, ct.input_tokens, ct.output_tokens,
           ct.cached_tokens, ct.branch_id, ct.parent_seq
    FROM aura.conversation_turns ct
    WHERE ct.conversation_id = $1 AND ct.seq = $2
    UNION ALL
    SELECT t.conversation_id, t.seq, t.role, t.content, t.content_sidecar_path,
           t.tool_call_id, t.tool_calls, t.created_at, t.input_tokens, t.output_tokens,
           t.cached_tokens, t.branch_id, t.parent_seq
    FROM aura.conversation_turns t
    JOIN path p
      ON t.conversation_id = p.conversation_id
     AND t.seq = p.parent_seq
)
SELECT path.conversation_id, path.seq, path.role, path.content, path.content_sidecar_path,
       path.tool_call_id, path.tool_calls, path.created_at, path.input_tokens,
       path.output_tokens, path.cached_tokens
FROM path
ORDER BY path.seq ASC
`

type ListTurnsByBranchPathParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Seq            int32       `json:"seq"`
}

type ListTurnsByBranchPathRow struct {
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Seq                int32              `json:"seq"`
	Role               string             `json:"role"`
	Content            pgtype.Text        `json:"content"`
	ContentSidecarPath pgtype.Text        `json:"content_sidecar_path"`
	ToolCallID         pgtype.Text        `json:"tool_call_id"`
	ToolCalls          []byte             `json:"tool_calls"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	InputTokens        int32              `json:"input_tokens"`
	OutputTokens       int32              `json:"output_tokens"`
	CachedTokens       int32              `json:"cached_tokens"`
}

// D-09 (CHAT-05): the deterministic leaf->root path walk. Given a selected leaf seq,
// follow parent_seq up to the root, then return the turns in root->leaf (seq ASC) order
// so the head (system seq=1 + the always-block) is byte-identical to the linear case —
// only the body turns differ per branch (Pitfall 3 rule 1). The column list MIRRORS
// ListTurnsBySeq exactly so turnFromRow rehydrates it unchanged. A leaf seq of 0 (or one
// not present) yields an empty path. Walk terminates at parent_seq IS NULL (the root).
func (q *Queries) ListTurnsByBranchPath(ctx context.Context, arg ListTurnsByBranchPathParams) ([]ListTurnsByBranchPathRow, error) {
	rows, err := q.db.Query(ctx, listTurnsByBranchPath, arg.ConversationID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTurnsByBranchPathRow{}
	for rows.Next() {
		var i ListTurnsByBranchPathRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.ContentSidecarPath,
			&i.ToolCallID,
			&i.ToolCalls,
			&i.CreatedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurnsBySeq = `-- name: ListTurnsBySeq :many
SELECT conversation_id, seq, role, content, content_sidecar_path,
       tool_call_id, tool_calls, created_at, input_tokens, output_tokens, cached_tokens
FROM aura.conversation_turns
WHERE conversation_id = $1
ORDER BY seq ASC
`

type ListTurnsBySeqRow struct {
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Seq                int32              `json:"seq"`
	Role               string             `json:"role"`
	Content            pgtype.Text        `json:"content"`
	ContentSidecarPath pgtype.Text        `json:"content_sidecar_path"`
	ToolCallID         pgtype.Text        `json:"tool_call_id"`
	ToolCalls          []byte             `json:"tool_calls"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	InputTokens        int32              `json:"input_tokens"`
	OutputTokens       int32              `json:"output_tokens"`
	CachedTokens       int32              `json:"cached_tokens"`
}

func (q *Queries) ListTurnsBySeq(ctx context.Context, conversationID pgtype.UUID) ([]ListTurnsBySeqRow, error) {
	rows, err := q.db.Query(ctx, listTurnsBySeq, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTurnsBySeqRow{}
	for rows.Next() {
		var i ListTurnsBySeqRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.ContentSidecarPath,
			&i.ToolCallID,
			&i.ToolCalls,
			&i.CreatedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTurnAttachments = `-- name: ListUserTurnAttachments :many
SELECT seq, attachment_ids, ordinal
FROM (
    SELECT seq,
           attachment_ids,
           (row_number() OVER (ORDER BY seq ASC) - 1)::int AS ordinal
    FROM aura.conversation_turns
    WHERE conversation_id = $1
      AND role = 'user'
) AS user_turns
WHERE attachment_ids IS NOT NULL
  AND cardinality(attachment_ids) > 0
ORDER BY seq ASC
`

type ListUserTurnAttachmentsRow struct {
	Seq           int32         `json:"seq"`
	AttachmentIds []pgtype.UUID `json:"attachment_ids"`
	Ordinal       int32         `json:"ordinal"`
}

// Display-only read, deliberately separate from ListTurnsBySeq for the same reason
// ListAssistantTurnReasoning is: the llm.Message history rebuild must never select it.
//
// `ordinal` is the turn's index AMONG USER TURNS, not its seq, because that is what the
// snapshot consumer can actually match on: the messages it merges into carry no seq, and
// user turns rebuild one-for-one and in order (repairToolMessagePairs touches only
// tool/assistant pairing). Computing it here rather than returning every user turn keeps
// the result sparse -- a long conversation with one attachment costs one row.
func (q *Queries) ListUserTurnAttachments(ctx context.Context, conversationID pgtype.UUID) ([]ListUserTurnAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listUserTurnAttachments, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTurnAttachmentsRow{}
	for rows.Next() {
		var i ListUserTurnAttachmentsRow
		if err := rows.Scan(&i.Seq, &i.AttachmentIds, &i.Ordinal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConversationForTurnAppend = `-- name: LockConversationForTurnAppend :one
SELECT id
FROM aura.conversations
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockConversationForTurnAppend(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockConversationForTurnAppend, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const nextConversationTurnSeq = `-- name: NextConversationTurnSeq :one
SELECT (COALESCE(MAX(seq), 0) + 1)::int AS seq
FROM aura.conversation_turns
WHERE conversation_id = $1
`

func (q *Queries) NextConversationTurnSeq(ctx context.Context, conversationID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextConversationTurnSeq, conversationID)
	var seq int32
	err := row.Scan(&seq)
	return seq, err
}

const searchConversationTurns = `-- name: SearchConversationTurns :many
SELECT conversation_id, seq, content, similarity(content, $1) AS sim
FROM aura.conversation_turns
WHERE content % $1
ORDER BY similarity(content, $1) DESC
LIMIT $2
`

type SearchConversationTurnsParams struct {
	Similarity string `json:"similarity"`
	Limit      int32  `json:"limit"`
}

type SearchConversationTurnsRow struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Seq            int32       `json:"seq"`
	Content        pgtype.Text `json:"content"`
	Sim            float32     `json:"sim"`
}

// LOCKED cross-slice contract (D-A5-03 / SPEC Req#13). Telegram /search (Phase 13)
// reuses this EXACT query; only the excerpt rendering differs per channel.
func (q *Queries) SearchConversationTurns(ctx context.Context, arg SearchConversationTurnsParams) ([]SearchConversationTurnsRow, error) {
	rows, err := q.db.Query(ctx, searchConversationTurns, arg.Similarity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchConversationTurnsRow{}
	for rows.Next() {
		var i SearchConversationTurnsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.Seq,
			&i.Content,
			&i.Sim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTurnBranchPointers = `-- name: SetTurnBranchPointers :exec
UPDATE aura.conversation_turns
SET branch_id = $3, parent_seq = $4
WHERE conversation_id = $1 AND seq = $2
`

type SetTurnBranchPointersParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Seq            int32       `json:"seq"`
	BranchID       pgtype.UUID `json:"branch_id"`
	ParentSeq      pgtype.Int4 `json:"parent_seq"`
}

// D-09 (CHAT-05): set a turn's branch/parent pointers. The branch-write seam plan 25-07
// uses when an edit/regenerate forks a new sibling branch off an existing parent turn.
func (q *Queries) SetTurnBranchPointers(ctx context.Context, arg SetTurnBranchPointersParams) error {
	_, err := q.db.Exec(ctx, setTurnBranchPointers,
		arg.ConversationID,
		arg.Seq,
		arg.BranchID,
		arg.ParentSeq,
	)
	return err
}

const upsertConversationCompaction = `-- name: UpsertConversationCompaction :one
INSERT INTO aura.conversation_compactions (
    conversation_id, branch_id, covers_through_seq, summary, model, source_turns
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (conversation_id, branch_id) DO UPDATE
   SET covers_through_seq = EXCLUDED.covers_through_seq,
       summary            = EXCLUDED.summary,
       model              = EXCLUDED.model,
       source_turns       = EXCLUDED.source_turns,
       updated_at         = now()
   WHERE conversation_compactions.covers_through_seq < EXCLUDED.covers_through_seq
RETURNING conversation_id, branch_id, covers_through_seq, summary, model, source_turns,
          created_at, updated_at
`

type UpsertConversationCompactionParams struct {
	ConversationID   pgtype.UUID `json:"conversation_id"`
	BranchID         pgtype.UUID `json:"branch_id"`
	CoversThroughSeq int32       `json:"covers_through_seq"`
	Summary          string      `json:"summary"`
	Model            string      `json:"model"`
	SourceTurns      int32       `json:"source_turns"`
}

// Writes the branch's summary, advancing the watermark.
//
// The WHERE on the DO UPDATE is the whole invariant: a watermark may only move FORWARD.
// Two turns can compact concurrently (two requests on one conversation), and the loser
// must not replace a summary covering seq 120 with one covering seq 80 -- that would
// silently drop forty turns out of the model's view while leaving the ladder believing
// they were summarized. Zero rows back means "someone else already went further", which
// the caller treats as success and re-reads.
func (q *Queries) UpsertConversationCompaction(ctx context.Context, arg UpsertConversationCompactionParams) (AuraConversationCompactions, error) {
	row := q.db.QueryRow(ctx, upsertConversationCompaction,
		arg.ConversationID,
		arg.BranchID,
		arg.CoversThroughSeq,
		arg.Summary,
		arg.Model,
		arg.SourceTurns,
	)
	var i AuraConversationCompactions
	err := row.Scan(
		&i.ConversationID,
		&i.BranchID,
		&i.CoversThroughSeq,
		&i.Summary,
		&i.Model,
		&i.SourceTurns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
