// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_turns.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTurns = `-- name: CountTurns :one
SELECT count(*) AS turn_count
FROM aura.conversation_turns
WHERE conversation_id = $1
`

func (q *Queries) CountTurns(ctx context.Context, conversationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTurns, conversationID)
	var turn_count int64
	err := row.Scan(&turn_count)
	return turn_count, err
}

const insertConversationTurn = `-- name: InsertConversationTurn :exec
INSERT INTO aura.conversation_turns (
    conversation_id, seq, role, content, content_sidecar_path,
    tool_call_id, tool_calls, input_tokens, output_tokens, cached_tokens
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertConversationTurnParams struct {
	ConversationID     pgtype.UUID `json:"conversation_id"`
	Seq                int32       `json:"seq"`
	Role               string      `json:"role"`
	Content            pgtype.Text `json:"content"`
	ContentSidecarPath pgtype.Text `json:"content_sidecar_path"`
	ToolCallID         pgtype.Text `json:"tool_call_id"`
	ToolCalls          []byte      `json:"tool_calls"`
	InputTokens        int32       `json:"input_tokens"`
	OutputTokens       int32       `json:"output_tokens"`
	CachedTokens       int32       `json:"cached_tokens"`
}

func (q *Queries) InsertConversationTurn(ctx context.Context, arg InsertConversationTurnParams) error {
	_, err := q.db.Exec(ctx, insertConversationTurn,
		arg.ConversationID,
		arg.Seq,
		arg.Role,
		arg.Content,
		arg.ContentSidecarPath,
		arg.ToolCallID,
		arg.ToolCalls,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
	)
	return err
}

const listTurnsBySeq = `-- name: ListTurnsBySeq :many
SELECT conversation_id, seq, role, content, content_sidecar_path,
       tool_call_id, tool_calls, created_at, input_tokens, output_tokens, cached_tokens
FROM aura.conversation_turns
WHERE conversation_id = $1
ORDER BY seq ASC
`

func (q *Queries) ListTurnsBySeq(ctx context.Context, conversationID pgtype.UUID) ([]AuraConversationTurns, error) {
	rows, err := q.db.Query(ctx, listTurnsBySeq, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraConversationTurns{}
	for rows.Next() {
		var i AuraConversationTurns
		if err := rows.Scan(
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.ContentSidecarPath,
			&i.ToolCallID,
			&i.ToolCalls,
			&i.CreatedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CachedTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchConversationTurns = `-- name: SearchConversationTurns :many
SELECT conversation_id, seq, content, similarity(content, $1) AS sim
FROM aura.conversation_turns
WHERE content % $1
ORDER BY similarity(content, $1) DESC
LIMIT $2
`

type SearchConversationTurnsParams struct {
	Similarity string `json:"similarity"`
	Limit      int32  `json:"limit"`
}

type SearchConversationTurnsRow struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Seq            int32       `json:"seq"`
	Content        pgtype.Text `json:"content"`
	Sim            float32     `json:"sim"`
}

// LOCKED cross-slice contract (D-A5-03 / SPEC Req#13). Telegram /search (Phase 13)
// reuses this EXACT query; only the excerpt rendering differs per channel.
func (q *Queries) SearchConversationTurns(ctx context.Context, arg SearchConversationTurnsParams) ([]SearchConversationTurnsRow, error) {
	rows, err := q.db.Query(ctx, searchConversationTurns, arg.Similarity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchConversationTurnsRow{}
	for rows.Next() {
		var i SearchConversationTurnsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.Seq,
			&i.Content,
			&i.Sim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
