// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO aura.conversations (id, identity_id, model, status, metadata)
VALUES ($1, $2, $3, 'active', $4)
RETURNING id, title, identity_id, created_at, last_active_at, status, model,
          total_input_tokens, total_output_tokens, total_cached_tokens,
          total_cost_usd, metadata
`

type CreateConversationParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
	Model      string      `json:"model"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (AuraConversations, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.IdentityID,
		arg.Model,
		arg.Metadata,
	)
	var i AuraConversations
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.IdentityID,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.Status,
		&i.Model,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
		&i.TotalCachedTokens,
		&i.TotalCostUsd,
		&i.Metadata,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM aura.conversations
WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, title, identity_id, created_at, last_active_at, status, model,
       total_input_tokens, total_output_tokens, total_cached_tokens,
       total_cost_usd, metadata
FROM aura.conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id pgtype.UUID) (AuraConversations, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i AuraConversations
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.IdentityID,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.Status,
		&i.Model,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
		&i.TotalCachedTokens,
		&i.TotalCostUsd,
		&i.Metadata,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, title, identity_id, created_at, last_active_at, status, model,
       total_input_tokens, total_output_tokens, total_cached_tokens,
       total_cost_usd, metadata
FROM aura.conversations
WHERE status <> 'deleted'
  AND ($1::boolean OR status = 'active')
ORDER BY last_active_at DESC
`

func (q *Queries) ListConversations(ctx context.Context, includeArchived bool) ([]AuraConversations, error) {
	rows, err := q.db.Query(ctx, listConversations, includeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraConversations{}
	for rows.Next() {
		var i AuraConversations
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.IdentityID,
			&i.CreatedAt,
			&i.LastActiveAt,
			&i.Status,
			&i.Model,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.TotalCachedTokens,
			&i.TotalCostUsd,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameConversation = `-- name: RenameConversation :exec
UPDATE aura.conversations
SET title = $2
WHERE id = $1
`

type RenameConversationParams struct {
	ID    pgtype.UUID `json:"id"`
	Title pgtype.Text `json:"title"`
}

func (q *Queries) RenameConversation(ctx context.Context, arg RenameConversationParams) error {
	_, err := q.db.Exec(ctx, renameConversation, arg.ID, arg.Title)
	return err
}

const setConversationTitleIfNull = `-- name: SetConversationTitleIfNull :exec
UPDATE aura.conversations
SET title = $2
WHERE id = $1
  AND title IS NULL
`

type SetConversationTitleIfNullParams struct {
	ID    pgtype.UUID `json:"id"`
	Title pgtype.Text `json:"title"`
}

func (q *Queries) SetConversationTitleIfNull(ctx context.Context, arg SetConversationTitleIfNullParams) error {
	_, err := q.db.Exec(ctx, setConversationTitleIfNull, arg.ID, arg.Title)
	return err
}

const updateConversationAggregates = `-- name: UpdateConversationAggregates :exec
UPDATE aura.conversations
SET last_active_at = now(),
    total_input_tokens = total_input_tokens + $1,
    total_output_tokens = total_output_tokens + $2,
    total_cached_tokens = total_cached_tokens + $3,
    total_cost_usd = total_cost_usd + $4
WHERE id = $5
`

type UpdateConversationAggregatesParams struct {
	InputTokens  int64          `json:"input_tokens"`
	OutputTokens int64          `json:"output_tokens"`
	CachedTokens int64          `json:"cached_tokens"`
	CostUsd      pgtype.Numeric `json:"cost_usd"`
	ID           pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateConversationAggregates(ctx context.Context, arg UpdateConversationAggregatesParams) error {
	_, err := q.db.Exec(ctx, updateConversationAggregates,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.CostUsd,
		arg.ID,
	)
	return err
}

const updateConversationStatus = `-- name: UpdateConversationStatus :exec
UPDATE aura.conversations
SET status = $2,
    last_active_at = now()
WHERE id = $1
`

type UpdateConversationStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateConversationStatus(ctx context.Context, arg UpdateConversationStatusParams) error {
	_, err := q.db.Exec(ctx, updateConversationStatus, arg.ID, arg.Status)
	return err
}
