// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delegation_delivery.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const stageDelegationDelivery = `-- name: StageDelegationDelivery :one
UPDATE aura.ingestion_jobs
SET payload = $1,
    updated_at = now()
WHERE id = $2
  AND identity_id = $3
  AND job_type = 'swarm_delegation'
  AND status = 'running'
  AND locked_by = $4
  AND lease_generation = $5
  AND locked_until > now()
RETURNING id, job_type, status, idempotency_key, stage, attempt_count, max_attempts, locked_by, locked_until, next_attempt_at, payload, error_code, error_message, created_at, updated_at, completed_at, identity_id, asset_id, pipeline_generation, attempt_generation, lease_generation
`

type StageDelegationDeliveryParams struct {
	Payload         []byte      `json:"payload"`
	ID              pgtype.UUID `json:"id"`
	IdentityID      pgtype.UUID `json:"identity_id"`
	LockedBy        pgtype.Text `json:"locked_by"`
	LeaseGeneration int64       `json:"lease_generation"`
}

func (q *Queries) StageDelegationDelivery(ctx context.Context, arg StageDelegationDeliveryParams) (AuraIngestionJobs, error) {
	row := q.db.QueryRow(ctx, stageDelegationDelivery,
		arg.Payload,
		arg.ID,
		arg.IdentityID,
		arg.LockedBy,
		arg.LeaseGeneration,
	)
	var i AuraIngestionJobs
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Status,
		&i.IdempotencyKey,
		&i.Stage,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedUntil,
		&i.NextAttemptAt,
		&i.Payload,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.IdentityID,
		&i.AssetID,
		&i.PipelineGeneration,
		&i.AttemptGeneration,
		&i.LeaseGeneration,
	)
	return i, err
}
