// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_ingest_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocumentIngestJob = `-- name: CreateDocumentIngestJob :one
INSERT INTO aura.document_ingest_jobs (
    source_id,
    source_kind,
    document_id,
    content_hash,
    original_path,
    file_name,
    mime_type,
    size_bytes,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (source_id, document_id, content_hash)
DO UPDATE SET
    original_path = EXCLUDED.original_path,
    file_name = EXCLUDED.file_name,
    mime_type = EXCLUDED.mime_type,
    size_bytes = EXCLUDED.size_bytes,
    updated_at = now()
RETURNING id, source_id, source_kind, document_id, content_hash, original_path, file_name, mime_type, size_bytes, status, sparse_chunks, embedded_chunks, error, created_at, updated_at, searchable_at, completed_at
`

type CreateDocumentIngestJobParams struct {
	SourceID     string `json:"source_id"`
	SourceKind   string `json:"source_kind"`
	DocumentID   string `json:"document_id"`
	ContentHash  string `json:"content_hash"`
	OriginalPath string `json:"original_path"`
	FileName     string `json:"file_name"`
	MimeType     string `json:"mime_type"`
	SizeBytes    int64  `json:"size_bytes"`
	Status       string `json:"status"`
}

func (q *Queries) CreateDocumentIngestJob(ctx context.Context, arg CreateDocumentIngestJobParams) (AuraDocumentIngestJobs, error) {
	row := q.db.QueryRow(ctx, createDocumentIngestJob,
		arg.SourceID,
		arg.SourceKind,
		arg.DocumentID,
		arg.ContentHash,
		arg.OriginalPath,
		arg.FileName,
		arg.MimeType,
		arg.SizeBytes,
		arg.Status,
	)
	var i AuraDocumentIngestJobs
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceKind,
		&i.DocumentID,
		&i.ContentHash,
		&i.OriginalPath,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Status,
		&i.SparseChunks,
		&i.EmbeddedChunks,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchableAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDocumentIngestJob = `-- name: GetDocumentIngestJob :one
SELECT id, source_id, source_kind, document_id, content_hash, original_path, file_name, mime_type, size_bytes, status, sparse_chunks, embedded_chunks, error, created_at, updated_at, searchable_at, completed_at
FROM aura.document_ingest_jobs
WHERE id = $1
`

func (q *Queries) GetDocumentIngestJob(ctx context.Context, id pgtype.UUID) (AuraDocumentIngestJobs, error) {
	row := q.db.QueryRow(ctx, getDocumentIngestJob, id)
	var i AuraDocumentIngestJobs
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceKind,
		&i.DocumentID,
		&i.ContentHash,
		&i.OriginalPath,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Status,
		&i.SparseChunks,
		&i.EmbeddedChunks,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchableAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDocumentIngestJobByDocumentID = `-- name: GetDocumentIngestJobByDocumentID :one
SELECT id, source_id, source_kind, document_id, content_hash, original_path, file_name, mime_type, size_bytes, status, sparse_chunks, embedded_chunks, error, created_at, updated_at, searchable_at, completed_at
FROM aura.document_ingest_jobs
WHERE document_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetDocumentIngestJobByDocumentID(ctx context.Context, documentID string) (AuraDocumentIngestJobs, error) {
	row := q.db.QueryRow(ctx, getDocumentIngestJobByDocumentID, documentID)
	var i AuraDocumentIngestJobs
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceKind,
		&i.DocumentID,
		&i.ContentHash,
		&i.OriginalPath,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Status,
		&i.SparseChunks,
		&i.EmbeddedChunks,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchableAt,
		&i.CompletedAt,
	)
	return i, err
}

const listRecentDocumentIngestJobs = `-- name: ListRecentDocumentIngestJobs :many
SELECT id, source_id, source_kind, document_id, content_hash, original_path, file_name, mime_type, size_bytes, status, sparse_chunks, embedded_chunks, error, created_at, updated_at, searchable_at, completed_at
FROM aura.document_ingest_jobs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListRecentDocumentIngestJobs(ctx context.Context, limit int32) ([]AuraDocumentIngestJobs, error) {
	rows, err := q.db.Query(ctx, listRecentDocumentIngestJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraDocumentIngestJobs{}
	for rows.Next() {
		var i AuraDocumentIngestJobs
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.SourceKind,
			&i.DocumentID,
			&i.ContentHash,
			&i.OriginalPath,
			&i.FileName,
			&i.MimeType,
			&i.SizeBytes,
			&i.Status,
			&i.SparseChunks,
			&i.EmbeddedChunks,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchableAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentIngestJobProgress = `-- name: UpdateDocumentIngestJobProgress :one
UPDATE aura.document_ingest_jobs
SET
    status = $2,
    sparse_chunks = $3,
    embedded_chunks = $4,
    updated_at = now(),
    searchable_at = CASE WHEN $2 = 'searchable' AND searchable_at IS NULL THEN now() ELSE searchable_at END,
    completed_at = CASE WHEN $2 = 'complete' AND completed_at IS NULL THEN now() ELSE completed_at END
WHERE id = $1
RETURNING id, source_id, source_kind, document_id, content_hash, original_path, file_name, mime_type, size_bytes, status, sparse_chunks, embedded_chunks, error, created_at, updated_at, searchable_at, completed_at
`

type UpdateDocumentIngestJobProgressParams struct {
	ID             pgtype.UUID `json:"id"`
	Status         string      `json:"status"`
	SparseChunks   int32       `json:"sparse_chunks"`
	EmbeddedChunks int32       `json:"embedded_chunks"`
}

func (q *Queries) UpdateDocumentIngestJobProgress(ctx context.Context, arg UpdateDocumentIngestJobProgressParams) (AuraDocumentIngestJobs, error) {
	row := q.db.QueryRow(ctx, updateDocumentIngestJobProgress,
		arg.ID,
		arg.Status,
		arg.SparseChunks,
		arg.EmbeddedChunks,
	)
	var i AuraDocumentIngestJobs
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceKind,
		&i.DocumentID,
		&i.ContentHash,
		&i.OriginalPath,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Status,
		&i.SparseChunks,
		&i.EmbeddedChunks,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchableAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateDocumentIngestJobStatus = `-- name: UpdateDocumentIngestJobStatus :one
UPDATE aura.document_ingest_jobs
SET
    status = $2,
    error = $3,
    updated_at = now(),
    searchable_at = CASE WHEN $2 = 'searchable' THEN now() ELSE searchable_at END,
    completed_at = CASE WHEN $2 = 'complete' THEN now() ELSE completed_at END
WHERE id = $1
RETURNING id, source_id, source_kind, document_id, content_hash, original_path, file_name, mime_type, size_bytes, status, sparse_chunks, embedded_chunks, error, created_at, updated_at, searchable_at, completed_at
`

type UpdateDocumentIngestJobStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
	Error  pgtype.Text `json:"error"`
}

func (q *Queries) UpdateDocumentIngestJobStatus(ctx context.Context, arg UpdateDocumentIngestJobStatusParams) (AuraDocumentIngestJobs, error) {
	row := q.db.QueryRow(ctx, updateDocumentIngestJobStatus, arg.ID, arg.Status, arg.Error)
	var i AuraDocumentIngestJobs
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceKind,
		&i.DocumentID,
		&i.ContentHash,
		&i.OriginalPath,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Status,
		&i.SparseChunks,
		&i.EmbeddedChunks,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchableAt,
		&i.CompletedAt,
	)
	return i, err
}
