// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_control_plane.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimIngestionJobs = `-- name: ClaimIngestionJobs :many
WITH candidates AS (
    SELECT queued_job.id, queued_job.status AS prior_status
    FROM aura.ingestion_jobs queued_job
    WHERE queued_job.identity_id = $1
      AND queued_job.attempt_count < queued_job.max_attempts
      AND (
        (queued_job.status = 'queued' AND queued_job.next_attempt_at <= now()
         AND (queued_job.locked_until IS NULL OR queued_job.locked_until < now()))
        OR (queued_job.status = 'running' AND queued_job.locked_until < now())
      )
    ORDER BY queued_job.next_attempt_at, queued_job.created_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
), claimed AS (
    UPDATE aura.ingestion_jobs job
    SET status = 'running',
        locked_by = $3,
        locked_until = now() + $4::interval,
        attempt_count = attempt_count + 1,
        lease_generation = lease_generation + 1,
        completed_at = NULL,
        updated_at = now()
    FROM candidates candidate
    WHERE job.id = candidate.id
    RETURNING job.id, job.job_type, job.document_id, job.version_id, job.status, job.idempotency_key, job.stage, job.attempt_count, job.max_attempts, job.locked_by, job.locked_until, job.next_attempt_at, job.payload, job.error_code, job.error_message, job.created_at, job.updated_at, job.completed_at, job.identity_id, job.asset_id, job.pipeline_generation, job.attempt_generation, job.lease_generation, candidate.prior_status
), events AS (
    INSERT INTO aura.ingestion_events (
        identity_id, entity_type, entity_id, job_id, from_status, to_status,
        event_type, detail, pipeline_generation, attempt_generation, lease_generation
    )
    SELECT claimed.identity_id, 'ingestion_job', claimed.id, claimed.id,
           claimed.prior_status, 'running',
           CASE WHEN claimed.prior_status = 'running' THEN 'job_lease_reclaimed'
                ELSE 'job_claimed' END,
           '{}'::jsonb, claimed.pipeline_generation, claimed.attempt_generation,
           claimed.lease_generation
    FROM claimed
    RETURNING job_id
)
SELECT claimed.id, claimed.job_type, claimed.document_id, claimed.version_id, claimed.status, claimed.idempotency_key, claimed.stage, claimed.attempt_count, claimed.max_attempts, claimed.locked_by, claimed.locked_until, claimed.next_attempt_at, claimed.payload, claimed.error_code, claimed.error_message, claimed.created_at, claimed.updated_at, claimed.completed_at, claimed.identity_id, claimed.asset_id, claimed.pipeline_generation, claimed.attempt_generation, claimed.lease_generation FROM claimed
JOIN events ON events.job_id = claimed.id
ORDER BY claimed.next_attempt_at, claimed.created_at
`

type ClaimIngestionJobsParams struct {
	IdentityID    pgtype.UUID     `json:"identity_id"`
	BatchSize     int32           `json:"batch_size"`
	LockedBy      pgtype.Text     `json:"locked_by"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

type ClaimIngestionJobsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	JobType            string             `json:"job_type"`
	DocumentID         pgtype.UUID        `json:"document_id"`
	VersionID          pgtype.UUID        `json:"version_id"`
	Status             string             `json:"status"`
	IdempotencyKey     string             `json:"idempotency_key"`
	Stage              string             `json:"stage"`
	AttemptCount       int32              `json:"attempt_count"`
	MaxAttempts        int32              `json:"max_attempts"`
	LockedBy           pgtype.Text        `json:"locked_by"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	NextAttemptAt      pgtype.Timestamptz `json:"next_attempt_at"`
	Payload            []byte             `json:"payload"`
	ErrorCode          string             `json:"error_code"`
	ErrorMessage       string             `json:"error_message"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	IdentityID         pgtype.UUID        `json:"identity_id"`
	AssetID            pgtype.UUID        `json:"asset_id"`
	PipelineGeneration int64              `json:"pipeline_generation"`
	AttemptGeneration  int64              `json:"attempt_generation"`
	LeaseGeneration    int64              `json:"lease_generation"`
}

func (q *Queries) ClaimIngestionJobs(ctx context.Context, arg ClaimIngestionJobsParams) ([]ClaimIngestionJobsRow, error) {
	rows, err := q.db.Query(ctx, claimIngestionJobs,
		arg.IdentityID,
		arg.BatchSize,
		arg.LockedBy,
		arg.LeaseDuration,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimIngestionJobsRow{}
	for rows.Next() {
		var i ClaimIngestionJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobType,
			&i.DocumentID,
			&i.VersionID,
			&i.Status,
			&i.IdempotencyKey,
			&i.Stage,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.LockedBy,
			&i.LockedUntil,
			&i.NextAttemptAt,
			&i.Payload,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.IdentityID,
			&i.AssetID,
			&i.PipelineGeneration,
			&i.AttemptGeneration,
			&i.LeaseGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countIngestionJobsByStatus = `-- name: CountIngestionJobsByStatus :one
SELECT count(*) FROM aura.ingestion_jobs
WHERE identity_id = $1 AND status = $2
`

type CountIngestionJobsByStatusParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Status     string      `json:"status"`
}

func (q *Queries) CountIngestionJobsByStatus(ctx context.Context, arg CountIngestionJobsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIngestionJobsByStatus, arg.IdentityID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO aura.documents (
    identity_id, scope, title, tags, metadata, status,
    source_kind, source_key, search_document_id, pipeline_generation
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
ON CONFLICT (identity_id, source_kind, source_key) WHERE deleted_at IS NULL
DO UPDATE SET updated_at = now()
    WHERE documents.status <> 'deleting'
RETURNING id, identity_id, scope, title, tags, metadata, active_version_id, status, created_at, updated_at, deleted_at, digest, card, digest_tsv, source_kind, source_key, search_document_id, pipeline_generation, error_code, error_message
`

type CreateDocumentParams struct {
	IdentityID         pgtype.UUID `json:"identity_id"`
	Scope              string      `json:"scope"`
	Title              string      `json:"title"`
	Tags               []string    `json:"tags"`
	Metadata           []byte      `json:"metadata"`
	Status             string      `json:"status"`
	SourceKind         string      `json:"source_kind"`
	SourceKey          string      `json:"source_key"`
	SearchDocumentID   string      `json:"search_document_id"`
	PipelineGeneration int64       `json:"pipeline_generation"`
}

// Get-or-create by source, refusing a document left mid-delete.
// DO UPDATE rather than DO NOTHING because :one needs a row back, and it touches ONLY
// updated_at: re-ingesting a file must not overwrite a title or tags the operator edited,
// and aura.document_identity_immutable raises 23514 on any write to identity, source,
// search id, or a lowered pipeline_generation. The status guard outlives the asynchronous
// delete workflow it was written for: no statement here sets 'deleting' any more, but rows
// the retired workflow stranded in that state are still on disk, and joining one would
// hand the caller a document whose bytes are half gone. Zero rows is that case, and the
// caller turns it into ErrDocumentDeleteInFlight.
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (AuraDocuments, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.IdentityID,
		arg.Scope,
		arg.Title,
		arg.Tags,
		arg.Metadata,
		arg.Status,
		arg.SourceKind,
		arg.SourceKey,
		arg.SearchDocumentID,
		arg.PipelineGeneration,
	)
	var i AuraDocuments
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Scope,
		&i.Title,
		&i.Tags,
		&i.Metadata,
		&i.ActiveVersionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Digest,
		&i.Card,
		&i.DigestTsv,
		&i.SourceKind,
		&i.SourceKey,
		&i.SearchDocumentID,
		&i.PipelineGeneration,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const createIngestionJob = `-- name: CreateIngestionJob :one
INSERT INTO aura.ingestion_jobs (
    identity_id, job_type, asset_id, document_id, version_id, status,
    idempotency_key, stage, max_attempts, next_attempt_at, payload,
    pipeline_generation
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12
)
ON CONFLICT (identity_id, job_type, idempotency_key) DO UPDATE
SET updated_at = now()
RETURNING id, job_type, document_id, version_id, status, idempotency_key, stage, attempt_count, max_attempts, locked_by, locked_until, next_attempt_at, payload, error_code, error_message, created_at, updated_at, completed_at, identity_id, asset_id, pipeline_generation, attempt_generation, lease_generation
`

type CreateIngestionJobParams struct {
	IdentityID         pgtype.UUID        `json:"identity_id"`
	JobType            string             `json:"job_type"`
	AssetID            pgtype.UUID        `json:"asset_id"`
	DocumentID         pgtype.UUID        `json:"document_id"`
	VersionID          pgtype.UUID        `json:"version_id"`
	Status             string             `json:"status"`
	IdempotencyKey     string             `json:"idempotency_key"`
	Stage              string             `json:"stage"`
	MaxAttempts        int32              `json:"max_attempts"`
	NextAttemptAt      pgtype.Timestamptz `json:"next_attempt_at"`
	Payload            []byte             `json:"payload"`
	PipelineGeneration int64              `json:"pipeline_generation"`
}

func (q *Queries) CreateIngestionJob(ctx context.Context, arg CreateIngestionJobParams) (AuraIngestionJobs, error) {
	row := q.db.QueryRow(ctx, createIngestionJob,
		arg.IdentityID,
		arg.JobType,
		arg.AssetID,
		arg.DocumentID,
		arg.VersionID,
		arg.Status,
		arg.IdempotencyKey,
		arg.Stage,
		arg.MaxAttempts,
		arg.NextAttemptAt,
		arg.Payload,
		arg.PipelineGeneration,
	)
	var i AuraIngestionJobs
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.DocumentID,
		&i.VersionID,
		&i.Status,
		&i.IdempotencyKey,
		&i.Stage,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedUntil,
		&i.NextAttemptAt,
		&i.Payload,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.IdentityID,
		&i.AssetID,
		&i.PipelineGeneration,
		&i.AttemptGeneration,
		&i.LeaseGeneration,
	)
	return i, err
}

const deleteDocumentTags = `-- name: DeleteDocumentTags :exec
DELETE FROM aura.document_tags WHERE document_id = $1
`

func (q *Queries) DeleteDocumentTags(ctx context.Context, documentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentTags, documentID)
	return err
}

const getDocumentBySearchID = `-- name: GetDocumentBySearchID :one
SELECT id, identity_id, scope, title, tags, metadata, active_version_id, status, created_at, updated_at, deleted_at, digest, card, digest_tsv, source_kind, source_key, search_document_id, pipeline_generation, error_code, error_message FROM aura.documents
WHERE identity_id = $1
  AND search_document_id = $2
  AND deleted_at IS NULL
`

type GetDocumentBySearchIDParams struct {
	IdentityID       pgtype.UUID `json:"identity_id"`
	SearchDocumentID string      `json:"search_document_id"`
}

func (q *Queries) GetDocumentBySearchID(ctx context.Context, arg GetDocumentBySearchIDParams) (AuraDocuments, error) {
	row := q.db.QueryRow(ctx, getDocumentBySearchID, arg.IdentityID, arg.SearchDocumentID)
	var i AuraDocuments
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Scope,
		&i.Title,
		&i.Tags,
		&i.Metadata,
		&i.ActiveVersionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Digest,
		&i.Card,
		&i.DigestTsv,
		&i.SourceKind,
		&i.SourceKey,
		&i.SearchDocumentID,
		&i.PipelineGeneration,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const heartbeatIngestionJob = `-- name: HeartbeatIngestionJob :one
UPDATE aura.ingestion_jobs
SET locked_until = now() + $1::interval,
    updated_at = now()
WHERE id = $2
  AND identity_id = $3
  AND status = 'running'
  AND locked_by = $4
  AND lease_generation = $5
  AND locked_until > now()
RETURNING id, job_type, document_id, version_id, status, idempotency_key, stage, attempt_count, max_attempts, locked_by, locked_until, next_attempt_at, payload, error_code, error_message, created_at, updated_at, completed_at, identity_id, asset_id, pipeline_generation, attempt_generation, lease_generation
`

type HeartbeatIngestionJobParams struct {
	LeaseDuration   pgtype.Interval `json:"lease_duration"`
	ID              pgtype.UUID     `json:"id"`
	IdentityID      pgtype.UUID     `json:"identity_id"`
	LockedBy        pgtype.Text     `json:"locked_by"`
	LeaseGeneration int64           `json:"lease_generation"`
}

func (q *Queries) HeartbeatIngestionJob(ctx context.Context, arg HeartbeatIngestionJobParams) (AuraIngestionJobs, error) {
	row := q.db.QueryRow(ctx, heartbeatIngestionJob,
		arg.LeaseDuration,
		arg.ID,
		arg.IdentityID,
		arg.LockedBy,
		arg.LeaseGeneration,
	)
	var i AuraIngestionJobs
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.DocumentID,
		&i.VersionID,
		&i.Status,
		&i.IdempotencyKey,
		&i.Stage,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedUntil,
		&i.NextAttemptAt,
		&i.Payload,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.IdentityID,
		&i.AssetID,
		&i.PipelineGeneration,
		&i.AttemptGeneration,
		&i.LeaseGeneration,
	)
	return i, err
}

const retryIngestionJob = `-- name: RetryIngestionJob :one
WITH target AS (
    SELECT target_job.id, target_job.status AS prior_status FROM aura.ingestion_jobs target_job
    WHERE target_job.id = $1 AND target_job.identity_id = $2
      AND target_job.status = 'running' AND target_job.locked_by = $3
      AND target_job.lease_generation = $4
    FOR UPDATE
), retried AS (
    UPDATE aura.ingestion_jobs job
    SET status = 'queued', stage = $5,
        error_code = $6, error_message = $7,
        locked_by = NULL, locked_until = NULL,
        next_attempt_at = $8, updated_at = now()
    FROM target WHERE job.id = target.id
    RETURNING job.id, job.job_type, job.document_id, job.version_id, job.status, job.idempotency_key, job.stage, job.attempt_count, job.max_attempts, job.locked_by, job.locked_until, job.next_attempt_at, job.payload, job.error_code, job.error_message, job.created_at, job.updated_at, job.completed_at, job.identity_id, job.asset_id, job.pipeline_generation, job.attempt_generation, job.lease_generation, target.prior_status
), events AS (
    INSERT INTO aura.ingestion_events (
        identity_id, entity_type, entity_id, job_id, from_status, to_status,
        event_type, message, pipeline_generation, attempt_generation, lease_generation
    )
    SELECT retried.identity_id, 'ingestion_job', retried.id, retried.id,
           retried.prior_status, 'queued', 'job_retry_scheduled',
           $9, retried.pipeline_generation,
           retried.attempt_generation, retried.lease_generation
    FROM retried
    RETURNING job_id
)
SELECT retried.id, retried.job_type, retried.document_id, retried.version_id, retried.status, retried.idempotency_key, retried.stage, retried.attempt_count, retried.max_attempts, retried.locked_by, retried.locked_until, retried.next_attempt_at, retried.payload, retried.error_code, retried.error_message, retried.created_at, retried.updated_at, retried.completed_at, retried.identity_id, retried.asset_id, retried.pipeline_generation, retried.attempt_generation, retried.lease_generation FROM retried JOIN events ON events.job_id = retried.id
`

type RetryIngestionJobParams struct {
	ID              pgtype.UUID        `json:"id"`
	IdentityID      pgtype.UUID        `json:"identity_id"`
	LockedBy        pgtype.Text        `json:"locked_by"`
	LeaseGeneration int64              `json:"lease_generation"`
	Stage           string             `json:"stage"`
	ErrorCode       string             `json:"error_code"`
	ErrorMessage    string             `json:"error_message"`
	NextAttemptAt   pgtype.Timestamptz `json:"next_attempt_at"`
	EventMessage    string             `json:"event_message"`
}

type RetryIngestionJobRow struct {
	ID                 pgtype.UUID        `json:"id"`
	JobType            string             `json:"job_type"`
	DocumentID         pgtype.UUID        `json:"document_id"`
	VersionID          pgtype.UUID        `json:"version_id"`
	Status             string             `json:"status"`
	IdempotencyKey     string             `json:"idempotency_key"`
	Stage              string             `json:"stage"`
	AttemptCount       int32              `json:"attempt_count"`
	MaxAttempts        int32              `json:"max_attempts"`
	LockedBy           pgtype.Text        `json:"locked_by"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	NextAttemptAt      pgtype.Timestamptz `json:"next_attempt_at"`
	Payload            []byte             `json:"payload"`
	ErrorCode          string             `json:"error_code"`
	ErrorMessage       string             `json:"error_message"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	IdentityID         pgtype.UUID        `json:"identity_id"`
	AssetID            pgtype.UUID        `json:"asset_id"`
	PipelineGeneration int64              `json:"pipeline_generation"`
	AttemptGeneration  int64              `json:"attempt_generation"`
	LeaseGeneration    int64              `json:"lease_generation"`
}

func (q *Queries) RetryIngestionJob(ctx context.Context, arg RetryIngestionJobParams) (RetryIngestionJobRow, error) {
	row := q.db.QueryRow(ctx, retryIngestionJob,
		arg.ID,
		arg.IdentityID,
		arg.LockedBy,
		arg.LeaseGeneration,
		arg.Stage,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.NextAttemptAt,
		arg.EventMessage,
	)
	var i RetryIngestionJobRow
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.DocumentID,
		&i.VersionID,
		&i.Status,
		&i.IdempotencyKey,
		&i.Stage,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedUntil,
		&i.NextAttemptAt,
		&i.Payload,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.IdentityID,
		&i.AssetID,
		&i.PipelineGeneration,
		&i.AttemptGeneration,
		&i.LeaseGeneration,
	)
	return i, err
}

const updateIngestionJobStatus = `-- name: UpdateIngestionJobStatus :one
WITH target AS (
    SELECT target_job.id, target_job.status AS prior_status
    FROM aura.ingestion_jobs target_job
    WHERE target_job.id = $1
      AND target_job.identity_id = $2
      AND target_job.status = 'running'
      AND target_job.locked_by = $3
      AND target_job.lease_generation = $4
    FOR UPDATE
), transitioned AS (
    UPDATE aura.ingestion_jobs job
    SET status = $5, stage = $6,
        error_code = $7, error_message = $8,
        locked_by = NULL, locked_until = NULL,
        completed_at = CASE WHEN $5::text IN (
            'succeeded', 'failed', 'dead_letter', 'canceled'
        ) THEN now() ELSE NULL END,
        updated_at = now()
    FROM target WHERE job.id = target.id
    RETURNING job.id, job.job_type, job.document_id, job.version_id, job.status, job.idempotency_key, job.stage, job.attempt_count, job.max_attempts, job.locked_by, job.locked_until, job.next_attempt_at, job.payload, job.error_code, job.error_message, job.created_at, job.updated_at, job.completed_at, job.identity_id, job.asset_id, job.pipeline_generation, job.attempt_generation, job.lease_generation, target.prior_status
), events AS (
    INSERT INTO aura.ingestion_events (
        identity_id, entity_type, entity_id, job_id, from_status, to_status,
        event_type, message, detail, trace_id,
        pipeline_generation, attempt_generation, lease_generation
    )
    SELECT transitioned.identity_id, 'ingestion_job', transitioned.id, transitioned.id,
           transitioned.prior_status, transitioned.status, $9,
           $10, $11, $12,
           transitioned.pipeline_generation, transitioned.attempt_generation, transitioned.lease_generation
    FROM transitioned
    RETURNING job_id
)
SELECT transitioned.id, transitioned.job_type, transitioned.document_id, transitioned.version_id, transitioned.status, transitioned.idempotency_key, transitioned.stage, transitioned.attempt_count, transitioned.max_attempts, transitioned.locked_by, transitioned.locked_until, transitioned.next_attempt_at, transitioned.payload, transitioned.error_code, transitioned.error_message, transitioned.created_at, transitioned.updated_at, transitioned.completed_at, transitioned.identity_id, transitioned.asset_id, transitioned.pipeline_generation, transitioned.attempt_generation, transitioned.lease_generation FROM transitioned JOIN events ON events.job_id = transitioned.id
`

type UpdateIngestionJobStatusParams struct {
	ID              pgtype.UUID `json:"id"`
	IdentityID      pgtype.UUID `json:"identity_id"`
	LockedBy        pgtype.Text `json:"locked_by"`
	LeaseGeneration int64       `json:"lease_generation"`
	Status          string      `json:"status"`
	Stage           string      `json:"stage"`
	ErrorCode       string      `json:"error_code"`
	ErrorMessage    string      `json:"error_message"`
	EventType       string      `json:"event_type"`
	EventMessage    string      `json:"event_message"`
	EventDetail     []byte      `json:"event_detail"`
	TraceID         string      `json:"trace_id"`
}

type UpdateIngestionJobStatusRow struct {
	ID                 pgtype.UUID        `json:"id"`
	JobType            string             `json:"job_type"`
	DocumentID         pgtype.UUID        `json:"document_id"`
	VersionID          pgtype.UUID        `json:"version_id"`
	Status             string             `json:"status"`
	IdempotencyKey     string             `json:"idempotency_key"`
	Stage              string             `json:"stage"`
	AttemptCount       int32              `json:"attempt_count"`
	MaxAttempts        int32              `json:"max_attempts"`
	LockedBy           pgtype.Text        `json:"locked_by"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	NextAttemptAt      pgtype.Timestamptz `json:"next_attempt_at"`
	Payload            []byte             `json:"payload"`
	ErrorCode          string             `json:"error_code"`
	ErrorMessage       string             `json:"error_message"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	IdentityID         pgtype.UUID        `json:"identity_id"`
	AssetID            pgtype.UUID        `json:"asset_id"`
	PipelineGeneration int64              `json:"pipeline_generation"`
	AttemptGeneration  int64              `json:"attempt_generation"`
	LeaseGeneration    int64              `json:"lease_generation"`
}

func (q *Queries) UpdateIngestionJobStatus(ctx context.Context, arg UpdateIngestionJobStatusParams) (UpdateIngestionJobStatusRow, error) {
	row := q.db.QueryRow(ctx, updateIngestionJobStatus,
		arg.ID,
		arg.IdentityID,
		arg.LockedBy,
		arg.LeaseGeneration,
		arg.Status,
		arg.Stage,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.EventType,
		arg.EventMessage,
		arg.EventDetail,
		arg.TraceID,
	)
	var i UpdateIngestionJobStatusRow
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.DocumentID,
		&i.VersionID,
		&i.Status,
		&i.IdempotencyKey,
		&i.Stage,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedUntil,
		&i.NextAttemptAt,
		&i.Payload,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.IdentityID,
		&i.AssetID,
		&i.PipelineGeneration,
		&i.AttemptGeneration,
		&i.LeaseGeneration,
	)
	return i, err
}

const upsertDocumentTag = `-- name: UpsertDocumentTag :exec
INSERT INTO aura.document_tags (document_id, tag, created_by)
VALUES ($1, $2, $3)
ON CONFLICT (document_id, tag) DO NOTHING
`

type UpsertDocumentTagParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	Tag        string      `json:"tag"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

func (q *Queries) UpsertDocumentTag(ctx context.Context, arg UpsertDocumentTagParams) error {
	_, err := q.db.Exec(ctx, upsertDocumentTag, arg.DocumentID, arg.Tag, arg.CreatedBy)
	return err
}
