// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateway_tool_policies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearGatewayToolPolicy = `-- name: ClearGatewayToolPolicy :execrows
DELETE FROM aura.gateway_tool_policies
WHERE identity_id = $1
  AND tool = $2
  AND action = $3
`

type ClearGatewayToolPolicyParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Tool       string      `json:"tool"`
	Action     string      `json:"action"`
}

func (q *Queries) ClearGatewayToolPolicy(ctx context.Context, arg ClearGatewayToolPolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearGatewayToolPolicy, arg.IdentityID, arg.Tool, arg.Action)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGatewayToolPolicy = `-- name: GetGatewayToolPolicy :one
SELECT policy
FROM aura.gateway_tool_policies
WHERE identity_id = $1
  AND tool = $2
  AND action = $3
`

type GetGatewayToolPolicyParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Tool       string      `json:"tool"`
	Action     string      `json:"action"`
}

func (q *Queries) GetGatewayToolPolicy(ctx context.Context, arg GetGatewayToolPolicyParams) (string, error) {
	row := q.db.QueryRow(ctx, getGatewayToolPolicy, arg.IdentityID, arg.Tool, arg.Action)
	var policy string
	err := row.Scan(&policy)
	return policy, err
}

const listGatewayToolPolicies = `-- name: ListGatewayToolPolicies :many
SELECT identity_id, tool, action, policy, set_at, set_by
FROM aura.gateway_tool_policies
WHERE identity_id = $1
ORDER BY tool ASC, action ASC
`

func (q *Queries) ListGatewayToolPolicies(ctx context.Context, identityID pgtype.UUID) ([]AuraGatewayToolPolicies, error) {
	rows, err := q.db.Query(ctx, listGatewayToolPolicies, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraGatewayToolPolicies{}
	for rows.Next() {
		var i AuraGatewayToolPolicies
		if err := rows.Scan(
			&i.IdentityID,
			&i.Tool,
			&i.Action,
			&i.Policy,
			&i.SetAt,
			&i.SetBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGatewayToolPolicy = `-- name: SetGatewayToolPolicy :exec
INSERT INTO aura.gateway_tool_policies (identity_id, tool, action, policy, set_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (identity_id, tool, action)
DO UPDATE SET policy = EXCLUDED.policy, set_at = now(), set_by = EXCLUDED.set_by
`

type SetGatewayToolPolicyParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Tool       string      `json:"tool"`
	Action     string      `json:"action"`
	Policy     string      `json:"policy"`
	SetBy      pgtype.Text `json:"set_by"`
}

func (q *Queries) SetGatewayToolPolicy(ctx context.Context, arg SetGatewayToolPolicyParams) error {
	_, err := q.db.Exec(ctx, setGatewayToolPolicy,
		arg.IdentityID,
		arg.Tool,
		arg.Action,
		arg.Policy,
		arg.SetBy,
	)
	return err
}
