// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency_operations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearExpiredReplayBody = `-- name: ClearExpiredReplayBody :execrows
UPDATE aura.idempotency_operations
SET replay_body = NULL,
    replay_preview = NULL,
    replay_sidecar_ref = NULL,
    replay_bytes = 0,
    updated_at = $1,
    version = version + 1
WHERE identity_id = $2
  AND operation_scope = $3
  AND operation_key = $4
  AND state = 'completed'
  AND replay_expires_at <= $5
  AND (replay_body IS NOT NULL OR replay_preview IS NOT NULL OR replay_sidecar_ref IS NOT NULL)
`

type ClearExpiredReplayBodyParams struct {
	ClearedAt      pgtype.Timestamptz `json:"cleared_at"`
	IdentityID     pgtype.UUID        `json:"identity_id"`
	OperationScope string             `json:"operation_scope"`
	OperationKey   string             `json:"operation_key"`
	Before         pgtype.Timestamptz `json:"before"`
}

func (q *Queries) ClearExpiredReplayBody(ctx context.Context, arg ClearExpiredReplayBodyParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearExpiredReplayBody,
		arg.ClearedAt,
		arg.IdentityID,
		arg.OperationScope,
		arg.OperationKey,
		arg.Before,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeOperation = `-- name: CompleteOperation :execrows
UPDATE aura.idempotency_operations
SET state = 'completed',
    replay_body = $1,
    replay_preview = $2,
    replay_sidecar_ref = $3,
    replay_bytes = $4,
    replay_expires_at = $5,
    completed_at = $6,
    updated_at = $6,
    version = version + 1
WHERE identity_id = $7
  AND operation_scope = $8
  AND operation_key = $9
  AND state = 'in_progress' AND payload_hash = $10
`

type CompleteOperationParams struct {
	ReplayBody       []byte             `json:"replay_body"`
	ReplayPreview    pgtype.Text        `json:"replay_preview"`
	ReplaySidecarRef pgtype.Text        `json:"replay_sidecar_ref"`
	ReplayBytes      int64              `json:"replay_bytes"`
	ReplayExpiresAt  pgtype.Timestamptz `json:"replay_expires_at"`
	Now              pgtype.Timestamptz `json:"now"`
	IdentityID       pgtype.UUID        `json:"identity_id"`
	OperationScope   string             `json:"operation_scope"`
	OperationKey     string             `json:"operation_key"`
	PayloadHash      []byte             `json:"payload_hash"`
}

func (q *Queries) CompleteOperation(ctx context.Context, arg CompleteOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeOperation,
		arg.ReplayBody,
		arg.ReplayPreview,
		arg.ReplaySidecarRef,
		arg.ReplayBytes,
		arg.ReplayExpiresAt,
		arg.Now,
		arg.IdentityID,
		arg.OperationScope,
		arg.OperationKey,
		arg.PayloadHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOperation = `-- name: GetOperation :one
SELECT
    identity_id,
    operation_scope,
    operation_key,
    payload_hash,
    state,
    replay_body,
    replay_preview,
    replay_sidecar_ref,
    replay_bytes,
    replay_expires_at,
    lease_expires_at,
    retry_after,
    audit_conversation_id,
    audit_request_id,
    audit_tool_call_id,
    version,
    created_at,
    updated_at,
    completed_at,
    indeterminate_at
FROM aura.idempotency_operations
WHERE identity_id = $1
  AND operation_scope = $2
  AND operation_key = $3
`

type GetOperationParams struct {
	IdentityID     pgtype.UUID `json:"identity_id"`
	OperationScope string      `json:"operation_scope"`
	OperationKey   string      `json:"operation_key"`
}

func (q *Queries) GetOperation(ctx context.Context, arg GetOperationParams) (AuraIdempotencyOperations, error) {
	row := q.db.QueryRow(ctx, getOperation, arg.IdentityID, arg.OperationScope, arg.OperationKey)
	var i AuraIdempotencyOperations
	err := row.Scan(
		&i.IdentityID,
		&i.OperationScope,
		&i.OperationKey,
		&i.PayloadHash,
		&i.State,
		&i.ReplayBody,
		&i.ReplayPreview,
		&i.ReplaySidecarRef,
		&i.ReplayBytes,
		&i.ReplayExpiresAt,
		&i.LeaseExpiresAt,
		&i.RetryAfter,
		&i.AuditConversationID,
		&i.AuditRequestID,
		&i.AuditToolCallID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.IndeterminateAt,
	)
	return i, err
}

const listExpiredReplayBodies = `-- name: ListExpiredReplayBodies :many
SELECT
    identity_id,
    operation_scope,
    operation_key,
    replay_bytes,
    replay_expires_at
FROM aura.idempotency_operations
WHERE state = 'completed'
  AND replay_expires_at <= $1
  AND (replay_body IS NOT NULL OR replay_preview IS NOT NULL OR replay_sidecar_ref IS NOT NULL)
ORDER BY replay_expires_at ASC, identity_id, operation_scope, operation_key
LIMIT $2
`

type ListExpiredReplayBodiesParams struct {
	Before    pgtype.Timestamptz `json:"before"`
	BatchSize int32              `json:"batch_size"`
}

type ListExpiredReplayBodiesRow struct {
	IdentityID      pgtype.UUID        `json:"identity_id"`
	OperationScope  string             `json:"operation_scope"`
	OperationKey    string             `json:"operation_key"`
	ReplayBytes     int64              `json:"replay_bytes"`
	ReplayExpiresAt pgtype.Timestamptz `json:"replay_expires_at"`
}

func (q *Queries) ListExpiredReplayBodies(ctx context.Context, arg ListExpiredReplayBodiesParams) ([]ListExpiredReplayBodiesRow, error) {
	rows, err := q.db.Query(ctx, listExpiredReplayBodies, arg.Before, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredReplayBodiesRow{}
	for rows.Next() {
		var i ListExpiredReplayBodiesRow
		if err := rows.Scan(
			&i.IdentityID,
			&i.OperationScope,
			&i.OperationKey,
			&i.ReplayBytes,
			&i.ReplayExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOperationIndeterminate = `-- name: MarkOperationIndeterminate :execrows
UPDATE aura.idempotency_operations
SET state = 'indeterminate',
    indeterminate_at = $1,
    updated_at = $1,
    version = version + 1
WHERE identity_id = $2
  AND operation_scope = $3
  AND operation_key = $4
  AND state = 'in_progress' AND payload_hash = $5
`

type MarkOperationIndeterminateParams struct {
	Now            pgtype.Timestamptz `json:"now"`
	IdentityID     pgtype.UUID        `json:"identity_id"`
	OperationScope string             `json:"operation_scope"`
	OperationKey   string             `json:"operation_key"`
	PayloadHash    []byte             `json:"payload_hash"`
}

func (q *Queries) MarkOperationIndeterminate(ctx context.Context, arg MarkOperationIndeterminateParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOperationIndeterminate,
		arg.Now,
		arg.IdentityID,
		arg.OperationScope,
		arg.OperationKey,
		arg.PayloadHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tryStartOperation = `-- name: TryStartOperation :execrows
INSERT INTO aura.idempotency_operations (
    identity_id,
    operation_scope,
    operation_key,
    payload_hash,
    state,
    lease_expires_at,
    retry_after,
    audit_conversation_id,
    audit_request_id,
    audit_tool_call_id,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'in_progress',
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $10
)
ON CONFLICT (identity_id, operation_scope, operation_key) DO NOTHING
`

type TryStartOperationParams struct {
	IdentityID          pgtype.UUID        `json:"identity_id"`
	OperationScope      string             `json:"operation_scope"`
	OperationKey        string             `json:"operation_key"`
	PayloadHash         []byte             `json:"payload_hash"`
	LeaseExpiresAt      pgtype.Timestamptz `json:"lease_expires_at"`
	RetryAfter          pgtype.Timestamptz `json:"retry_after"`
	AuditConversationID pgtype.UUID        `json:"audit_conversation_id"`
	AuditRequestID      pgtype.UUID        `json:"audit_request_id"`
	AuditToolCallID     pgtype.Text        `json:"audit_tool_call_id"`
	Now                 pgtype.Timestamptz `json:"now"`
}

func (q *Queries) TryStartOperation(ctx context.Context, arg TryStartOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, tryStartOperation,
		arg.IdentityID,
		arg.OperationScope,
		arg.OperationKey,
		arg.PayloadHash,
		arg.LeaseExpiresAt,
		arg.RetryAfter,
		arg.AuditConversationID,
		arg.AuditRequestID,
		arg.AuditToolCallID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
