// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_mcp_oauth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteIdentityMCPOAuth = `-- name: DeleteIdentityMCPOAuth :execrows
DELETE FROM aura.identity_mcp_oauth
WHERE identity_id = $1 AND server_name = $2
`

type DeleteIdentityMCPOAuthParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	ServerName string      `json:"server_name"`
}

// Revoking locally. execrows, not exec: a caller that reports "revoked" without knowing
// whether a row existed cannot tell a real revocation from a no-op on someone else's row
// that RLS filtered away.
func (q *Queries) DeleteIdentityMCPOAuth(ctx context.Context, arg DeleteIdentityMCPOAuthParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdentityMCPOAuth, arg.IdentityID, arg.ServerName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdentityMCPOAuth = `-- name: GetIdentityMCPOAuth :one

SELECT identity_id, server_name, resource_url, access_token_enc, refresh_token_enc,
       client_info_enc, token_type, scopes, expires_at, created_at, updated_at
FROM aura.identity_mcp_oauth
WHERE identity_id = $1 AND server_name = $2
`

type GetIdentityMCPOAuthParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	ServerName string      `json:"server_name"`
}

// Per-identity OAuth grants for remote MCP servers (migration 0100). Every statement is
// scoped by identity_id in the WHERE clause AND by the two RLS policies underneath: the
// predicate here is what makes the intent readable, the policy is what makes it true even
// when a future caller forgets to write it.
func (q *Queries) GetIdentityMCPOAuth(ctx context.Context, arg GetIdentityMCPOAuthParams) (AuraIdentityMcpOauth, error) {
	row := q.db.QueryRow(ctx, getIdentityMCPOAuth, arg.IdentityID, arg.ServerName)
	var i AuraIdentityMcpOauth
	err := row.Scan(
		&i.IdentityID,
		&i.ServerName,
		&i.ResourceUrl,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.ClientInfoEnc,
		&i.TokenType,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdentityMCPOAuthServers = `-- name: ListIdentityMCPOAuthServers :many
SELECT server_name, resource_url, expires_at, updated_at
FROM aura.identity_mcp_oauth
WHERE identity_id = $1
ORDER BY server_name
`

type ListIdentityMCPOAuthServersRow struct {
	ServerName  string             `json:"server_name"`
	ResourceUrl string             `json:"resource_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// The names an identity has authorized, for `aura mcp login --status` and the cockpit's
// connector list. Deliberately selects NO ciphertext: a listing must not pull three
// credentials into memory to render a name and an expiry.
func (q *Queries) ListIdentityMCPOAuthServers(ctx context.Context, identityID pgtype.UUID) ([]ListIdentityMCPOAuthServersRow, error) {
	rows, err := q.db.Query(ctx, listIdentityMCPOAuthServers, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIdentityMCPOAuthServersRow{}
	for rows.Next() {
		var i ListIdentityMCPOAuthServersRow
		if err := rows.Scan(
			&i.ServerName,
			&i.ResourceUrl,
			&i.ExpiresAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIdentityMCPOAuth = `-- name: UpsertIdentityMCPOAuth :exec
INSERT INTO aura.identity_mcp_oauth (
    identity_id, server_name, resource_url, access_token_enc, refresh_token_enc,
    client_info_enc, token_type, scopes, expires_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (identity_id, server_name) DO UPDATE SET
    resource_url      = EXCLUDED.resource_url,
    access_token_enc  = EXCLUDED.access_token_enc,
    refresh_token_enc = EXCLUDED.refresh_token_enc,
    client_info_enc   = EXCLUDED.client_info_enc,
    token_type        = EXCLUDED.token_type,
    scopes            = EXCLUDED.scopes,
    expires_at        = EXCLUDED.expires_at,
    updated_at        = now()
`

type UpsertIdentityMCPOAuthParams struct {
	IdentityID      pgtype.UUID        `json:"identity_id"`
	ServerName      string             `json:"server_name"`
	ResourceUrl     string             `json:"resource_url"`
	AccessTokenEnc  []byte             `json:"access_token_enc"`
	RefreshTokenEnc []byte             `json:"refresh_token_enc"`
	ClientInfoEnc   []byte             `json:"client_info_enc"`
	TokenType       string             `json:"token_type"`
	Scopes          []string           `json:"scopes"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

// A refresh rewrites the same row, so this is an UPDATE-on-conflict rather than the
// delete-then-insert aura.identity_object_store uses for key rotation. created_at is
// deliberately left alone on conflict: it records when the identity first authorized this
// server, which a refresh does not change.
func (q *Queries) UpsertIdentityMCPOAuth(ctx context.Context, arg UpsertIdentityMCPOAuthParams) error {
	_, err := q.db.Exec(ctx, upsertIdentityMCPOAuth,
		arg.IdentityID,
		arg.ServerName,
		arg.ResourceUrl,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.ClientInfoEnc,
		arg.TokenType,
		arg.Scopes,
		arg.ExpiresAt,
	)
	return err
}
