// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO aura.identities (id, name, kind)
VALUES ($1, $2, $3)
RETURNING id, name, kind, created_at, deactivated_at, purge_after
`

type CreateIdentityParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Kind string      `json:"kind"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (AuraIdentities, error) {
	row := q.db.QueryRow(ctx, createIdentity, arg.ID, arg.Name, arg.Kind)
	var i AuraIdentities
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.DeactivatedAt,
		&i.PurgeAfter,
	)
	return i, err
}

const deleteIdentity = `-- name: DeleteIdentity :exec
DELETE FROM aura.identities
WHERE name = $1
`

func (q *Queries) DeleteIdentity(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteIdentity, name)
	return err
}

const getIdentityByID = `-- name: GetIdentityByID :one
SELECT id, name, kind, created_at, deactivated_at, purge_after
FROM aura.identities
WHERE id = $1
`

func (q *Queries) GetIdentityByID(ctx context.Context, id pgtype.UUID) (AuraIdentities, error) {
	row := q.db.QueryRow(ctx, getIdentityByID, id)
	var i AuraIdentities
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.DeactivatedAt,
		&i.PurgeAfter,
	)
	return i, err
}

const getIdentityByName = `-- name: GetIdentityByName :one
SELECT id, name, kind, created_at, deactivated_at, purge_after
FROM aura.identities
WHERE name = $1
`

func (q *Queries) GetIdentityByName(ctx context.Context, name string) (AuraIdentities, error) {
	row := q.db.QueryRow(ctx, getIdentityByName, name)
	var i AuraIdentities
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.DeactivatedAt,
		&i.PurgeAfter,
	)
	return i, err
}

const listIdentities = `-- name: ListIdentities :many
SELECT id, name, kind, created_at, deactivated_at, purge_after
FROM aura.identities
ORDER BY created_at ASC, name ASC
`

func (q *Queries) ListIdentities(ctx context.Context) ([]AuraIdentities, error) {
	rows, err := q.db.Query(ctx, listIdentities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraIdentities{}
	for rows.Next() {
		var i AuraIdentities
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
			&i.DeactivatedAt,
			&i.PurgeAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
