// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_provider_routes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listLLMProviderRoutes = `-- name: ListLLMProviderRoutes :many
SELECT provider, base_url, model, updated_at, updated_by
FROM aura.llm_provider_routes
ORDER BY provider
`

func (q *Queries) ListLLMProviderRoutes(ctx context.Context) ([]AuraLlmProviderRoutes, error) {
	rows, err := q.db.Query(ctx, listLLMProviderRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraLlmProviderRoutes{}
	for rows.Next() {
		var i AuraLlmProviderRoutes
		if err := rows.Scan(
			&i.Provider,
			&i.BaseUrl,
			&i.Model,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLLMProviderRoute = `-- name: UpsertLLMProviderRoute :one
INSERT INTO aura.llm_provider_routes (provider, base_url, model, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider) DO UPDATE
SET base_url   = EXCLUDED.base_url,
    model      = EXCLUDED.model,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING provider, base_url, model, updated_at, updated_by
`

type UpsertLLMProviderRouteParams struct {
	Provider  string      `json:"provider"`
	BaseUrl   string      `json:"base_url"`
	Model     string      `json:"model"`
	UpdatedBy pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpsertLLMProviderRoute(ctx context.Context, arg UpsertLLMProviderRouteParams) (AuraLlmProviderRoutes, error) {
	row := q.db.QueryRow(ctx, upsertLLMProviderRoute,
		arg.Provider,
		arg.BaseUrl,
		arg.Model,
		arg.UpdatedBy,
	)
	var i AuraLlmProviderRoutes
	err := row.Scan(
		&i.Provider,
		&i.BaseUrl,
		&i.Model,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
