// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMcpAudit = `-- name: InsertMcpAudit :one
INSERT INTO aura.mcp_audit (
    actor_identity_id, action, server_name, reason
)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, actor_identity_id, action, server_name, reason
`

type InsertMcpAuditParams struct {
	ActorIdentityID string      `json:"actor_identity_id"`
	Action          string      `json:"action"`
	ServerName      string      `json:"server_name"`
	Reason          pgtype.Text `json:"reason"`
}

func (q *Queries) InsertMcpAudit(ctx context.Context, arg InsertMcpAuditParams) (AuraMcpAudit, error) {
	row := q.db.QueryRow(ctx, insertMcpAudit,
		arg.ActorIdentityID,
		arg.Action,
		arg.ServerName,
		arg.Reason,
	)
	var i AuraMcpAudit
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ActorIdentityID,
		&i.Action,
		&i.ServerName,
		&i.Reason,
	)
	return i, err
}

const listMcpAudit = `-- name: ListMcpAudit :many
SELECT id, created_at, actor_identity_id, action, server_name, reason
FROM aura.mcp_audit
WHERE ($2::text IS NULL OR server_name = $2::text)
  AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
ORDER BY created_at DESC, id DESC
LIMIT $1
`

type ListMcpAuditParams struct {
	Limit      int32              `json:"limit"`
	ServerName pgtype.Text        `json:"server_name"`
	Since      pgtype.Timestamptz `json:"since"`
}

func (q *Queries) ListMcpAudit(ctx context.Context, arg ListMcpAuditParams) ([]AuraMcpAudit, error) {
	rows, err := q.db.Query(ctx, listMcpAudit, arg.Limit, arg.ServerName, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraMcpAudit{}
	for rows.Next() {
		var i AuraMcpAudit
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ActorIdentityID,
			&i.Action,
			&i.ServerName,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
