// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_server.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMCPServer = `-- name: DeleteMCPServer :execrows
DELETE FROM aura.mcp_server WHERE name = $1
`

func (q *Queries) DeleteMCPServer(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMCPServer, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMCPServers = `-- name: ListMCPServers :many
SELECT name, source, enabled, config, env_enc, profiles, created_by, created_at, updated_at
FROM aura.mcp_server
ORDER BY name
`

func (q *Queries) ListMCPServers(ctx context.Context) ([]AuraMcpServer, error) {
	rows, err := q.db.Query(ctx, listMCPServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraMcpServer{}
	for rows.Next() {
		var i AuraMcpServer
		if err := rows.Scan(
			&i.Name,
			&i.Source,
			&i.Enabled,
			&i.Config,
			&i.EnvEnc,
			&i.Profiles,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMCPServer = `-- name: UpsertMCPServer :one
INSERT INTO aura.mcp_server (name, source, enabled, config, env_enc, profiles, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (name) DO UPDATE
SET source     = EXCLUDED.source,
    enabled    = EXCLUDED.enabled,
    config     = EXCLUDED.config,
    env_enc    = EXCLUDED.env_enc,
    profiles   = EXCLUDED.profiles,
    updated_at = now()
RETURNING name, source, enabled, config, env_enc, profiles, created_by, created_at, updated_at
`

type UpsertMCPServerParams struct {
	Name      string      `json:"name"`
	Source    string      `json:"source"`
	Enabled   pgtype.Bool `json:"enabled"`
	Config    []byte      `json:"config"`
	EnvEnc    []byte      `json:"env_enc"`
	Profiles  []string    `json:"profiles"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) UpsertMCPServer(ctx context.Context, arg UpsertMCPServerParams) (AuraMcpServer, error) {
	row := q.db.QueryRow(ctx, upsertMCPServer,
		arg.Name,
		arg.Source,
		arg.Enabled,
		arg.Config,
		arg.EnvEnc,
		arg.Profiles,
		arg.CreatedBy,
	)
	var i AuraMcpServer
	err := row.Scan(
		&i.Name,
		&i.Source,
		&i.Enabled,
		&i.Config,
		&i.EnvEnc,
		&i.Profiles,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
