// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_profile.sql

package sqlc

import (
	"context"
)

const clearActiveMCPProfile = `-- name: ClearActiveMCPProfile :exec
UPDATE aura.mcp_profile SET active = false WHERE active
`

func (q *Queries) ClearActiveMCPProfile(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearActiveMCPProfile)
	return err
}

const deleteMCPProfilesExcept = `-- name: DeleteMCPProfilesExcept :exec
DELETE FROM aura.mcp_profile WHERE name <> ALL($1::text[])
`

func (q *Queries) DeleteMCPProfilesExcept(ctx context.Context, keep []string) error {
	_, err := q.db.Exec(ctx, deleteMCPProfilesExcept, keep)
	return err
}

const listMCPProfiles = `-- name: ListMCPProfiles :many
SELECT name, active, created_at
FROM aura.mcp_profile
ORDER BY name
`

func (q *Queries) ListMCPProfiles(ctx context.Context) ([]AuraMcpProfile, error) {
	rows, err := q.db.Query(ctx, listMCPProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraMcpProfile{}
	for rows.Next() {
		var i AuraMcpProfile
		if err := rows.Scan(&i.Name, &i.Active, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMCPProfile = `-- name: UpsertMCPProfile :exec
INSERT INTO aura.mcp_profile (name, active)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET active = EXCLUDED.active
`

type UpsertMCPProfileParams struct {
	Name   string `json:"name"`
	Active bool   `json:"active"`
}

func (q *Queries) UpsertMCPProfile(ctx context.Context, arg UpsertMCPProfileParams) error {
	_, err := q.db.Exec(ctx, upsertMCPProfile, arg.Name, arg.Active)
	return err
}
