// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindMediaJobAssetDelivery = `-- name: BindMediaJobAssetDelivery :execrows
UPDATE aura.assets SET tool_call_id = $3, updated_at = now()
WHERE id = $1 AND identity_id = $2 AND thread_id = $4
  AND source_kind = 'agent' AND status = 'accepted' AND deleted_at IS NULL
`

type BindMediaJobAssetDeliveryParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
	ToolCallID string      `json:"tool_call_id"`
	ThreadID   string      `json:"thread_id"`
}

func (q *Queries) BindMediaJobAssetDelivery(ctx context.Context, arg BindMediaJobAssetDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindMediaJobAssetDelivery,
		arg.ID,
		arg.IdentityID,
		arg.ToolCallID,
		arg.ThreadID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimMediaJobDelivery = `-- name: ClaimMediaJobDelivery :one
UPDATE aura.media_job SET delivered_at = now(), updated_at = now()
WHERE id = $1 AND identity_id = $2 AND conversation_id = $3
  AND status = 'completed' AND asset_id IS NOT NULL AND delivered_at IS NULL
RETURNING id, identity_id, conversation_id, tool_call_id, provider_job_id, model, request, status, error, asset_id, cost_usd, created_at, updated_at, completed_at, delivered_at, surface, kind
`

type ClaimMediaJobDeliveryParams struct {
	ID             pgtype.UUID `json:"id"`
	IdentityID     pgtype.UUID `json:"identity_id"`
	ConversationID string      `json:"conversation_id"`
}

func (q *Queries) ClaimMediaJobDelivery(ctx context.Context, arg ClaimMediaJobDeliveryParams) (AuraMediaJob, error) {
	row := q.db.QueryRow(ctx, claimMediaJobDelivery, arg.ID, arg.IdentityID, arg.ConversationID)
	var i AuraMediaJob
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.ConversationID,
		&i.ToolCallID,
		&i.ProviderJobID,
		&i.Model,
		&i.Request,
		&i.Status,
		&i.Error,
		&i.AssetID,
		&i.CostUsd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeliveredAt,
		&i.Surface,
		&i.Kind,
	)
	return i, err
}

const completeMediaJob = `-- name: CompleteMediaJob :one
UPDATE aura.media_job
SET status = 'completed',
    asset_id = $1,
    cost_usd = COALESCE($2::numeric, media_job.cost_usd),
    error = NULL,
    completed_at = now(),
    delivered_at = CASE WHEN media_job.surface = 'studio' THEN now() ELSE media_job.delivered_at END,
    updated_at = now()
WHERE media_job.id = $3
  AND media_job.identity_id = $4
  AND media_job.status IN ('pending', 'in_progress')
  AND EXISTS (
      SELECT 1 FROM aura.assets
      WHERE assets.id = $1
        AND assets.identity_id = media_job.identity_id
        AND assets.thread_id = media_job.conversation_id
        AND assets.source_kind = 'agent'
        AND assets.modality = media_job.kind
        AND assets.status = 'accepted'
        AND assets.deleted_at IS NULL
  )
RETURNING id, identity_id, conversation_id, tool_call_id, provider_job_id, model, request, status, error, asset_id, cost_usd, created_at, updated_at, completed_at, delivered_at, surface, kind
`

type CompleteMediaJobParams struct {
	AssetID    pgtype.UUID    `json:"asset_id"`
	CostUsd    pgtype.Numeric `json:"cost_usd"`
	ID         pgtype.UUID    `json:"id"`
	IdentityID pgtype.UUID    `json:"identity_id"`
}

// The asset must be deliverable by BindMediaJobAssetDelivery when the job completes: owned,
// in the job's conversation, an accepted agent video that is not deleted.
func (q *Queries) CompleteMediaJob(ctx context.Context, arg CompleteMediaJobParams) (AuraMediaJob, error) {
	row := q.db.QueryRow(ctx, completeMediaJob,
		arg.AssetID,
		arg.CostUsd,
		arg.ID,
		arg.IdentityID,
	)
	var i AuraMediaJob
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.ConversationID,
		&i.ToolCallID,
		&i.ProviderJobID,
		&i.Model,
		&i.Request,
		&i.Status,
		&i.Error,
		&i.AssetID,
		&i.CostUsd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeliveredAt,
		&i.Surface,
		&i.Kind,
	)
	return i, err
}

const getMediaJobForIdentity = `-- name: GetMediaJobForIdentity :one
SELECT id, identity_id, conversation_id, tool_call_id, provider_job_id, model, request, status, error, asset_id, cost_usd, created_at, updated_at, completed_at, delivered_at, surface, kind FROM aura.media_job WHERE id = $1 AND identity_id = $2
`

type GetMediaJobForIdentityParams struct {
	ID         pgtype.UUID `json:"id"`
	IdentityID pgtype.UUID `json:"identity_id"`
}

func (q *Queries) GetMediaJobForIdentity(ctx context.Context, arg GetMediaJobForIdentityParams) (AuraMediaJob, error) {
	row := q.db.QueryRow(ctx, getMediaJobForIdentity, arg.ID, arg.IdentityID)
	var i AuraMediaJob
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.ConversationID,
		&i.ToolCallID,
		&i.ProviderJobID,
		&i.Model,
		&i.Request,
		&i.Status,
		&i.Error,
		&i.AssetID,
		&i.CostUsd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeliveredAt,
		&i.Surface,
		&i.Kind,
	)
	return i, err
}

const insertCompletedMediaJob = `-- name: InsertCompletedMediaJob :one
INSERT INTO aura.media_job (
    identity_id, conversation_id, tool_call_id, provider_job_id, model, request,
    status, cost_usd, surface, kind, asset_id, completed_at, delivered_at
)
SELECT $1, '', '', $2, $3,
       $4, 'completed', $5::numeric, 'studio', 'image',
       assets.id, now(), now()
FROM aura.assets
WHERE assets.id = $6
  AND assets.identity_id = $1
  AND assets.thread_id = ''
  AND assets.source_kind = 'agent'
  AND assets.modality = 'image'
  AND assets.status = 'accepted'
  AND assets.deleted_at IS NULL
RETURNING id, identity_id, conversation_id, tool_call_id, provider_job_id, model, request, status, error, asset_id, cost_usd, created_at, updated_at, completed_at, delivered_at, surface, kind
`

type InsertCompletedMediaJobParams struct {
	IdentityID    pgtype.UUID    `json:"identity_id"`
	ProviderJobID string         `json:"provider_job_id"`
	Model         string         `json:"model"`
	Request       []byte         `json:"request"`
	CostUsd       pgtype.Numeric `json:"cost_usd"`
	AssetID       pgtype.UUID    `json:"asset_id"`
}

// One synchronous image generation, recorded finished. The asset must be the owner's
// accepted, undeleted agent image with no thread: the Studio's own result, never another
// identity's or a chat delivery.
func (q *Queries) InsertCompletedMediaJob(ctx context.Context, arg InsertCompletedMediaJobParams) (AuraMediaJob, error) {
	row := q.db.QueryRow(ctx, insertCompletedMediaJob,
		arg.IdentityID,
		arg.ProviderJobID,
		arg.Model,
		arg.Request,
		arg.CostUsd,
		arg.AssetID,
	)
	var i AuraMediaJob
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.ConversationID,
		&i.ToolCallID,
		&i.ProviderJobID,
		&i.Model,
		&i.Request,
		&i.Status,
		&i.Error,
		&i.AssetID,
		&i.CostUsd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeliveredAt,
		&i.Surface,
		&i.Kind,
	)
	return i, err
}

const insertMediaJob = `-- name: InsertMediaJob :one
INSERT INTO aura.media_job (
    identity_id, conversation_id, tool_call_id, provider_job_id, model, request, status, cost_usd,
    surface, kind
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, identity_id, conversation_id, tool_call_id, provider_job_id, model, request, status, error, asset_id, cost_usd, created_at, updated_at, completed_at, delivered_at, surface, kind
`

type InsertMediaJobParams struct {
	IdentityID     pgtype.UUID    `json:"identity_id"`
	ConversationID string         `json:"conversation_id"`
	ToolCallID     string         `json:"tool_call_id"`
	ProviderJobID  string         `json:"provider_job_id"`
	Model          string         `json:"model"`
	Request        []byte         `json:"request"`
	Status         string         `json:"status"`
	CostUsd        pgtype.Numeric `json:"cost_usd"`
	Surface        string         `json:"surface"`
	Kind           string         `json:"kind"`
}

func (q *Queries) InsertMediaJob(ctx context.Context, arg InsertMediaJobParams) (AuraMediaJob, error) {
	row := q.db.QueryRow(ctx, insertMediaJob,
		arg.IdentityID,
		arg.ConversationID,
		arg.ToolCallID,
		arg.ProviderJobID,
		arg.Model,
		arg.Request,
		arg.Status,
		arg.CostUsd,
		arg.Surface,
		arg.Kind,
	)
	var i AuraMediaJob
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.ConversationID,
		&i.ToolCallID,
		&i.ProviderJobID,
		&i.Model,
		&i.Request,
		&i.Status,
		&i.Error,
		&i.AssetID,
		&i.CostUsd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeliveredAt,
		&i.Surface,
		&i.Kind,
	)
	return i, err
}

const listRecoverableMediaJobs = `-- name: ListRecoverableMediaJobs :many
SELECT id, identity_id, conversation_id, tool_call_id, provider_job_id, model, request, status, error, asset_id, cost_usd, created_at, updated_at, completed_at, delivered_at, surface, kind FROM aura.media_job WHERE media_job.identity_id = $1
AND (media_job.status IN ('pending','in_progress') OR
     (media_job.status = 'completed' AND media_job.delivered_at IS NULL AND EXISTS (
         SELECT 1 FROM aura.assets
         WHERE assets.id = media_job.asset_id
           AND assets.identity_id = media_job.identity_id
           AND assets.thread_id = media_job.conversation_id
           AND assets.source_kind = 'agent'
           AND assets.status = 'accepted'
           AND assets.deleted_at IS NULL
     )))
ORDER BY created_at, id
`

// A completed, undelivered job is recoverable only while BindMediaJobAssetDelivery could still
// bind its asset: once the clip is deleted no delivery can succeed, so waking the conversation
// on every boot would only ever answer asset_not_found.
func (q *Queries) ListRecoverableMediaJobs(ctx context.Context, identityID pgtype.UUID) ([]AuraMediaJob, error) {
	rows, err := q.db.Query(ctx, listRecoverableMediaJobs, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraMediaJob{}
	for rows.Next() {
		var i AuraMediaJob
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.ConversationID,
			&i.ToolCallID,
			&i.ProviderJobID,
			&i.Model,
			&i.Request,
			&i.Status,
			&i.Error,
			&i.AssetID,
			&i.CostUsd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeliveredAt,
			&i.Surface,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudioMediaJobs = `-- name: ListStudioMediaJobs :many
SELECT id, identity_id, conversation_id, tool_call_id, provider_job_id, model, request, status, error, asset_id, cost_usd, created_at, updated_at, completed_at, delivered_at, surface, kind FROM aura.media_job
WHERE media_job.identity_id = $1
  AND media_job.surface = 'studio'
  AND ($2::text IS NULL OR media_job.kind = $2::text)
  AND ($3::uuid IS NULL OR (media_job.created_at, media_job.id) < (
      SELECT b.created_at, b.id FROM aura.media_job b
      WHERE b.id = $3::uuid AND b.identity_id = $1))
ORDER BY media_job.created_at DESC, media_job.id DESC
LIMIT $4
`

type ListStudioMediaJobsParams struct {
	IdentityID pgtype.UUID `json:"identity_id"`
	Kind       pgtype.Text `json:"kind"`
	BeforeID   pgtype.UUID `json:"before_id"`
	RowLimit   int32       `json:"row_limit"`
}

// One history page, newest first, optionally of one kind. before_id is the last row of the
// previous page; an id the owner does not hold compares as NULL and yields an empty page.
func (q *Queries) ListStudioMediaJobs(ctx context.Context, arg ListStudioMediaJobsParams) ([]AuraMediaJob, error) {
	rows, err := q.db.Query(ctx, listStudioMediaJobs,
		arg.IdentityID,
		arg.Kind,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraMediaJob{}
	for rows.Next() {
		var i AuraMediaJob
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.ConversationID,
			&i.ToolCallID,
			&i.ProviderJobID,
			&i.Model,
			&i.Request,
			&i.Status,
			&i.Error,
			&i.AssetID,
			&i.CostUsd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeliveredAt,
			&i.Surface,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaJobProgress = `-- name: UpdateMediaJobProgress :one
UPDATE aura.media_job
SET status = $1,
    cost_usd = COALESCE($2::numeric, cost_usd),
    error = $3,
    completed_at = CASE WHEN $1 IN ('failed', 'expired', 'cancelled') THEN now() ELSE completed_at END,
    updated_at = now()
WHERE id = $4
  AND identity_id = $5
  AND status IN ('pending', 'in_progress')
RETURNING id, identity_id, conversation_id, tool_call_id, provider_job_id, model, request, status, error, asset_id, cost_usd, created_at, updated_at, completed_at, delivered_at, surface, kind
`

type UpdateMediaJobProgressParams struct {
	Status     string         `json:"status"`
	CostUsd    pgtype.Numeric `json:"cost_usd"`
	Error      []byte         `json:"error"`
	ID         pgtype.UUID    `json:"id"`
	IdentityID pgtype.UUID    `json:"identity_id"`
}

// A NULL cost keeps the recorded one; a zero cost is recorded.
func (q *Queries) UpdateMediaJobProgress(ctx context.Context, arg UpdateMediaJobProgressParams) (AuraMediaJob, error) {
	row := q.db.QueryRow(ctx, updateMediaJobProgress,
		arg.Status,
		arg.CostUsd,
		arg.Error,
		arg.ID,
		arg.IdentityID,
	)
	var i AuraMediaJob
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.ConversationID,
		&i.ToolCallID,
		&i.ProviderJobID,
		&i.Model,
		&i.Request,
		&i.Status,
		&i.Error,
		&i.AssetID,
		&i.CostUsd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeliveredAt,
		&i.Surface,
		&i.Kind,
	)
	return i, err
}
