// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Per-run audit ledger (Slice 6 / Phase 10). Audit-forever (no aura_app DELETE, PRD OQ4). completed_with_hash is the SC#2 idempotency key (UNIQUE; a duplicate completion swallows 23505).
type AuraAgentJobRuns struct {
	ID                pgtype.UUID        `json:"id"`
	TaskID            pgtype.UUID        `json:"task_id"`
	Status            string             `json:"status"`
	StepBudget        pgtype.Int4        `json:"step_budget"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	LastHeartbeatAt   pgtype.Timestamptz `json:"last_heartbeat_at"`
	CompletedWithHash pgtype.Text        `json:"completed_with_hash"`
	Summary           pgtype.Text        `json:"summary"`
	LastError         pgtype.Text        `json:"last_error"`
	MissedSince       pgtype.Timestamptz `json:"missed_since"`
	PausedStateToken  pgtype.UUID        `json:"paused_state_token"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

type AuraAssetEvents struct {
	AssetID    pgtype.UUID        `json:"asset_id"`
	Seq        int32              `json:"seq"`
	FromStatus string             `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	Reason     string             `json:"reason"`
	Detail     []byte             `json:"detail"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuraAssets struct {
	ID                pgtype.UUID        `json:"id"`
	IdentityID        pgtype.UUID        `json:"identity_id"`
	SourceKind        string             `json:"source_kind"`
	SourceRef         string             `json:"source_ref"`
	ThreadID          string             `json:"thread_id"`
	Scope             string             `json:"scope"`
	Modality          string             `json:"modality"`
	Status            string             `json:"status"`
	FileName          string             `json:"file_name"`
	MimeType          string             `json:"mime_type"`
	DeclaredSizeBytes int64              `json:"declared_size_bytes"`
	SizeBytes         int64              `json:"size_bytes"`
	ContentHash       string             `json:"content_hash"`
	ObjectBucket      string             `json:"object_bucket"`
	ObjectKey         string             `json:"object_key"`
	ObjectEtag        string             `json:"object_etag"`
	DocumentID        string             `json:"document_id"`
	Summary           string             `json:"summary"`
	Metadata          []byte             `json:"metadata"`
	ErrorCode         string             `json:"error_code"`
	ErrorMessage      string             `json:"error_message"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UploadedAt        pgtype.Timestamptz `json:"uploaded_at"`
	AcceptedAt        pgtype.Timestamptz `json:"accepted_at"`
	ProcessedAt       pgtype.Timestamptz `json:"processed_at"`
	SearchableAt      pgtype.Timestamptz `json:"searchable_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Per-turn KV-cache metrics (Slice 4 / Phase 6, D-02). Append-only: one row per completed assistant turn from llm.Usage (token counts + cost only, no message content).
type AuraCacheMetrics struct {
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Seq            int32              `json:"seq"`
	Ts             pgtype.Timestamptz `json:"ts"`
	PromptTokens   int32              `json:"prompt_tokens"`
	CachedTokens   int32              `json:"cached_tokens"`
	CostUsd        pgtype.Numeric     `json:"cost_usd"`
}

// Per-identity capability grants. Wildcard `*` is system-managed (seeded, never grant/revoke via CLI).
type AuraCapabilityGrants struct {
	IdentityID pgtype.UUID        `json:"identity_id"`
	Capability string             `json:"capability"`
	GrantedAt  pgtype.Timestamptz `json:"granted_at"`
}

// L2.5 hard-rolling-buffer audit (amendment #22). One row per pair-drop; never written when L1 alone suffices (SC-1).
type AuraContextRotEvents struct {
	Ts             pgtype.Timestamptz `json:"ts"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Action         string             `json:"action"`
	PairsDropped   int32              `json:"pairs_dropped"`
	TokensBefore   int32              `json:"tokens_before"`
	TokensAfter    int32              `json:"tokens_after"`
}

// Per-turn rows (Slice 1.8). content NULL + content_sidecar_path set when content > AURA_CONVERSATION_TURN_CAP_BYTES.
type AuraConversationTurns struct {
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Seq                int32              `json:"seq"`
	Role               string             `json:"role"`
	Content            pgtype.Text        `json:"content"`
	ContentSidecarPath pgtype.Text        `json:"content_sidecar_path"`
	ToolCallID         pgtype.Text        `json:"tool_call_id"`
	ToolCalls          []byte             `json:"tool_calls"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	InputTokens        int32              `json:"input_tokens"`
	OutputTokens       int32              `json:"output_tokens"`
	CachedTokens       int32              `json:"cached_tokens"`
	// D-09 branch tree (CHAT-05): the branch a turn belongs to. All-zero UUID = the per-conversation canonical branch (pre-0017 backfill).
	BranchID pgtype.UUID `json:"branch_id"`
	// D-09 branch tree (CHAT-05): seq of the parent turn within the conversation; NULL at the root (seq=1). Canonical backfill: seq-1.
	ParentSeq pgtype.Int4 `json:"parent_seq"`
}

// Multi-thread persisted conversations (Slice 1.8). Aggregates token + USD totals per thread.
type AuraConversations struct {
	ID                pgtype.UUID        `json:"id"`
	Title             pgtype.Text        `json:"title"`
	IdentityID        pgtype.UUID        `json:"identity_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastActiveAt      pgtype.Timestamptz `json:"last_active_at"`
	Status            string             `json:"status"`
	Model             string             `json:"model"`
	TotalInputTokens  int64              `json:"total_input_tokens"`
	TotalOutputTokens int64              `json:"total_output_tokens"`
	TotalCachedTokens int64              `json:"total_cached_tokens"`
	TotalCostUsd      pgtype.Numeric     `json:"total_cost_usd"`
	Metadata          []byte             `json:"metadata"`
}

// Durable document ingestion job state. Neo4j stores document/chunk graph data; Postgres tracks lifecycle and progress.
type AuraDocumentIngestJobs struct {
	ID             pgtype.UUID        `json:"id"`
	SourceID       string             `json:"source_id"`
	SourceKind     string             `json:"source_kind"`
	DocumentID     string             `json:"document_id"`
	ContentHash    string             `json:"content_hash"`
	OriginalPath   string             `json:"original_path"`
	FileName       string             `json:"file_name"`
	MimeType       string             `json:"mime_type"`
	SizeBytes      int64              `json:"size_bytes"`
	Status         string             `json:"status"`
	SparseChunks   int32              `json:"sparse_chunks"`
	EmbeddedChunks int32              `json:"embedded_chunks"`
	Error          pgtype.Text        `json:"error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SearchableAt   pgtype.Timestamptz `json:"searchable_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

// Identity scaffolding (Slice 1.7). Single-user: one seeded `local`/system row with the fixed UUID ...001.
type AuraIdentities struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Kind      string             `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Maps an Authula user-id to a seeded aura.identities row (spec §5). Single-operator: the operator user pins to `local` (…0001). The A2 session-validate seam maps authula user-id -> this identity_id -> principalKey{}.
type AuraIdentityAuthLinks struct {
	IdentityID    pgtype.UUID        `json:"identity_id"`
	AuthulaUserID string             `json:"authula_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// Audit of applied Cypher migrations. Written by aura neo4j migrate; read by aura neo4j status.
type AuraKnowledgeMigrations struct {
	Version   int32              `json:"version"`
	Name      string             `json:"name"`
	Checksum  string             `json:"checksum"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

// ask_user HITL pauses (Slice 1.5). Pending = resumed_at IS NULL. FIFO order: priority DESC, created_at ASC, token ASC.
type AuraPausedStates struct {
	Token              pgtype.UUID        `json:"token"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Kind               string             `json:"kind"`
	Question           string             `json:"question"`
	Options            []byte             `json:"options"`
	Priority           int32              `json:"priority"`
	ResumeContext      []byte             `json:"resume_context"`
	ToolCallID         string             `json:"tool_call_id"`
	ProxiedFromChildID pgtype.Text        `json:"proxied_from_child_id"`
	ProxiedToolCallID  pgtype.Text        `json:"proxied_tool_call_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ResumedAt          pgtype.Timestamptz `json:"resumed_at"`
	ResumedAnswer      []byte             `json:"resumed_answer"`
}

// Durable scheduler notification queue (Phase 19 H6/H7): quiet-hours deferred notifications and failed self-send retry state.
type AuraPendingNotifications struct {
	ID          pgtype.UUID        `json:"id"`
	RunID       pgtype.UUID        `json:"run_id"`
	NotifyRoute pgtype.Text        `json:"notify_route"`
	Body        string             `json:"body"`
	NotifyAfter pgtype.Timestamptz `json:"notify_after"`
	Attempts    int32              `json:"attempts"`
	LastError   pgtype.Text        `json:"last_error"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	// Stable owning identity snapshot (Phase 20, Fork 1): the channel-independent delivery key for the deferred/failed sweep route-back. Plain text, no FK — survives a deleted origin conversation. NULL for legacy/CLI rows → falls back to notify_route.
	IdentityID pgtype.Text `json:"identity_id"`
}

// Scheduler task definitions (Slice 6 / Phase 10, amendment #46). Grammar triad at|every|cron with per-task IANA tz; next_run_at is UTC, recomputed in-zone (D-06/D-07).
type AuraSchedulerTasks struct {
	ID                   pgtype.UUID        `json:"id"`
	Kind                 string             `json:"kind"`
	ScheduleKind         string             `json:"schedule_kind"`
	CronExpr             pgtype.Text        `json:"cron_expr"`
	EveryMinutes         pgtype.Int4        `json:"every_minutes"`
	RunAt                pgtype.Timestamptz `json:"run_at"`
	Tz                   string             `json:"tz"`
	Payload              []byte             `json:"payload"`
	StepBudget           pgtype.Int4        `json:"step_budget"`
	Status               string             `json:"status"`
	NextRunAt            pgtype.Timestamptz `json:"next_run_at"`
	NotifyRoute          pgtype.Text        `json:"notify_route"`
	IdentityID           string             `json:"identity_id"`
	OriginConversationID pgtype.UUID        `json:"origin_conversation_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// Append-only skill-mutation audit ledger (Slice 7c / Phase 11, D-29). aura_app has SELECT+INSERT only; UPDATE/DELETE raise via a row trigger and TRUNCATE via a statement trigger (Pitfall 1/6). The D-29 coherence CHECK constrains the approval tuple to five allowed events; content_hash is the D-23 recovery path on every row.
type AuraSkillAudit struct {
	ID             pgtype.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ActorID        string             `json:"actor_id"`
	IdentityID     string             `json:"identity_id"`
	SkillName      string             `json:"skill_name"`
	Action         string             `json:"action"`
	ContentHash    string             `json:"content_hash"`
	ApprovalSource pgtype.Text        `json:"approval_source"`
	// Historical ask_user pause token. Intentionally not a live FK: paused_states are ephemeral and may be cascade-deleted with their conversation while audit rows remain append-only.
	PausedStateToken  pgtype.UUID `json:"paused_state_token"`
	GateRecommended   bool        `json:"gate_recommended"`
	GateTaken         bool        `json:"gate_taken"`
	BlocklistOverride bool        `json:"blocklist_override"`
}

// Known Telegram accounts (Slice 9a / Phase 13, amendment #58). PK telegram_user_id; identity_id FKs aura.identities (single-user `local` this phase, D-07).
type AuraTelegramAccounts struct {
	TelegramUserID int64              `json:"telegram_user_id"`
	IdentityID     pgtype.UUID        `json:"identity_id"`
	Username       pgtype.Text        `json:"username"`
	FirstName      pgtype.Text        `json:"first_name"`
	AddedAt        pgtype.Timestamptz `json:"added_at"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
}

// Single-use onboarding tokens (Slice 9a / Phase 13, amendment #58). consumed_at marks the token spent (T-13-01-TokenReplay); expires_at is a 1h TTL; the partial active index keys the cleanup scan.
type AuraTelegramSetupPending struct {
	OnboardingToken string             `json:"onboarding_token"`
	IdentityID      pgtype.UUID        `json:"identity_id"`
	GeneratedBy     pgtype.Text        `json:"generated_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt      pgtype.Timestamptz `json:"consumed_at"`
}

// Append-only tool invocation ledger: start/end facts for dispatched tools with args, timestamps, status, bytes, sidecar path, exit code, and typed metadata.
type AuraToolInvocations struct {
	ID                pgtype.UUID        `json:"id"`
	ConversationID    pgtype.UUID        `json:"conversation_id"`
	RequestID         pgtype.UUID        `json:"request_id"`
	ToolCallID        string             `json:"tool_call_id"`
	ToolName          string             `json:"tool_name"`
	EventKind         string             `json:"event_kind"`
	Seq               int32              `json:"seq"`
	Ts                pgtype.Timestamptz `json:"ts"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	EndedAt           pgtype.Timestamptz `json:"ended_at"`
	DurationMs        pgtype.Int8        `json:"duration_ms"`
	ArgsRaw           pgtype.Text        `json:"args_raw"`
	ArgsBytes         pgtype.Int4        `json:"args_bytes"`
	Status            pgtype.Text        `json:"status"`
	Error             pgtype.Text        `json:"error"`
	ResultPreview     pgtype.Text        `json:"result_preview"`
	PreviewBytes      pgtype.Int4        `json:"preview_bytes"`
	ResultBytes       pgtype.Int4        `json:"result_bytes"`
	ResultTruncated   pgtype.Bool        `json:"result_truncated"`
	ResultSidecarPath pgtype.Text        `json:"result_sidecar_path"`
	ExitCode          pgtype.Int4        `json:"exit_code"`
	Meta              []byte             `json:"meta"`
}
