// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Per-run audit ledger (Slice 6 / Phase 10). Audit-forever (no aura_app DELETE, PRD OQ4). completed_with_hash is the SC#2 idempotency key (UNIQUE; a duplicate completion swallows 23505).
type AuraAgentJobRuns struct {
	ID                pgtype.UUID        `json:"id"`
	TaskID            pgtype.UUID        `json:"task_id"`
	Status            string             `json:"status"`
	StepBudget        pgtype.Int4        `json:"step_budget"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	LastHeartbeatAt   pgtype.Timestamptz `json:"last_heartbeat_at"`
	CompletedWithHash pgtype.Text        `json:"completed_with_hash"`
	Summary           pgtype.Text        `json:"summary"`
	LastError         pgtype.Text        `json:"last_error"`
	MissedSince       pgtype.Timestamptz `json:"missed_since"`
	PausedStateToken  pgtype.UUID        `json:"paused_state_token"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

type AuraAssetEvents struct {
	AssetID    pgtype.UUID        `json:"asset_id"`
	Seq        int32              `json:"seq"`
	FromStatus string             `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	Reason     string             `json:"reason"`
	Detail     []byte             `json:"detail"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuraAssets struct {
	ID                pgtype.UUID        `json:"id"`
	IdentityID        pgtype.UUID        `json:"identity_id"`
	SourceKind        string             `json:"source_kind"`
	SourceRef         string             `json:"source_ref"`
	ThreadID          string             `json:"thread_id"`
	Scope             string             `json:"scope"`
	Modality          string             `json:"modality"`
	Status            string             `json:"status"`
	FileName          string             `json:"file_name"`
	MimeType          string             `json:"mime_type"`
	DeclaredSizeBytes int64              `json:"declared_size_bytes"`
	SizeBytes         int64              `json:"size_bytes"`
	ContentHash       string             `json:"content_hash"`
	ObjectBucket      string             `json:"object_bucket"`
	ObjectKey         string             `json:"object_key"`
	ObjectEtag        string             `json:"object_etag"`
	DocumentID        string             `json:"document_id"`
	Summary           string             `json:"summary"`
	Metadata          []byte             `json:"metadata"`
	ErrorCode         string             `json:"error_code"`
	ErrorMessage      string             `json:"error_message"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UploadedAt        pgtype.Timestamptz `json:"uploaded_at"`
	AcceptedAt        pgtype.Timestamptz `json:"accepted_at"`
	ProcessedAt       pgtype.Timestamptz `json:"processed_at"`
	SearchableAt      pgtype.Timestamptz `json:"searchable_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type AuraAuditLogs struct {
	ID              int64              `json:"id"`
	ActorIdentityID pgtype.UUID        `json:"actor_identity_id"`
	Action          string             `json:"action"`
	EntityType      string             `json:"entity_type"`
	EntityID        pgtype.UUID        `json:"entity_id"`
	Before          []byte             `json:"before"`
	After           []byte             `json:"after"`
	Reason          string             `json:"reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// Per-turn KV-cache metrics (Slice 4 / Phase 6, D-02). Append-only: one row per completed assistant turn from llm.Usage (token counts + cost only, no message content).
type AuraCacheMetrics struct {
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Seq            int32              `json:"seq"`
	Ts             pgtype.Timestamptz `json:"ts"`
	PromptTokens   int32              `json:"prompt_tokens"`
	CachedTokens   int32              `json:"cached_tokens"`
	CostUsd        pgtype.Numeric     `json:"cost_usd"`
}

// Per-identity capability grants. Wildcard `*` is system-managed (seeded, never grant/revoke via CLI).
type AuraCapabilityGrants struct {
	IdentityID pgtype.UUID        `json:"identity_id"`
	Capability string             `json:"capability"`
	GrantedAt  pgtype.Timestamptz `json:"granted_at"`
}

// L2.5 hard-rolling-buffer audit (amendment #22). One row per pair-drop; never written when L1 alone suffices (SC-1).
type AuraContextRotEvents struct {
	Ts             pgtype.Timestamptz `json:"ts"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Action         string             `json:"action"`
	PairsDropped   int32              `json:"pairs_dropped"`
	TokensBefore   int32              `json:"tokens_before"`
	TokensAfter    int32              `json:"tokens_after"`
}

// Per-turn rows (Slice 1.8). content NULL + content_sidecar_path set when content > AURA_CONVERSATION_TURN_CAP_BYTES.
type AuraConversationTurns struct {
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Seq                int32              `json:"seq"`
	Role               string             `json:"role"`
	Content            pgtype.Text        `json:"content"`
	ContentSidecarPath pgtype.Text        `json:"content_sidecar_path"`
	ToolCallID         pgtype.Text        `json:"tool_call_id"`
	ToolCalls          []byte             `json:"tool_calls"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	InputTokens        int32              `json:"input_tokens"`
	OutputTokens       int32              `json:"output_tokens"`
	CachedTokens       int32              `json:"cached_tokens"`
	// D-09 branch tree (CHAT-05): the branch a turn belongs to. All-zero UUID = the per-conversation canonical branch (pre-0017 backfill).
	BranchID pgtype.UUID `json:"branch_id"`
	// D-09 branch tree (CHAT-05): seq of the parent turn within the conversation; NULL at the root (seq=1). Canonical backfill: seq-1.
	ParentSeq pgtype.Int4 `json:"parent_seq"`
}

// Multi-thread persisted conversations (Slice 1.8). Aggregates token + USD totals per thread.
type AuraConversations struct {
	ID                pgtype.UUID        `json:"id"`
	Title             pgtype.Text        `json:"title"`
	IdentityID        pgtype.UUID        `json:"identity_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastActiveAt      pgtype.Timestamptz `json:"last_active_at"`
	Status            string             `json:"status"`
	Model             string             `json:"model"`
	TotalInputTokens  int64              `json:"total_input_tokens"`
	TotalOutputTokens int64              `json:"total_output_tokens"`
	TotalCachedTokens int64              `json:"total_cached_tokens"`
	TotalCostUsd      pgtype.Numeric     `json:"total_cost_usd"`
	Metadata          []byte             `json:"metadata"`
}

type AuraDeleteJobs struct {
	ID            pgtype.UUID        `json:"id"`
	DocumentID    pgtype.UUID        `json:"document_id"`
	VersionID     pgtype.UUID        `json:"version_id"`
	Scope         string             `json:"scope"`
	Status        string             `json:"status"`
	Steps         []byte             `json:"steps"`
	AttemptCount  int32              `json:"attempt_count"`
	MaxAttempts   int32              `json:"max_attempts"`
	LockedBy      pgtype.Text        `json:"locked_by"`
	LockedUntil   pgtype.Timestamptz `json:"locked_until"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

type AuraDocumentChunks struct {
	ID         pgtype.UUID        `json:"id"`
	DocumentID pgtype.UUID        `json:"document_id"`
	VersionID  pgtype.UUID        `json:"version_id"`
	ChunkIndex int32              `json:"chunk_index"`
	ChunkHash  string             `json:"chunk_hash"`
	Text       string             `json:"text"`
	Locator    []byte             `json:"locator"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type AuraDocumentEmbeddings struct {
	ID               pgtype.UUID        `json:"id"`
	DocumentID       pgtype.UUID        `json:"document_id"`
	VersionID        pgtype.UUID        `json:"version_id"`
	ChunkID          pgtype.UUID        `json:"chunk_id"`
	EmbeddingModel   string             `json:"embedding_model"`
	EmbeddingVersion string             `json:"embedding_version"`
	EmbeddingDim     int32              `json:"embedding_dim"`
	VectorNamespace  string             `json:"vector_namespace"`
	VectorID         string             `json:"vector_id"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

// Durable document ingestion job state. Neo4j stores document/chunk graph data; Postgres tracks lifecycle and progress.
type AuraDocumentIngestJobs struct {
	ID             pgtype.UUID        `json:"id"`
	SourceID       string             `json:"source_id"`
	SourceKind     string             `json:"source_kind"`
	DocumentID     string             `json:"document_id"`
	ContentHash    string             `json:"content_hash"`
	OriginalPath   string             `json:"original_path"`
	FileName       string             `json:"file_name"`
	MimeType       string             `json:"mime_type"`
	SizeBytes      int64              `json:"size_bytes"`
	Status         string             `json:"status"`
	SparseChunks   int32              `json:"sparse_chunks"`
	EmbeddedChunks int32              `json:"embedded_chunks"`
	Error          pgtype.Text        `json:"error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SearchableAt   pgtype.Timestamptz `json:"searchable_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type AuraDocumentTags struct {
	DocumentID pgtype.UUID        `json:"document_id"`
	Tag        string             `json:"tag"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Immutable document content versions and processing lifecycle state.
type AuraDocumentVersions struct {
	ID                 pgtype.UUID        `json:"id"`
	DocumentID         pgtype.UUID        `json:"document_id"`
	AssetID            pgtype.UUID        `json:"asset_id"`
	VersionNumber      int32              `json:"version_number"`
	Status             string             `json:"status"`
	Sha1               string             `json:"sha1"`
	Sha256             string             `json:"sha256"`
	ContentType        string             `json:"content_type"`
	SizeBytes          int64              `json:"size_bytes"`
	StorageObjectID    pgtype.UUID        `json:"storage_object_id"`
	ChunkingConfigHash string             `json:"chunking_config_hash"`
	PipelineConfigHash string             `json:"pipeline_config_hash"`
	ReadyAt            pgtype.Timestamptz `json:"ready_at"`
	ActivatedAt        pgtype.Timestamptz `json:"activated_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	ErrorCode          string             `json:"error_code"`
	ErrorMessage       string             `json:"error_message"`
}

// Stable logical documents across immutable content versions; tags are operator metadata for library search.
type AuraDocuments struct {
	ID              pgtype.UUID        `json:"id"`
	IdentityID      pgtype.UUID        `json:"identity_id"`
	Scope           string             `json:"scope"`
	Title           string             `json:"title"`
	Tags            []string           `json:"tags"`
	Metadata        []byte             `json:"metadata"`
	ActiveVersionID pgtype.UUID        `json:"active_version_id"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

// Identity scaffolding (Slice 1.7). Single-user: one seeded `local`/system row with the fixed UUID ...001.
type AuraIdentities struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Kind      string             `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Soft-delete marker (Phase 36, D-27): non-NULL once the identity is deactivated. Login is refused and work is paused; rows are retained until purge_after.
	DeactivatedAt pgtype.Timestamptz `json:"deactivated_at"`
	// End of the soft-delete grace window (Phase 36, D-27): after this instant the plan-08 de-provisioning saga may hard-delete the identity and cascade its owned data.
	PurgeAfter pgtype.Timestamptz `json:"purge_after"`
}

// Append-only identity-provisioning audit ledger (Phase 28, ONBD-01a). aura_app has SELECT+INSERT only; UPDATE/DELETE raise via a row trigger and TRUNCATE via a statement trigger (Pitfall 1/6). One immutable row per successful onboarding provision, written inside the provisioning db.WithTx.
type AuraIdentityAudit struct {
	ID                  pgtype.UUID        `json:"id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ActorIdentityID     string             `json:"actor_identity_id"`
	NewIdentityID       pgtype.UUID        `json:"new_identity_id"`
	NewIdentityName     string             `json:"new_identity_name"`
	GrantedCapabilities []string           `json:"granted_capabilities"`
	AuthulaUserID       string             `json:"authula_user_id"`
}

// Maps an Authula user-id to a seeded aura.identities row (spec §5). Single-operator: the operator user pins to `local` (…0001). The A2 session-validate seam maps authula user-id -> this identity_id -> principalKey{}.
type AuraIdentityAuthLinks struct {
	IdentityID    pgtype.UUID        `json:"identity_id"`
	AuthulaUserID string             `json:"authula_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// Per-identity Garage/S3 credential store (Phase 36, D-08/OQ4). secret_key_enc is the S3 secret as encrypted-at-rest bytea ciphertext (wrapping key derived from AURA_AUTHULA_SECRET, same trust boundary as .env); the AEAD is implemented by the plan-06 persistence layer. Deleting the identity cascades its key.
type AuraIdentityObjectStore struct {
	IdentityID   pgtype.UUID        `json:"identity_id"`
	Bucket       string             `json:"bucket"`
	AccessKey    string             `json:"access_key"`
	SecretKeyEnc []byte             `json:"secret_key_enc"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Per-identity recovery question and hashed answer for Telegram password reset. Raw answers are never stored.
type AuraIdentityRecovery struct {
	IdentityID        pgtype.UUID        `json:"identity_id"`
	Question          string             `json:"question"`
	AnswerHash        string             `json:"answer_hash"`
	AnswerHashVersion string             `json:"answer_hash_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Append-only recovery event audit. Contains no raw emails, answers, codes, passwords, IP addresses, or Telegram tokens.
type AuraIdentityRecoveryAudit struct {
	ID            pgtype.UUID        `json:"id"`
	IdentityID    pgtype.UUID        `json:"identity_id"`
	Event         string             `json:"event"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	RequestIpHash pgtype.Text        `json:"request_ip_hash"`
	UserAgentHash pgtype.Text        `json:"user_agent_hash"`
	Metadata      []byte             `json:"metadata"`
}

// Operator-visible progress and lifecycle events for documents, versions, jobs, and assets.
type AuraIngestionEvents struct {
	ID         int64              `json:"id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	JobID      pgtype.UUID        `json:"job_id"`
	FromStatus pgtype.Text        `json:"from_status"`
	ToStatus   pgtype.Text        `json:"to_status"`
	EventType  string             `json:"event_type"`
	Message    string             `json:"message"`
	Detail     []byte             `json:"detail"`
	TraceID    string             `json:"trace_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Durable document ingestion and cleanup queue with idempotency keys and worker leases.
type AuraIngestionJobs struct {
	ID             pgtype.UUID        `json:"id"`
	JobType        string             `json:"job_type"`
	DocumentID     pgtype.UUID        `json:"document_id"`
	VersionID      pgtype.UUID        `json:"version_id"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	Stage          string             `json:"stage"`
	AttemptCount   int32              `json:"attempt_count"`
	MaxAttempts    int32              `json:"max_attempts"`
	LockedBy       pgtype.Text        `json:"locked_by"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	Payload        []byte             `json:"payload"`
	ErrorCode      string             `json:"error_code"`
	ErrorMessage   string             `json:"error_message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

// Audit of applied Cypher migrations. Written by aura neo4j migrate; read by aura neo4j status.
type AuraKnowledgeMigrations struct {
	Version   int32              `json:"version"`
	Name      string             `json:"name"`
	Checksum  string             `json:"checksum"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

// Append-only MCP-config-mutation audit ledger (Phase 29, MCPW-02). aura_app has SELECT+INSERT only; UPDATE/DELETE raise via a row trigger and TRUNCATE via a statement trigger (Pitfall 3). One immutable row per MCP config mutation, written inside the mutation db.WithTx.
type AuraMcpAudit struct {
	ID              pgtype.UUID        `json:"id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ActorIdentityID string             `json:"actor_identity_id"`
	Action          string             `json:"action"`
	ServerName      string             `json:"server_name"`
	Reason          pgtype.Text        `json:"reason"`
}

// Short-lived Telegram code challenges for self-service Authula password reset.
type AuraPasswordResetChallenges struct {
	ID             pgtype.UUID        `json:"id"`
	IdentityID     pgtype.UUID        `json:"identity_id"`
	CodeHash       string             `json:"code_hash"`
	TelegramUserID pgtype.Int8        `json:"telegram_user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	AttemptCount   int32              `json:"attempt_count"`
	MaxAttempts    int32              `json:"max_attempts"`
	RequestIpHash  pgtype.Text        `json:"request_ip_hash"`
	UserAgentHash  pgtype.Text        `json:"user_agent_hash"`
}

// Short-lived server-side reset tokens minted after Telegram code and security answer verification.
type AuraPasswordResetTokens struct {
	TokenHash    string             `json:"token_hash"`
	ChallengeID  pgtype.UUID        `json:"challenge_id"`
	IdentityID   pgtype.UUID        `json:"identity_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	AttemptCount int32              `json:"attempt_count"`
	MaxAttempts  int32              `json:"max_attempts"`
}

// ask_user HITL pauses (Slice 1.5). Pending = resumed_at IS NULL. FIFO order: priority DESC, created_at ASC, token ASC.
type AuraPausedStates struct {
	Token              pgtype.UUID        `json:"token"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Kind               string             `json:"kind"`
	Question           string             `json:"question"`
	Options            []byte             `json:"options"`
	Priority           int32              `json:"priority"`
	ResumeContext      []byte             `json:"resume_context"`
	ToolCallID         string             `json:"tool_call_id"`
	ProxiedFromChildID pgtype.Text        `json:"proxied_from_child_id"`
	ProxiedToolCallID  pgtype.Text        `json:"proxied_tool_call_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ResumedAt          pgtype.Timestamptz `json:"resumed_at"`
	ResumedAnswer      []byte             `json:"resumed_answer"`
	// Owning identity (Phase 36, OQ2): a first-class column backfilled from the parent aura.conversations.identity_id so the plan-04 kernel-isolation / RLS owner filter keys on the row, not a subquery. NULLABLE until the plan-05 write path populates it.
	IdentityID pgtype.UUID `json:"identity_id"`
}

// Durable scheduler notification queue (Phase 19 H6/H7): quiet-hours deferred notifications and failed self-send retry state.
type AuraPendingNotifications struct {
	ID          pgtype.UUID        `json:"id"`
	RunID       pgtype.UUID        `json:"run_id"`
	NotifyRoute pgtype.Text        `json:"notify_route"`
	Body        string             `json:"body"`
	NotifyAfter pgtype.Timestamptz `json:"notify_after"`
	Attempts    int32              `json:"attempts"`
	LastError   pgtype.Text        `json:"last_error"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	// Stable owning identity snapshot (Phase 20, Fork 1): the channel-independent delivery key for the deferred/failed sweep route-back. Plain text, no FK — survives a deleted origin conversation. NULL for legacy/CLI rows → falls back to notify_route.
	IdentityID pgtype.Text `json:"identity_id"`
}

// Resumable provisioning/de-provisioning saga journal (Phase 36, D-14/D-27). MUTABLE: step status transitions pending -> done/failed for forward recovery. identity_id has NO FK so a de-provision saga survives the identity deletion it is executing.
type AuraProvisioningSaga struct {
	SagaID     pgtype.UUID        `json:"saga_id"`
	IdentityID pgtype.UUID        `json:"identity_id"`
	Kind       string             `json:"kind"`
	Step       string             `json:"step"`
	Status     string             `json:"status"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Scheduler task definitions (Slice 6 / Phase 10, amendment #46). Grammar triad at|every|cron with per-task IANA tz; next_run_at is UTC, recomputed in-zone (D-06/D-07).
type AuraSchedulerTasks struct {
	ID                   pgtype.UUID        `json:"id"`
	Kind                 string             `json:"kind"`
	ScheduleKind         string             `json:"schedule_kind"`
	CronExpr             pgtype.Text        `json:"cron_expr"`
	EveryMinutes         pgtype.Int4        `json:"every_minutes"`
	RunAt                pgtype.Timestamptz `json:"run_at"`
	Tz                   string             `json:"tz"`
	Payload              []byte             `json:"payload"`
	StepBudget           pgtype.Int4        `json:"step_budget"`
	Status               string             `json:"status"`
	NextRunAt            pgtype.Timestamptz `json:"next_run_at"`
	NotifyRoute          pgtype.Text        `json:"notify_route"`
	IdentityID           string             `json:"identity_id"`
	OriginConversationID pgtype.UUID        `json:"origin_conversation_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// Cockpit-editable runtime override layer for model-backend knobs (Settings page). MUTABLE (aura_app full DML). Overlaid onto the environment at boot by internal/settings (DB wins); applied on restart. is_secret rows are redacted in API GET responses.
type AuraSettings struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	IsSecret  bool               `json:"is_secret"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.Text        `json:"updated_by"`
}

// Append-only skill-mutation audit ledger (Slice 7c / Phase 11, D-29). aura_app has SELECT+INSERT only; UPDATE/DELETE raise via a row trigger and TRUNCATE via a statement trigger (Pitfall 1/6). The D-29 coherence CHECK constrains the approval tuple to five allowed events; content_hash is the D-23 recovery path on every row.
type AuraSkillAudit struct {
	ID             pgtype.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ActorID        string             `json:"actor_id"`
	IdentityID     string             `json:"identity_id"`
	SkillName      string             `json:"skill_name"`
	Action         string             `json:"action"`
	ContentHash    string             `json:"content_hash"`
	ApprovalSource pgtype.Text        `json:"approval_source"`
	// Historical ask_user pause token. Intentionally not a live FK: paused_states are ephemeral and may be cascade-deleted with their conversation while audit rows remain append-only.
	PausedStateToken  pgtype.UUID `json:"paused_state_token"`
	GateRecommended   bool        `json:"gate_recommended"`
	GateTaken         bool        `json:"gate_taken"`
	BlocklistOverride bool        `json:"blocklist_override"`
}

// Ledger of Garage/S3 objects owned by assets, documents, versions, and derived artifacts.
type AuraStorageObjects struct {
	ID             pgtype.UUID        `json:"id"`
	IdentityID     pgtype.UUID        `json:"identity_id"`
	DocumentID     pgtype.UUID        `json:"document_id"`
	VersionID      pgtype.UUID        `json:"version_id"`
	AssetID        pgtype.UUID        `json:"asset_id"`
	Bucket         string             `json:"bucket"`
	ObjectKey      string             `json:"object_key"`
	Kind           string             `json:"kind"`
	Sha1           string             `json:"sha1"`
	Sha256         string             `json:"sha256"`
	Etag           string             `json:"etag"`
	SizeBytes      int64              `json:"size_bytes"`
	ContentType    string             `json:"content_type"`
	RetentionClass string             `json:"retention_class"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

// Known Telegram accounts (Slice 9a / Phase 13, amendment #58). PK telegram_user_id; identity_id FKs aura.identities (single-user `local` this phase, D-07).
type AuraTelegramAccounts struct {
	TelegramUserID int64              `json:"telegram_user_id"`
	IdentityID     pgtype.UUID        `json:"identity_id"`
	Username       pgtype.Text        `json:"username"`
	FirstName      pgtype.Text        `json:"first_name"`
	AddedAt        pgtype.Timestamptz `json:"added_at"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
}

// Single-use onboarding tokens (Slice 9a / Phase 13, amendment #58). consumed_at marks the token spent (T-13-01-TokenReplay); expires_at is a 1h TTL; the partial active index keys the cleanup scan.
type AuraTelegramSetupPending struct {
	OnboardingToken string             `json:"onboarding_token"`
	IdentityID      pgtype.UUID        `json:"identity_id"`
	GeneratedBy     pgtype.Text        `json:"generated_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt      pgtype.Timestamptz `json:"consumed_at"`
}

// Append-only tool invocation ledger: start/end facts for dispatched tools with args, timestamps, status, bytes, sidecar path, exit code, and typed metadata.
type AuraToolInvocations struct {
	ID                pgtype.UUID        `json:"id"`
	ConversationID    pgtype.UUID        `json:"conversation_id"`
	RequestID         pgtype.UUID        `json:"request_id"`
	ToolCallID        string             `json:"tool_call_id"`
	ToolName          string             `json:"tool_name"`
	EventKind         string             `json:"event_kind"`
	Seq               int32              `json:"seq"`
	Ts                pgtype.Timestamptz `json:"ts"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	EndedAt           pgtype.Timestamptz `json:"ended_at"`
	DurationMs        pgtype.Int8        `json:"duration_ms"`
	ArgsRaw           pgtype.Text        `json:"args_raw"`
	ArgsBytes         pgtype.Int4        `json:"args_bytes"`
	Status            pgtype.Text        `json:"status"`
	Error             pgtype.Text        `json:"error"`
	ResultPreview     pgtype.Text        `json:"result_preview"`
	PreviewBytes      pgtype.Int4        `json:"preview_bytes"`
	ResultBytes       pgtype.Int4        `json:"result_bytes"`
	ResultTruncated   pgtype.Bool        `json:"result_truncated"`
	ResultSidecarPath pgtype.Text        `json:"result_sidecar_path"`
	ExitCode          pgtype.Int4        `json:"exit_code"`
	Meta              []byte             `json:"meta"`
}
