// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPendingNotification = `-- name: InsertPendingNotification :one
INSERT INTO aura.pending_notifications (
    id, run_id, notify_route, body, notify_after, attempts, last_error, status,
    identity_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, run_id, notify_route, body, notify_after, attempts, last_error,
    status, created_at, updated_at, identity_id
`

type InsertPendingNotificationParams struct {
	ID          pgtype.UUID        `json:"id"`
	RunID       pgtype.UUID        `json:"run_id"`
	NotifyRoute pgtype.Text        `json:"notify_route"`
	Body        string             `json:"body"`
	NotifyAfter pgtype.Timestamptz `json:"notify_after"`
	Attempts    int32              `json:"attempts"`
	LastError   pgtype.Text        `json:"last_error"`
	Status      string             `json:"status"`
	IdentityID  pgtype.Text        `json:"identity_id"`
}

func (q *Queries) InsertPendingNotification(ctx context.Context, arg InsertPendingNotificationParams) (AuraPendingNotifications, error) {
	row := q.db.QueryRow(ctx, insertPendingNotification,
		arg.ID,
		arg.RunID,
		arg.NotifyRoute,
		arg.Body,
		arg.NotifyAfter,
		arg.Attempts,
		arg.LastError,
		arg.Status,
		arg.IdentityID,
	)
	var i AuraPendingNotifications
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.NotifyRoute,
		&i.Body,
		&i.NotifyAfter,
		&i.Attempts,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityID,
	)
	return i, err
}

const markNotificationDelivered = `-- name: MarkNotificationDelivered :exec
UPDATE aura.pending_notifications
SET status = 'delivered', updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkNotificationDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationDelivered, id)
	return err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE aura.pending_notifications
SET status = 'failed',
    attempts = attempts + 1,
    last_error = $2,
    updated_at = now()
WHERE id = $1
`

type MarkNotificationFailedParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.ID, arg.LastError)
	return err
}

const sweepDueNotifications = `-- name: SweepDueNotifications :many
SELECT id, run_id, notify_route, body, notify_after, attempts, last_error,
    status, created_at, updated_at, identity_id
FROM aura.pending_notifications
WHERE (status = 'pending' AND notify_after <= now())
   OR (status = 'failed' AND attempts < $1)
ORDER BY notify_after ASC, created_at ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type SweepDueNotificationsParams struct {
	Attempts int32 `json:"attempts"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) SweepDueNotifications(ctx context.Context, arg SweepDueNotificationsParams) ([]AuraPendingNotifications, error) {
	rows, err := q.db.Query(ctx, sweepDueNotifications, arg.Attempts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraPendingNotifications{}
	for rows.Next() {
		var i AuraPendingNotifications
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.NotifyRoute,
			&i.Body,
			&i.NotifyAfter,
			&i.Attempts,
			&i.LastError,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdentityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
