// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPendingNotification = `-- name: InsertPendingNotification :one
INSERT INTO aura.pending_notifications (
    id, run_id, notify_route, body, notify_after, attempts, last_error, status,
    identity_id, steer_queue_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, run_id, notify_route, body, notify_after, attempts, last_error,
    status, created_at, updated_at, identity_id, steer_queue_id
`

type InsertPendingNotificationParams struct {
	ID           pgtype.UUID        `json:"id"`
	RunID        pgtype.UUID        `json:"run_id"`
	NotifyRoute  string             `json:"notify_route"`
	Body         string             `json:"body"`
	NotifyAfter  pgtype.Timestamptz `json:"notify_after"`
	Attempts     int32              `json:"attempts"`
	LastError    pgtype.Text        `json:"last_error"`
	Status       string             `json:"status"`
	IdentityID   string             `json:"identity_id"`
	SteerQueueID pgtype.UUID        `json:"steer_queue_id"`
}

// Exactly one of run_id / steer_queue_id owns the row (migration 0109). Route and
// identity are mandatory snapshots; cron.Store mirrors all three invariants before the
// round trip.
func (q *Queries) InsertPendingNotification(ctx context.Context, arg InsertPendingNotificationParams) (AuraPendingNotifications, error) {
	row := q.db.QueryRow(ctx, insertPendingNotification,
		arg.ID,
		arg.RunID,
		arg.NotifyRoute,
		arg.Body,
		arg.NotifyAfter,
		arg.Attempts,
		arg.LastError,
		arg.Status,
		arg.IdentityID,
		arg.SteerQueueID,
	)
	var i AuraPendingNotifications
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.NotifyRoute,
		&i.Body,
		&i.NotifyAfter,
		&i.Attempts,
		&i.LastError,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityID,
		&i.SteerQueueID,
	)
	return i, err
}

const markNotificationDelivered = `-- name: MarkNotificationDelivered :exec
UPDATE aura.pending_notifications
SET status = 'delivered', updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkNotificationDelivered(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationDelivered, id)
	return err
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE aura.pending_notifications
SET status = 'failed',
    attempts = attempts + 1,
    last_error = $2,
    updated_at = now()
WHERE id = $1
`

type MarkNotificationFailedParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.ID, arg.LastError)
	return err
}

const sweepDueNotifications = `-- name: SweepDueNotifications :many
SELECT n.id, n.run_id, n.notify_route, n.body, n.notify_after, n.attempts, n.last_error,
    n.status, n.created_at, n.updated_at, n.identity_id, n.steer_queue_id,
    COALESCE(t.origin_conversation_id::text, s.conversation_id, '') AS origin_conversation_id
FROM aura.pending_notifications AS n
LEFT JOIN aura.agent_job_runs AS r ON r.id = n.run_id
LEFT JOIN aura.scheduler_tasks AS t ON t.id = r.task_id
LEFT JOIN aura.steer_queue AS s ON s.id = n.steer_queue_id
WHERE (n.status = 'pending' AND n.notify_after <= now())
   OR (n.status = 'failed' AND n.attempts < $1)
ORDER BY n.notify_after ASC, n.created_at ASC
LIMIT $2
FOR UPDATE OF n SKIP LOCKED
`

type SweepDueNotificationsParams struct {
	Attempts int32 `json:"attempts"`
	Limit    int32 `json:"limit"`
}

type SweepDueNotificationsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	RunID                pgtype.UUID        `json:"run_id"`
	NotifyRoute          string             `json:"notify_route"`
	Body                 string             `json:"body"`
	NotifyAfter          pgtype.Timestamptz `json:"notify_after"`
	Attempts             int32              `json:"attempts"`
	LastError            pgtype.Text        `json:"last_error"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	IdentityID           string             `json:"identity_id"`
	SteerQueueID         pgtype.UUID        `json:"steer_queue_id"`
	OriginConversationID string             `json:"origin_conversation_id"`
}

func (q *Queries) SweepDueNotifications(ctx context.Context, arg SweepDueNotificationsParams) ([]SweepDueNotificationsRow, error) {
	rows, err := q.db.Query(ctx, sweepDueNotifications, arg.Attempts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SweepDueNotificationsRow{}
	for rows.Next() {
		var i SweepDueNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.NotifyRoute,
			&i.Body,
			&i.NotifyAfter,
			&i.Attempts,
			&i.LastError,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdentityID,
			&i.SteerQueueID,
			&i.OriginConversationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
