// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	ListAppliedKnowledgeMigrations(ctx context.Context) ([]AuraKnowledgeMigrations, error)
	RecordKnowledgeMigration(ctx context.Context, arg RecordKnowledgeMigrationParams) error
}

var _ Querier = (*Queries)(nil)
