// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AggregateCacheMetricsSince(ctx context.Context, since pgtype.Timestamptz) (AggregateCacheMetricsSinceRow, error)
	// Flip a pending_approval task to active (the cockpit approval, parity with the CLI
	// `aura task approve`). Returns rows affected so the caller distinguishes a hit (1) from
	// a task that is not awaiting approval (0).
	ApproveTaskRow(ctx context.Context, id pgtype.UUID) (int64, error)
	// First apply only: commit the freshly rebuilt plan authorization before any
	// item can be claimed. A crash after this transition resumes persisted items
	// without re-authorizing against a possibly changed global candidate set.
	AuthorizeRetentionOperation(ctx context.Context, arg AuthorizeRetentionOperationParams) (int64, error)
	AutoResolvePendingForConversation(ctx context.Context, arg AutoResolvePendingForConversationParams) error
	BenchmarkSettingsOverrideExpired(ctx context.Context, runID pgtype.UUID) (bool, error)
	BindPipelineJobCandidate(ctx context.Context, arg BindPipelineJobCandidateParams) (BindPipelineJobCandidateRow, error)
	CancelTask(ctx context.Context, id pgtype.UUID) error
	// D-09 (CHAT-05): the leaf (deepest) seq of a conversation's canonical branch — the
	// all-zero sentinel branch every pre-0017 turn is backfilled onto. For a non-branched
	// conversation this is just MAX(seq), so a branch-path walk from this leaf reconstructs
	// the same linear history ListTurnsBySeq returns (byte-identity, store.go:250). Returns
	// 0 when the conversation has no turns.
	CanonicalBranchLeafSeq(ctx context.Context, conversationID pgtype.UUID) (int32, error)
	CaptureBenchmarkSetting(ctx context.Context, arg CaptureBenchmarkSettingParams) error
	ClaimConversationDeleteTeardown(ctx context.Context, arg ClaimConversationDeleteTeardownParams) (int64, error)
	ClaimIngestionJobs(ctx context.Context, arg ClaimIngestionJobsParams) ([]ClaimIngestionJobsRow, error)
	ClaimRetentionItems(ctx context.Context, arg ClaimRetentionItemsParams) ([]AuraRetentionOperationItems, error)
	CleanupResumedOlderThan(ctx context.Context, resumedAt pgtype.Timestamptz) error
	ClearExpiredReplayBody(ctx context.Context, arg ClearExpiredReplayBodyParams) (int64, error)
	CompleteBenchmarkSettingsOverride(ctx context.Context, arg CompleteBenchmarkSettingsOverrideParams) (int64, error)
	CompleteOperation(ctx context.Context, arg CompleteOperationParams) (int64, error)
	CompleteRun(ctx context.Context, arg CompleteRunParams) error
	ConsumePasswordResetChallenge(ctx context.Context, id pgtype.UUID) (AuraPasswordResetChallenges, error)
	ConsumePasswordResetToken(ctx context.Context, tokenHash string) (AuraPasswordResetTokens, error)
	// ConsumeTelegramSetupPending atomically marks an unconsumed, unexpired token as
	// consumed and returns it. The consumed_at IS NULL guard makes the consume
	// single-use: a second consume of the same token matches no row (RETURNING is
	// empty → sql.ErrNoRows / pgx.ErrNoRows → ErrTokenConsumed). The expires_at guard
	// rejects a stale token in the same statement.
	ConsumeTelegramSetupPending(ctx context.Context, onboardingToken string) (AuraTelegramSetupPending, error)
	// A reservation cannot be replaced or released after teardown starts. Once its exact
	// row is absent, the worker holding that reservation committed the terminal delete.
	ConversationDeleteCompleted(ctx context.Context, arg ConversationDeleteCompletedParams) (bool, error)
	CountBenchmarkSettingsOverrideRows(ctx context.Context, runID pgtype.UUID) (int32, error)
	CountBenchmarkSettingsRestoreMismatches(ctx context.Context, runID pgtype.UUID) (int32, error)
	CountConversationsForIdentityPurge(ctx context.Context, identityID pgtype.UUID) (int64, error)
	CountIngestionJobsByStatus(ctx context.Context, arg CountIngestionJobsByStatusParams) (int64, error)
	// Current durable work that has not reached a terminal completed/failed item state.
	// This query owns the restart-safe backlog gauge; transition counters are not state.
	CountRetentionBacklog(ctx context.Context) (int64, error)
	CountTelegramAccounts(ctx context.Context) (int64, error)
	CountTurns(ctx context.Context, conversationID pgtype.UUID) (int64, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (AuraAssets, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (AuraConversations, error)
	// Get-or-create by source, refusing a document left mid-delete.
	// DO UPDATE rather than DO NOTHING because :one needs a row back, and it touches ONLY
	// updated_at: re-ingesting a file must not overwrite a title or tags the operator edited,
	// and aura.document_identity_immutable raises 23514 on any write to identity, source,
	// search id, or a lowered pipeline_generation. The status guard outlives the asynchronous
	// delete workflow it was written for: no statement here sets 'deleting' any more, but rows
	// the retired workflow stranded in that state are still on disk, and joining one would
	// hand the caller a document whose bytes are half gone. Zero rows is that case, and the
	// caller turns it into ErrDocumentDeleteInFlight.
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (AuraDocuments, error)
	// Legacy queue kept owner-scoped during retirement. New ingress uses aura.ingestion_jobs.
	CreateDocumentIngestJob(ctx context.Context, arg CreateDocumentIngestJobParams) (AuraDocumentIngestJobs, error)
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (AuraIdentities, error)
	CreateIngestionJob(ctx context.Context, arg CreateIngestionJobParams) (AuraIngestionJobs, error)
	CreateRetentionItem(ctx context.Context, arg CreateRetentionItemParams) (AuraRetentionOperationItems, error)
	CreateRetentionOperation(ctx context.Context, arg CreateRetentionOperationParams) (AuraRetentionOperations, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (AuraSchedulerTasks, error)
	DeleteConversation(ctx context.Context, id pgtype.UUID) error
	// Owner-scoped hard delete (Phase 36 MUSR-01 / D-06): affects a row ONLY when the caller
	// owns it. rows-affected==0 lets the handler split 403 (a known-foreign id) from 404.
	DeleteConversationForIdentity(ctx context.Context, arg DeleteConversationForIdentityParams) (int64, error)
	DeleteConversationForIdentityIfReservation(ctx context.Context, arg DeleteConversationForIdentityIfReservationParams) (int64, error)
	DeleteConversationsForIdentityPurge(ctx context.Context, identityID pgtype.UUID) (int64, error)
	DeleteDocumentTags(ctx context.Context, documentID pgtype.UUID) error
	DeleteExpiredTelegramSetupPending(ctx context.Context) (int64, error)
	DeleteExpiredVerificationEvents(ctx context.Context, createdAt pgtype.Timestamptz) error
	// Retention, mirroring the original's two-branch prune: state that was edited before
	// the cutoff, and state whose only anchor is an event older than the cutoff.
	DeleteExpiredVerificationState(ctx context.Context, lastEditAt pgtype.Timestamptz) error
	DeleteIdentity(ctx context.Context, name string) error
	DeleteSetting(ctx context.Context, key string) error
	// Bound ledger growth per session+root, keeping the newest $4 events. The row the
	// state points at survives because it is always among the newest.
	DeleteSupersededVerificationEvents(ctx context.Context, arg DeleteSupersededVerificationEventsParams) error
	// Claim correctness is held by the per-task pg_try_advisory_lock (claim.go), NOT a
	// row lock here: this SELECT runs on the autocommit pool, so any FOR UPDATE SKIP
	// LOCKED would release the instant the SELECT returns (inert, L5). The advisory lock
	// is what makes each due task a singleton across concurrent workers.
	DueTasks(ctx context.Context, limit int32) ([]AuraSchedulerTasks, error)
	FailRetentionItem(ctx context.Context, arg FailRetentionItemParams) (int64, error)
	FinalizeRetentionItem(ctx context.Context, arg FinalizeRetentionItemParams) (int64, error)
	FinalizeRetentionOperation(ctx context.Context, arg FinalizeRetentionOperationParams) (AuraRetentionOperations, error)
	GetActivePasswordResetChallenge(ctx context.Context, identityID pgtype.UUID) (AuraPasswordResetChallenges, error)
	GetAsset(ctx context.Context, id pgtype.UUID) (AuraAssets, error)
	GetAssetForIdentity(ctx context.Context, arg GetAssetForIdentityParams) (AuraAssets, error)
	GetConversation(ctx context.Context, id pgtype.UUID) (AuraConversations, error)
	// Owner-scoped single-conversation read (Phase 36 MUSR-01 / D-06): GetConversation with
	// an identity_id owner predicate. A miss is the caller's 404 (read hides existence).
	// Routed through db.WithIdentityTx so the RLS owner policy backstops a forgotten filter.
	GetConversationForIdentity(ctx context.Context, arg GetConversationForIdentityParams) (AuraConversations, error)
	// The input_tokens of the most recent request-bearing turn = the CURRENT
	// context-window fill (distinct from the cumulative total_input_tokens column,
	// which sums every turn's input and so climbs far past the window on a long
	// chat). The runtime footer's context gauge reads this so a reloaded
	// conversation shows real fill, not the lifetime sum. COALESCE => 0 when the
	// conversation has no request-bearing turn yet.
	GetConversationLastInputTokens(ctx context.Context, conversationID pgtype.UUID) (int32, error)
	GetConversationVersionForIdentity(ctx context.Context, arg GetConversationVersionForIdentityParams) (int64, error)
	GetDocument(ctx context.Context, arg GetDocumentParams) (AuraDocuments, error)
	GetDocumentBySearchID(ctx context.Context, arg GetDocumentBySearchIDParams) (AuraDocuments, error)
	GetDocumentIngestJob(ctx context.Context, arg GetDocumentIngestJobParams) (AuraDocumentIngestJobs, error)
	GetDocumentIngestJobByDocumentID(ctx context.Context, arg GetDocumentIngestJobByDocumentIDParams) (AuraDocumentIngestJobs, error)
	GetIdentityByID(ctx context.Context, id pgtype.UUID) (AuraIdentities, error)
	GetIdentityByName(ctx context.Context, name string) (AuraIdentities, error)
	GetIdentityRecoveryByIdentity(ctx context.Context, identityID pgtype.UUID) (AuraIdentityRecovery, error)
	GetOpenBenchmarkSettingsOverride(ctx context.Context) (AuraBenchmarkSettingsOverrides, error)
	GetOperation(ctx context.Context, arg GetOperationParams) (GetOperationRow, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (AuraPasswordResetTokens, error)
	GetPausedStateByToken(ctx context.Context, token pgtype.UUID) (AuraPausedStates, error)
	// Owner-scoped single-pause read (Phase 36 MUSR-01 / D-06): the same projection as
	// GetPausedStateByToken with an identity_id owner predicate. A miss (unknown token OR a
	// token owned by another identity) is the caller's 404/403 signal. Run through
	// db.WithIdentityTx so the RLS owner policy backstops a forgotten filter.
	GetPausedStateByTokenForIdentity(ctx context.Context, arg GetPausedStateByTokenForIdentityParams) (AuraPausedStates, error)
	GetRetentionItem(ctx context.Context, id pgtype.UUID) (AuraRetentionOperationItems, error)
	GetRetentionOperationByToken(ctx context.Context, token string) (AuraRetentionOperations, error)
	GetRun(ctx context.Context, id pgtype.UUID) (AuraAgentJobRuns, error)
	GetSetting(ctx context.Context, key string) (AuraSettings, error)
	GetTask(ctx context.Context, id pgtype.UUID) (AuraSchedulerTasks, error)
	GetTelegramAccountByIdentity(ctx context.Context, identityID pgtype.UUID) (AuraTelegramAccounts, error)
	GetTelegramAccountByTelegramID(ctx context.Context, telegramUserID int64) (AuraTelegramAccounts, error)
	GetTelegramSetupPending(ctx context.Context, onboardingToken string) (AuraTelegramSetupPending, error)
	GetToolInvocationEnd(ctx context.Context, arg GetToolInvocationEndParams) (AuraToolInvocations, error)
	// D-09 (CHAT-05): a turn's own branch/parent pointers, used by the fork path to read the
	// diverging turn's parent_seq (the new sibling chains off the SAME parent so it replaces
	// the diverging turn rather than appending after it). Returns pgx.ErrNoRows when the seq
	// is absent (mapped to a clean 404 at the boundary).
	GetTurnPointers(ctx context.Context, arg GetTurnPointersParams) (GetTurnPointersRow, error)
	GetVerificationState(ctx context.Context, arg GetVerificationStateParams) (GetVerificationStateRow, error)
	GrantCapability(ctx context.Context, arg GrantCapabilityParams) error
	HasCapability(ctx context.Context, arg HasCapabilityParams) (bool, error)
	HeartbeatBenchmarkSettingsOverride(ctx context.Context, arg HeartbeatBenchmarkSettingsOverrideParams) (int64, error)
	HeartbeatIngestionJob(ctx context.Context, arg HeartbeatIngestionJobParams) (AuraIngestionJobs, error)
	IncrementPasswordResetChallengeAttempts(ctx context.Context, id pgtype.UUID) error
	IncrementPasswordResetTokenAttempts(ctx context.Context, tokenHash string) error
	InsertAssetEvent(ctx context.Context, arg InsertAssetEventParams) error
	InsertBenchmarkSettingsOverride(ctx context.Context, arg InsertBenchmarkSettingsOverrideParams) (AuraBenchmarkSettingsOverrides, error)
	// Idempotent on (conversation_id, seq): the metric write is a separate, non-transactional
	// observation following the assistant turn (runner_persist.go). ON CONFLICT DO NOTHING
	// makes a re-run for an already-recorded turn a no-op rather than a PK violation or a
	// duplicate, so a retry after a transient failure can never double-count the metric (WR-03).
	InsertCacheMetric(ctx context.Context, arg InsertCacheMetricParams) error
	InsertContextRotEvent(ctx context.Context, arg InsertContextRotEventParams) error
	// parent_seq maintains the canonical leaf->root chain the branch walk recurses on
	// (ListRecentTurnsByBranchPath joins `t.seq = p.parent_seq`). It is derived here rather
	// than bound as a parameter so no call site can forget it — which is exactly what
	// happened: 0017 added the column, backfilled `seq - 1` for the rows present at
	// migration time, and gave it no default, so EVERY turn appended since carried NULL. A
	// NULL breaks the join, so a forked branch reconstructed to the forked turn ALONE —
	// measured 2026-08-13 against the live schema, one turn, not even the system head — and
	// the model lost the whole prior conversation on any edit/regenerate.
	// NULLIF keeps seq=1 (the root) at NULL, matching that backfill's `WHERE seq > 1`.
	InsertConversationTurn(ctx context.Context, arg InsertConversationTurnParams) error
	InsertIdentityAudit(ctx context.Context, arg InsertIdentityAuditParams) (AuraIdentityAudit, error)
	InsertIdentityRecoveryAudit(ctx context.Context, arg InsertIdentityRecoveryAuditParams) (AuraIdentityRecoveryAudit, error)
	InsertMcpAudit(ctx context.Context, arg InsertMcpAuditParams) (AuraMcpAudit, error)
	InsertPasswordResetChallenge(ctx context.Context, arg InsertPasswordResetChallengeParams) (AuraPasswordResetChallenges, error)
	InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) (AuraPasswordResetTokens, error)
	InsertPausedState(ctx context.Context, arg InsertPausedStateParams) error
	InsertPendingNotification(ctx context.Context, arg InsertPendingNotificationParams) (AuraPendingNotifications, error)
	InsertRun(ctx context.Context, arg InsertRunParams) (AuraAgentJobRuns, error)
	InsertSkillAudit(ctx context.Context, arg InsertSkillAuditParams) (AuraSkillAudit, error)
	InsertTelegramAccount(ctx context.Context, arg InsertTelegramAccountParams) (AuraTelegramAccounts, error)
	InsertTelegramSetupPending(ctx context.Context, arg InsertTelegramSetupPendingParams) error
	InsertToolInvocation(ctx context.Context, arg InsertToolInvocationParams) (int64, error)
	// Coding verification evidence ledger (migration 0094).
	//
	// Ported from NousResearch/hermes-agent `agent/verification_evidence.py` (MIT), whose
	// store is SQLite. The statements below are the same operations against Postgres; the
	// invariant they maintain is the module's whole point:
	//
	//   a passing verification event CLEARS last_edit_at;
	//   an edit SETS it;
	//   so "was this workspace edited after its last passing verification" is one column.
	InsertVerificationEvent(ctx context.Context, arg InsertVerificationEventParams) (InsertVerificationEventRow, error)
	ListActiveTasks(ctx context.Context) ([]AuraSchedulerTasks, error)
	// Cross-thread pending list (APRV-01 / D-04): the same SELECT as
	// ListPendingPausedStates with NO conversation_id filter, so the approval center
	// can aggregate every still-pending pause across ALL conversations. KEEPS the
	// mandatory total-order tiebreaker (priority DESC, created_at ASC, token ASC) —
	// `token ASC` is non-negotiable because tx-batched rows share created_at = now()
	// (RESEARCH Pitfall 4 / askuser/store.go:158-160), so without it the order would
	// be non-deterministic. LIMIT $1 caps the scan (a single operator's pending set is
	// tiny; no new index is warranted — RESEARCH A4).
	ListAllPendingPausedStates(ctx context.Context, limit int32) ([]AuraPausedStates, error)
	// Owner-scoped cross-thread pending list (Phase 36 MUSR-01 / APRV-01): ListAllPendingPausedStates
	// restricted to one identity's pauses. Same total order (priority DESC, created_at ASC, token ASC).
	ListAllPendingPausedStatesForIdentity(ctx context.Context, arg ListAllPendingPausedStatesForIdentityParams) ([]AuraPausedStates, error)
	ListAssetsForLibrary(ctx context.Context, arg ListAssetsForLibraryParams) ([]AuraAssets, error)
	ListAssetsForThread(ctx context.Context, arg ListAssetsForThreadParams) ([]AuraAssets, error)
	// Amendment #91 (fix-plan 1.12) display-only read: the reasoning columns for every
	// answer-shaped assistant turn (no tool_calls payload), ordered by seq. Deliberately
	// SEPARATE from ListTurnsBySeq so the llm.Message history rebuild can never select
	// reasoning. Scope mirrors ListTurnsBySeq exactly (conversation-wide, no branch
	// filter) so the snapshot merge pairs positionally with the LoadHistory projection.
	// The tool_calls filter mirrors turnToMessage's Go semantics: rows whose tool_calls
	// decode to zero calls ('[]'/'null') count as answer-shaped there too.
	ListAssistantTurnReasoning(ctx context.Context, conversationID pgtype.UUID) ([]ListAssistantTurnReasoningRow, error)
	// D-09 (CHAT-05): the navigable branch set. A leaf is a turn that is NOT the parent of
	// any other turn (no row's parent_seq points at it) — i.e. the tip of a branch path. The
	// BranchPicker navigates among these sibling leaves; a re-run continues over the selected
	// leaf's path (ListTurnsByBranchPath). Ordered by branch_id then seq so the canonical
	// (all-zero) branch sorts first and the order is stable across calls.
	ListBranchLeaves(ctx context.Context, conversationID pgtype.UUID) ([]ListBranchLeavesRow, error)
	ListCacheMetricsSince(ctx context.Context, since pgtype.Timestamptz) ([]AuraCacheMetrics, error)
	ListCapabilities(ctx context.Context, identityID pgtype.UUID) ([]AuraCapabilityGrants, error)
	ListContextRotEvents(ctx context.Context, conversationID pgtype.UUID) ([]AuraContextRotEvents, error)
	ListConversationIDsForIdentityPurge(ctx context.Context, identityID pgtype.UUID) ([]pgtype.UUID, error)
	ListConversations(ctx context.Context, includeArchived bool) ([]AuraConversations, error)
	// Owner-scoped conversation list (Phase 36 MUSR-01): ListConversations restricted to one
	// identity. identity_id is NOT NULL (0005) so every conversation is attributable.
	ListConversationsForIdentity(ctx context.Context, arg ListConversationsForIdentityParams) ([]AuraConversations, error)
	ListDocumentVersions(ctx context.Context, arg ListDocumentVersionsParams) ([]AuraDocumentVersions, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]AuraDocuments, error)
	// fix-plan 1.7 / Amendment #92 (REVISED): the per-tick approval-reminder sweep. Every
	// pending_approval task with an ORIGIN CONVERSATION whose throttle stamp is due (never
	// reminded, or older than the cadence cutoff computed in Go: now() -
	// AURA_SCHEDULER_APPROVAL_REMINDER_SEC). The old identity_id NOT IN ('','local') filter is
	// DROPPED: WebUI/local-origin rows MUST be selected so the sweep can MINT their pause (they
	// surface via the pull /api/approvals; the Telegram push is simply a no-op for them). Rows
	// with a NULL origin_conversation_id (CLI-origin, no conversation to key a pause on) are
	// excluded and keep the `aura task approve` CLI path. No FOR UPDATE SKIP LOCKED: the sweep
	// runs on the autocommit pool (like DueTasks) where a row lock releases the instant the
	// SELECT returns (inert). The dedup is the approval_reminded_at throttle stamp, not a row
	// lock; a rare cross-instance double-nudge under HA is benign.
	ListDuePendingApprovalReminders(ctx context.Context, arg ListDuePendingApprovalRemindersParams) ([]AuraSchedulerTasks, error)
	ListExpiredReplayBodies(ctx context.Context, arg ListExpiredReplayBodiesParams) ([]ListExpiredReplayBodiesRow, error)
	ListIdentities(ctx context.Context) ([]AuraIdentities, error)
	ListIdentityAudit(ctx context.Context, arg ListIdentityAuditParams) ([]AuraIdentityAudit, error)
	ListInFlightToolInvocationsBefore(ctx context.Context, startedAt pgtype.Timestamptz) ([]AuraToolInvocations, error)
	// The cockpit scheduler board (GOV-03 write): active AND pending_approval tasks, so an
	// operator can approve a gated task on-screen. Ordered by next fire (pending rows have a
	// non-null next_run_at too — it is the first fire computed at schedule time).
	ListManageableTasks(ctx context.Context) ([]AuraSchedulerTasks, error)
	ListMcpAudit(ctx context.Context, arg ListMcpAuditParams) ([]AuraMcpAudit, error)
	ListPendingPausedStates(ctx context.Context, conversationID pgtype.UUID) ([]AuraPausedStates, error)
	ListRecentDocumentIngestJobs(ctx context.Context, arg ListRecentDocumentIngestJobsParams) ([]AuraDocumentIngestJobs, error)
	ListRecentPausedStates(ctx context.Context, limit int32) ([]AuraPausedStates, error)
	// Managed branch-history query: cap recursive parent traversal itself, then add the
	// protected system head in a separate O(1) lookup. This keeps branch reconstruction
	// bounded without losing messages[0].
	ListRecentTurnsByBranchPath(ctx context.Context, arg ListRecentTurnsByBranchPathParams) ([]ListRecentTurnsByBranchPathRow, error)
	// Managed-history query: retain the earliest system head plus only the newest rows
	// that fit the declared aggregate hard cap. The database, sidecar reads, and tokenizer
	// therefore all see O(hard_cap) rows instead of every turn ever persisted.
	ListRecentTurnsBySeq(ctx context.Context, arg ListRecentTurnsBySeqParams) ([]ListRecentTurnsBySeqRow, error)
	ListReservedConversationDeletes(ctx context.Context, arg ListReservedConversationDeletesParams) ([]ListReservedConversationDeletesRow, error)
	ListRunsForTask(ctx context.Context, arg ListRunsForTaskParams) ([]AuraAgentJobRuns, error)
	ListSettings(ctx context.Context) ([]AuraSettings, error)
	ListSkillAudit(ctx context.Context, arg ListSkillAuditParams) ([]AuraSkillAudit, error)
	ListSkillAuditByName(ctx context.Context, skillName string) ([]AuraSkillAudit, error)
	// D-09 (LOOP-09): every seq whose content spilled to a <seq>.content sidecar
	// (content_sidecar_path IS NOT NULL) in one conversation. The crash-orphan GC
	// (orphan_scan.go) reconciles the live .content files against this referenced
	// set, so no ORDER BY is needed. Read-only — no schema change (D-07 holds).
	ListSpilledSeqsForConversation(ctx context.Context, conversationID pgtype.UUID) ([]int32, error)
	// The only storage-object statement Go still issues. The ledger's one writer travels with
	// the row it belongs to — ReservePipelineCandidateVersion inserts the object as part of
	// reserving the version that owns those bytes — so it has no standalone query to call.
	ListStorageObjects(ctx context.Context, arg ListStorageObjectsParams) ([]AuraStorageObjects, error)
	ListTelegramAccounts(ctx context.Context) ([]AuraTelegramAccounts, error)
	ListToolInvocationsByConversation(ctx context.Context, conversationID pgtype.UUID) ([]AuraToolInvocations, error)
	// D-09 (CHAT-05): the deterministic leaf->root path walk. Given a selected leaf seq,
	// follow parent_seq up to the root, then return the turns in root->leaf (seq ASC) order
	// so the head (system seq=1 + the always-block) is byte-identical to the linear case —
	// only the body turns differ per branch (Pitfall 3 rule 1). The column list MIRRORS
	// ListTurnsBySeq exactly so turnFromRow rehydrates it unchanged. A leaf seq of 0 (or one
	// not present) yields an empty path. Walk terminates at parent_seq IS NULL (the root).
	ListTurnsByBranchPath(ctx context.Context, arg ListTurnsByBranchPathParams) ([]ListTurnsByBranchPathRow, error)
	ListTurnsBySeq(ctx context.Context, conversationID pgtype.UUID) ([]ListTurnsBySeqRow, error)
	LockConversationForTurnAppend(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// This must run on transaction-bound Queries because autocommit releases the row lock when the statement returns.
	LockOperationReceipt(ctx context.Context, arg LockOperationReceiptParams) (LockOperationReceiptRow, error)
	LookupRecoveryByEmail(ctx context.Context, email string) (LookupRecoveryByEmailRow, error)
	ManualRetryIngestionJob(ctx context.Context, arg ManualRetryIngestionJobParams) (ManualRetryIngestionJobRow, error)
	// Stamp the throttle after a reminder ATTEMPT (delivered or not) so a pending approval
	// re-nudges at most once per cadence and a failing channel cannot spam the tick.
	MarkApprovalReminded(ctx context.Context, id pgtype.UUID) error
	MarkAssetDeleted(ctx context.Context, arg MarkAssetDeletedParams) (AuraAssets, error)
	MarkBenchmarkSettingsOverrideRestoring(ctx context.Context, runID pgtype.UUID) (int64, error)
	MarkNotificationDelivered(ctx context.Context, id pgtype.UUID) error
	MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error
	MarkOperationIndeterminate(ctx context.Context, arg MarkOperationIndeterminateParams) (int64, error)
	MarkOperationRejected(ctx context.Context, arg MarkOperationRejectedParams) (int64, error)
	MarkPausedStateResumed(ctx context.Context, arg MarkPausedStateResumedParams) (int64, error)
	MarkUnknownRecovery(ctx context.Context, id pgtype.UUID) error
	NextAssetEventSeq(ctx context.Context, assetID pgtype.UUID) (int32, error)
	NextConversationTurnSeq(ctx context.Context, conversationID pgtype.UUID) (int32, error)
	PromoteAssetToLibrary(ctx context.Context, arg PromoteAssetToLibraryParams) (AuraAssets, error)
	RecordRetentionArtifactResult(ctx context.Context, arg RecordRetentionArtifactResultParams) (int64, error)
	// A byte-identical deterministic plan receives a fresh authorization window only
	// while it has not crossed the first-apply durability boundary. In-flight and
	// terminal operations are immutable replays of their original snapshot.
	RefreshPlannedRetentionOperation(ctx context.Context, arg RefreshPlannedRetentionOperationParams) (int64, error)
	ReleaseConversationDeleteLease(ctx context.Context, arg ReleaseConversationDeleteLeaseParams) (int64, error)
	ReleaseReservedConversationDelete(ctx context.Context, arg ReleaseReservedConversationDeleteParams) (int64, error)
	RenameConversation(ctx context.Context, arg RenameConversationParams) error
	// Owner-scoped rename (Phase 36 MUSR-01 / D-06). rows-affected==0 drives the 403-vs-404 split.
	RenameConversationForIdentity(ctx context.Context, arg RenameConversationForIdentityParams) (int64, error)
	// Cross-process export-delete fence. This must commit before any runtime teardown.
	// Reusing the same deterministic reservation is idempotent after a process retry.
	ReserveConversationDeleteForIdentityIfVersion(ctx context.Context, arg ReserveConversationDeleteForIdentityIfVersionParams) (int64, error)
	// Reserves the version that owns these exact bytes AND writes the asset's storage-object
	// ledger row AND binds the asset to the resulting document+version -- in one statement.
	//
	// One statement rather than four because the four could interleave: a repeat upload of
	// identical bytes would create a fresh raw object and then attach it to the OLD immutable
	// version, and a repeat ingest would redo conversion, embedding and projection that the
	// recorded version already owns.
	//
	// The object INSERT names a version that does not exist yet, and the version names that
	// object, because both foreign keys are DEFERRABLE INITIALLY DEFERRED (0093:378-394) and
	// the remaining immediate one is checked at end of statement, by which time both rows are
	// present.
	//
	// Data-modifying CTEs cannot observe each other's effects on the underlying tables, so
	// every hand-off here travels through a RETURNING projection -- `inserted` reads
	// `asset_object.id`, never aura.storage_objects a second time.
	ReservePipelineCandidateVersion(ctx context.Context, arg ReservePipelineCandidateVersionParams) (ReservePipelineCandidateVersionRow, error)
	ResetAssetForIngestionRetry(ctx context.Context, arg ResetAssetForIngestionRetryParams) (AuraAssets, error)
	RestoreBenchmarkSetting(ctx context.Context, arg RestoreBenchmarkSettingParams) error
	RetryIngestionJob(ctx context.Context, arg RetryIngestionJobParams) (RetryIngestionJobRow, error)
	RetryRetentionItem(ctx context.Context, arg RetryRetentionItemParams) (int64, error)
	RevokeCapability(ctx context.Context, arg RevokeCapabilityParams) error
	// Advance an active task's next fire to now so the next tick claims it. Returns rows
	// affected so the caller distinguishes a hit from a non-active (pending/cancelled) task.
	RunTaskNowRow(ctx context.Context, id pgtype.UUID) (int64, error)
	ScanStaleRuns(ctx context.Context, secs float64) ([]ScanStaleRunsRow, error)
	// LOCKED cross-slice contract (D-A5-03 / SPEC Req#13). Telegram /search (Phase 13)
	// reuses this EXACT query; only the excerpt rendering differs per channel.
	SearchConversationTurns(ctx context.Context, arg SearchConversationTurnsParams) ([]SearchConversationTurnsRow, error)
	SetConversationTitleIfNull(ctx context.Context, arg SetConversationTitleIfNullParams) error
	// The machine's own description, written at ingest from the file. Identity-scoped:
	// this is a write reachable from an ingest a tool call can start, so a document id alone
	// must never be enough to overwrite what someone else's library says about their file.
	// A non-owner gets no rows, which the caller reports as not-found.
	SetDocumentCard(ctx context.Context, arg SetDocumentCardParams) (AuraDocuments, error)
	// D-09 (CHAT-05): set a turn's branch/parent pointers. The branch-write seam plan 25-07
	// uses when an edit/regenerate forks a new sibling branch off an existing parent turn.
	SetTurnBranchPointers(ctx context.Context, arg SetTurnBranchPointersParams) error
	SoftDeleteAsset(ctx context.Context, arg SoftDeleteAssetParams) (AuraAssets, error)
	SweepDueNotifications(ctx context.Context, arg SweepDueNotificationsParams) ([]AuraPendingNotifications, error)
	TouchTelegramLastSeen(ctx context.Context, telegramUserID int64) error
	TryRecoverExpiredOperation(ctx context.Context, arg TryRecoverExpiredOperationParams) (int64, error)
	TryStartOperation(ctx context.Context, arg TryStartOperationParams) (int64, error)
	UpdateAssetAccepted(ctx context.Context, arg UpdateAssetAcceptedParams) (AuraAssets, error)
	UpdateAssetResult(ctx context.Context, arg UpdateAssetResultParams) (AuraAssets, error)
	UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) (AuraAssets, error)
	UpdateAssetUploaded(ctx context.Context, arg UpdateAssetUploadedParams) (AuraAssets, error)
	UpdateConversationAggregates(ctx context.Context, arg UpdateConversationAggregatesParams) error
	// Owner-scoped reasoning-effort persistence (Phase 37E WEBMODEL-01 / D-06): writes the
	// chosen effort symbol into the EXISTING metadata jsonb — the column exists since
	// 0005_conversations.up.sql, so NO migration is added (numbering unchanged). Mirrors
	// RenameConversationForIdentity: rows-affected==0 = the caller does NOT own the id
	// (foreign OR absent), routed through db.WithIdentityTx so the 0032 RLS owner policy
	// backstops a forgotten predicate. Parameterized jsonb_set (never string concat) — the
	// effort is a symbol validated upstream (plan 06). COALESCE seeds '{}' when metadata is
	// NULL so the first write on a metadata-less row succeeds.
	UpdateConversationReasoningEffortForIdentity(ctx context.Context, arg UpdateConversationReasoningEffortForIdentityParams) (int64, error)
	UpdateConversationStatus(ctx context.Context, arg UpdateConversationStatusParams) error
	// Owner-scoped status transition (archive/unarchive, Phase 36 MUSR-01 / D-06). Serves the
	// /archive + /unarchive routes; rows-affected==0 drives the handler's 403-vs-404 split.
	UpdateConversationStatusForIdentity(ctx context.Context, arg UpdateConversationStatusForIdentityParams) (int64, error)
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (AuraDocuments, error)
	UpdateDocumentIngestJobProgress(ctx context.Context, arg UpdateDocumentIngestJobProgressParams) (AuraDocumentIngestJobs, error)
	UpdateDocumentIngestJobStatus(ctx context.Context, arg UpdateDocumentIngestJobStatusParams) (AuraDocumentIngestJobs, error)
	UpdateHeartbeat(ctx context.Context, id pgtype.UUID) error
	UpdateIngestionJobStatus(ctx context.Context, arg UpdateIngestionJobStatusParams) (UpdateIngestionJobStatusRow, error)
	UpdateNextRunAt(ctx context.Context, arg UpdateNextRunAtParams) error
	// Reschedule + re-payload a user task (the cockpit edit): rewrite the schedule grammar,
	// payload, notify route, and the recomputed first fire. Guarded to active/pending rows so
	// a cancelled/completed task is not silently revived. Returns rows affected.
	UpdateTaskScheduleRow(ctx context.Context, arg UpdateTaskScheduleRowParams) (int64, error)
	UpsertBenchmarkSetting(ctx context.Context, arg UpsertBenchmarkSettingParams) error
	UpsertDocumentTag(ctx context.Context, arg UpsertDocumentTagParams) error
	UpsertIdentityRecovery(ctx context.Context, arg UpsertIdentityRecoveryParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (AuraSettings, error)
	// The setting half: an edit stales whatever evidence existed. last_event_id is kept so
	// the status read can still name the command that last passed, which is what makes the
	// nudge say "last command X" instead of a bare "unverified".
	UpsertVerificationStateEdited(ctx context.Context, arg UpsertVerificationStateEditedParams) error
	// The clearing half of the invariant: recording an event makes this workspace the
	// verified one and drops the edit marker with the paths it carried.
	UpsertVerificationStateVerified(ctx context.Context, arg UpsertVerificationStateVerifiedParams) error
}

var _ Querier = (*Queries)(nil)
