// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention_operations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimRetentionItems = `-- name: ClaimRetentionItems :many
WITH claimable AS (
    SELECT candidate.id
    FROM aura.retention_operation_items AS candidate
    WHERE candidate.operation_id = $4
      AND (
        candidate.status IN ('planned', 'retryable')
        OR (candidate.status = 'deleting' AND candidate.lease_expires_at <= $3)
      )
    ORDER BY candidate.item_key
    LIMIT $5
    FOR UPDATE SKIP LOCKED
)
UPDATE aura.retention_operation_items AS item
SET status = 'deleting',
    claim_owner = $1,
    lease_expires_at = $2,
    attempt_count = item.attempt_count + 1,
    updated_at = $3
FROM claimable
WHERE item.id = claimable.id
RETURNING item.id, item.operation_id, item.item_key, item.identity_id, item.conversation_id, item.artifact_id, item.class, item.action, item.expected_version, item.expected_bytes, item.status, item.artifact_result, item.removed_bytes, item.failure_class, item.claim_owner, item.lease_expires_at, item.attempt_count, item.created_at, item.updated_at, item.completed_at
`

type ClaimRetentionItemsParams struct {
	ClaimOwner     pgtype.Text        `json:"claim_owner"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	Now            pgtype.Timestamptz `json:"now"`
	OperationID    pgtype.UUID        `json:"operation_id"`
	BatchSize      int32              `json:"batch_size"`
}

func (q *Queries) ClaimRetentionItems(ctx context.Context, arg ClaimRetentionItemsParams) ([]AuraRetentionOperationItems, error) {
	rows, err := q.db.Query(ctx, claimRetentionItems,
		arg.ClaimOwner,
		arg.LeaseExpiresAt,
		arg.Now,
		arg.OperationID,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraRetentionOperationItems{}
	for rows.Next() {
		var i AuraRetentionOperationItems
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.ItemKey,
			&i.IdentityID,
			&i.ConversationID,
			&i.ArtifactID,
			&i.Class,
			&i.Action,
			&i.ExpectedVersion,
			&i.ExpectedBytes,
			&i.Status,
			&i.ArtifactResult,
			&i.RemovedBytes,
			&i.FailureClass,
			&i.ClaimOwner,
			&i.LeaseExpiresAt,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRetentionItem = `-- name: CreateRetentionItem :one
INSERT INTO aura.retention_operation_items (
    id, operation_id, item_key, identity_id, conversation_id, artifact_id,
    class, action, expected_version, expected_bytes, status, artifact_result,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, 'planned', 'pending',
    $11, $11
)
ON CONFLICT (operation_id, item_key) DO UPDATE SET item_key = EXCLUDED.item_key
RETURNING id, operation_id, item_key, identity_id, conversation_id, artifact_id, class, action, expected_version, expected_bytes, status, artifact_result, removed_bytes, failure_class, claim_owner, lease_expires_at, attempt_count, created_at, updated_at, completed_at
`

type CreateRetentionItemParams struct {
	ID              pgtype.UUID        `json:"id"`
	OperationID     pgtype.UUID        `json:"operation_id"`
	ItemKey         string             `json:"item_key"`
	IdentityID      string             `json:"identity_id"`
	ConversationID  pgtype.Text        `json:"conversation_id"`
	ArtifactID      pgtype.Text        `json:"artifact_id"`
	Class           string             `json:"class"`
	Action          string             `json:"action"`
	ExpectedVersion int64              `json:"expected_version"`
	ExpectedBytes   int64              `json:"expected_bytes"`
	Now             pgtype.Timestamptz `json:"now"`
}

func (q *Queries) CreateRetentionItem(ctx context.Context, arg CreateRetentionItemParams) (AuraRetentionOperationItems, error) {
	row := q.db.QueryRow(ctx, createRetentionItem,
		arg.ID,
		arg.OperationID,
		arg.ItemKey,
		arg.IdentityID,
		arg.ConversationID,
		arg.ArtifactID,
		arg.Class,
		arg.Action,
		arg.ExpectedVersion,
		arg.ExpectedBytes,
		arg.Now,
	)
	var i AuraRetentionOperationItems
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.ItemKey,
		&i.IdentityID,
		&i.ConversationID,
		&i.ArtifactID,
		&i.Class,
		&i.Action,
		&i.ExpectedVersion,
		&i.ExpectedBytes,
		&i.Status,
		&i.ArtifactResult,
		&i.RemovedBytes,
		&i.FailureClass,
		&i.ClaimOwner,
		&i.LeaseExpiresAt,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createRetentionOperation = `-- name: CreateRetentionOperation :one
INSERT INTO aura.retention_operations (
    id, token, policy_version, status, candidate_count, planned_bytes, created_at, updated_at
) VALUES (
    $1, $2, $3, 'planned',
    $4, $5, $6, $6
)
ON CONFLICT (token) DO UPDATE SET token = EXCLUDED.token
RETURNING id, token, policy_version, status, candidate_count, planned_bytes, completed_count, completed_bytes, failure_count, created_at, updated_at, completed_at
`

type CreateRetentionOperationParams struct {
	ID             pgtype.UUID        `json:"id"`
	Token          string             `json:"token"`
	PolicyVersion  string             `json:"policy_version"`
	CandidateCount int32              `json:"candidate_count"`
	PlannedBytes   int64              `json:"planned_bytes"`
	Now            pgtype.Timestamptz `json:"now"`
}

func (q *Queries) CreateRetentionOperation(ctx context.Context, arg CreateRetentionOperationParams) (AuraRetentionOperations, error) {
	row := q.db.QueryRow(ctx, createRetentionOperation,
		arg.ID,
		arg.Token,
		arg.PolicyVersion,
		arg.CandidateCount,
		arg.PlannedBytes,
		arg.Now,
	)
	var i AuraRetentionOperations
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.PolicyVersion,
		&i.Status,
		&i.CandidateCount,
		&i.PlannedBytes,
		&i.CompletedCount,
		&i.CompletedBytes,
		&i.FailureCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failRetentionItem = `-- name: FailRetentionItem :execrows
UPDATE aura.retention_operation_items
SET status = 'failed',
    artifact_result = CASE WHEN artifact_result = 'pending' THEN 'failed' ELSE artifact_result END,
    failure_class = $1,
    claim_owner = NULL,
    lease_expires_at = NULL,
    updated_at = $2
WHERE id = $3
  AND status = 'deleting'
  AND claim_owner = $4
`

type FailRetentionItemParams struct {
	FailureClass pgtype.Text        `json:"failure_class"`
	Now          pgtype.Timestamptz `json:"now"`
	ID           pgtype.UUID        `json:"id"`
	ClaimOwner   pgtype.Text        `json:"claim_owner"`
}

func (q *Queries) FailRetentionItem(ctx context.Context, arg FailRetentionItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, failRetentionItem,
		arg.FailureClass,
		arg.Now,
		arg.ID,
		arg.ClaimOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeRetentionItem = `-- name: FinalizeRetentionItem :execrows
UPDATE aura.retention_operation_items
SET status = 'completed',
    claim_owner = NULL,
    lease_expires_at = NULL,
    failure_class = NULL,
    completed_at = $1,
    updated_at = $1
WHERE id = $2
  AND status = 'deleting'
  AND claim_owner = $3
  AND artifact_result IN ('removed', 'absent')
`

type FinalizeRetentionItemParams struct {
	Now        pgtype.Timestamptz `json:"now"`
	ID         pgtype.UUID        `json:"id"`
	ClaimOwner pgtype.Text        `json:"claim_owner"`
}

func (q *Queries) FinalizeRetentionItem(ctx context.Context, arg FinalizeRetentionItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeRetentionItem, arg.Now, arg.ID, arg.ClaimOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeRetentionOperation = `-- name: FinalizeRetentionOperation :one
UPDATE aura.retention_operations AS operation
SET status = CASE
        WHEN EXISTS (
            SELECT 1 FROM aura.retention_operation_items item
            WHERE item.operation_id = operation.id AND item.status = 'failed'
        ) THEN 'failed'
        WHEN EXISTS (
            SELECT 1 FROM aura.retention_operation_items item
            WHERE item.operation_id = operation.id AND item.status <> 'completed'
        ) THEN 'retryable'
        ELSE 'completed'
    END,
    completed_count = (
        SELECT count(*) FROM aura.retention_operation_items item
        WHERE item.operation_id = operation.id AND item.status = 'completed'
    ),
    completed_bytes = COALESCE((
        SELECT sum(removed_bytes) FROM aura.retention_operation_items item
        WHERE item.operation_id = operation.id AND item.status = 'completed'
    ), 0),
    failure_count = (
        SELECT count(*) FROM aura.retention_operation_items item
        WHERE item.operation_id = operation.id AND item.status IN ('retryable', 'failed')
    ),
    completed_at = CASE WHEN NOT EXISTS (
        SELECT 1 FROM aura.retention_operation_items item
        WHERE item.operation_id = operation.id AND item.status <> 'completed'
    ) THEN $1::timestamptz ELSE NULL END,
    updated_at = $1
WHERE operation.id = $2
RETURNING operation.id, operation.token, operation.policy_version, operation.status, operation.candidate_count, operation.planned_bytes, operation.completed_count, operation.completed_bytes, operation.failure_count, operation.created_at, operation.updated_at, operation.completed_at
`

type FinalizeRetentionOperationParams struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  pgtype.UUID        `json:"id"`
}

func (q *Queries) FinalizeRetentionOperation(ctx context.Context, arg FinalizeRetentionOperationParams) (AuraRetentionOperations, error) {
	row := q.db.QueryRow(ctx, finalizeRetentionOperation, arg.Now, arg.ID)
	var i AuraRetentionOperations
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.PolicyVersion,
		&i.Status,
		&i.CandidateCount,
		&i.PlannedBytes,
		&i.CompletedCount,
		&i.CompletedBytes,
		&i.FailureCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRetentionItem = `-- name: GetRetentionItem :one
SELECT id, operation_id, item_key, identity_id, conversation_id, artifact_id, class, action, expected_version, expected_bytes, status, artifact_result, removed_bytes, failure_class, claim_owner, lease_expires_at, attempt_count, created_at, updated_at, completed_at FROM aura.retention_operation_items WHERE id = $1
`

func (q *Queries) GetRetentionItem(ctx context.Context, id pgtype.UUID) (AuraRetentionOperationItems, error) {
	row := q.db.QueryRow(ctx, getRetentionItem, id)
	var i AuraRetentionOperationItems
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.ItemKey,
		&i.IdentityID,
		&i.ConversationID,
		&i.ArtifactID,
		&i.Class,
		&i.Action,
		&i.ExpectedVersion,
		&i.ExpectedBytes,
		&i.Status,
		&i.ArtifactResult,
		&i.RemovedBytes,
		&i.FailureClass,
		&i.ClaimOwner,
		&i.LeaseExpiresAt,
		&i.AttemptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRetentionOperationByToken = `-- name: GetRetentionOperationByToken :one
SELECT id, token, policy_version, status, candidate_count, planned_bytes, completed_count, completed_bytes, failure_count, created_at, updated_at, completed_at FROM aura.retention_operations WHERE token = $1
`

func (q *Queries) GetRetentionOperationByToken(ctx context.Context, token string) (AuraRetentionOperations, error) {
	row := q.db.QueryRow(ctx, getRetentionOperationByToken, token)
	var i AuraRetentionOperations
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.PolicyVersion,
		&i.Status,
		&i.CandidateCount,
		&i.PlannedBytes,
		&i.CompletedCount,
		&i.CompletedBytes,
		&i.FailureCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const recordRetentionArtifactResult = `-- name: RecordRetentionArtifactResult :execrows
UPDATE aura.retention_operation_items
SET artifact_result = $1,
    removed_bytes = $2,
    failure_class = $3,
    updated_at = $4
WHERE id = $5
  AND status = 'deleting'
  AND claim_owner = $6
`

type RecordRetentionArtifactResultParams struct {
	ArtifactResult string             `json:"artifact_result"`
	RemovedBytes   int64              `json:"removed_bytes"`
	FailureClass   pgtype.Text        `json:"failure_class"`
	Now            pgtype.Timestamptz `json:"now"`
	ID             pgtype.UUID        `json:"id"`
	ClaimOwner     pgtype.Text        `json:"claim_owner"`
}

func (q *Queries) RecordRetentionArtifactResult(ctx context.Context, arg RecordRetentionArtifactResultParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordRetentionArtifactResult,
		arg.ArtifactResult,
		arg.RemovedBytes,
		arg.FailureClass,
		arg.Now,
		arg.ID,
		arg.ClaimOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryRetentionItem = `-- name: RetryRetentionItem :execrows
UPDATE aura.retention_operation_items
SET status = 'retryable',
    artifact_result = CASE WHEN artifact_result = 'failed' THEN 'pending' ELSE artifact_result END,
    failure_class = $1,
    claim_owner = NULL,
    lease_expires_at = NULL,
    updated_at = $2
WHERE id = $3
  AND status = 'deleting'
  AND claim_owner = $4
`

type RetryRetentionItemParams struct {
	FailureClass pgtype.Text        `json:"failure_class"`
	Now          pgtype.Timestamptz `json:"now"`
	ID           pgtype.UUID        `json:"id"`
	ClaimOwner   pgtype.Text        `json:"claim_owner"`
}

func (q *Queries) RetryRetentionItem(ctx context.Context, arg RetryRetentionItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryRetentionItem,
		arg.FailureClass,
		arg.Now,
		arg.ID,
		arg.ClaimOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
