// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler_tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelTask = `-- name: CancelTask :exec
UPDATE aura.scheduler_tasks
SET status = 'cancelled', updated_at = now()
WHERE id = $1
`

func (q *Queries) CancelTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelTask, id)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO aura.scheduler_tasks (
    id, kind, schedule_kind, cron_expr, every_minutes, run_at, tz, payload,
    step_budget, status, next_run_at, notify_route, identity_id, origin_conversation_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, kind, schedule_kind, cron_expr, every_minutes, run_at, tz, payload,
    step_budget, status, next_run_at, notify_route, identity_id, origin_conversation_id,
    created_at, updated_at
`

type CreateTaskParams struct {
	ID                   pgtype.UUID        `json:"id"`
	Kind                 string             `json:"kind"`
	ScheduleKind         string             `json:"schedule_kind"`
	CronExpr             pgtype.Text        `json:"cron_expr"`
	EveryMinutes         pgtype.Int4        `json:"every_minutes"`
	RunAt                pgtype.Timestamptz `json:"run_at"`
	Tz                   string             `json:"tz"`
	Payload              []byte             `json:"payload"`
	StepBudget           pgtype.Int4        `json:"step_budget"`
	Status               string             `json:"status"`
	NextRunAt            pgtype.Timestamptz `json:"next_run_at"`
	NotifyRoute          pgtype.Text        `json:"notify_route"`
	IdentityID           string             `json:"identity_id"`
	OriginConversationID pgtype.UUID        `json:"origin_conversation_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (AuraSchedulerTasks, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.Kind,
		arg.ScheduleKind,
		arg.CronExpr,
		arg.EveryMinutes,
		arg.RunAt,
		arg.Tz,
		arg.Payload,
		arg.StepBudget,
		arg.Status,
		arg.NextRunAt,
		arg.NotifyRoute,
		arg.IdentityID,
		arg.OriginConversationID,
	)
	var i AuraSchedulerTasks
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ScheduleKind,
		&i.CronExpr,
		&i.EveryMinutes,
		&i.RunAt,
		&i.Tz,
		&i.Payload,
		&i.StepBudget,
		&i.Status,
		&i.NextRunAt,
		&i.NotifyRoute,
		&i.IdentityID,
		&i.OriginConversationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dueTasks = `-- name: DueTasks :many
SELECT id, kind, schedule_kind, cron_expr, every_minutes, run_at, tz, payload,
    step_budget, status, next_run_at, notify_route, identity_id, origin_conversation_id,
    created_at, updated_at
FROM aura.scheduler_tasks
WHERE status = 'active' AND next_run_at <= now()
ORDER BY next_run_at ASC
LIMIT $1
`

// Claim correctness is held by the per-task pg_try_advisory_lock (claim.go), NOT a
// row lock here: this SELECT runs on the autocommit pool, so any FOR UPDATE SKIP
// LOCKED would release the instant the SELECT returns (inert, L5). The advisory lock
// is what makes each due task a singleton across concurrent workers.
func (q *Queries) DueTasks(ctx context.Context, limit int32) ([]AuraSchedulerTasks, error) {
	rows, err := q.db.Query(ctx, dueTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraSchedulerTasks{}
	for rows.Next() {
		var i AuraSchedulerTasks
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ScheduleKind,
			&i.CronExpr,
			&i.EveryMinutes,
			&i.RunAt,
			&i.Tz,
			&i.Payload,
			&i.StepBudget,
			&i.Status,
			&i.NextRunAt,
			&i.NotifyRoute,
			&i.IdentityID,
			&i.OriginConversationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, kind, schedule_kind, cron_expr, every_minutes, run_at, tz, payload,
    step_budget, status, next_run_at, notify_route, identity_id, origin_conversation_id,
    created_at, updated_at
FROM aura.scheduler_tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (AuraSchedulerTasks, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i AuraSchedulerTasks
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ScheduleKind,
		&i.CronExpr,
		&i.EveryMinutes,
		&i.RunAt,
		&i.Tz,
		&i.Payload,
		&i.StepBudget,
		&i.Status,
		&i.NextRunAt,
		&i.NotifyRoute,
		&i.IdentityID,
		&i.OriginConversationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTasks = `-- name: ListActiveTasks :many
SELECT id, kind, schedule_kind, cron_expr, every_minutes, run_at, tz, payload,
    step_budget, status, next_run_at, notify_route, identity_id, origin_conversation_id,
    created_at, updated_at
FROM aura.scheduler_tasks
WHERE status = 'active'
ORDER BY next_run_at ASC NULLS LAST, id ASC
`

func (q *Queries) ListActiveTasks(ctx context.Context) ([]AuraSchedulerTasks, error) {
	rows, err := q.db.Query(ctx, listActiveTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraSchedulerTasks{}
	for rows.Next() {
		var i AuraSchedulerTasks
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ScheduleKind,
			&i.CronExpr,
			&i.EveryMinutes,
			&i.RunAt,
			&i.Tz,
			&i.Payload,
			&i.StepBudget,
			&i.Status,
			&i.NextRunAt,
			&i.NotifyRoute,
			&i.IdentityID,
			&i.OriginConversationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNextRunAt = `-- name: UpdateNextRunAt :exec
UPDATE aura.scheduler_tasks
SET next_run_at = $2, updated_at = now()
WHERE id = $1
`

type UpdateNextRunAtParams struct {
	ID        pgtype.UUID        `json:"id"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpdateNextRunAt(ctx context.Context, arg UpdateNextRunAtParams) error {
	_, err := q.db.Exec(ctx, updateNextRunAt, arg.ID, arg.NextRunAt)
	return err
}
