// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM aura.settings WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSetting, key)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT key, value, is_secret, updated_at, updated_by
FROM aura.settings
WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (AuraSettings, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i AuraSettings
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, is_secret, updated_at, updated_by
FROM aura.settings
ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]AuraSettings, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraSettings{}
	for rows.Next() {
		var i AuraSettings
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.IsSecret,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO aura.settings (key, value, is_secret, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE
SET value      = EXCLUDED.value,
    is_secret  = EXCLUDED.is_secret,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING key, value, is_secret, updated_at, updated_by
`

type UpsertSettingParams struct {
	Key       string      `json:"key"`
	Value     string      `json:"value"`
	IsSecret  bool        `json:"is_secret"`
	UpdatedBy pgtype.Text `json:"updated_by"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (AuraSettings, error) {
	row := q.db.QueryRow(ctx, upsertSetting,
		arg.Key,
		arg.Value,
		arg.IsSecret,
		arg.UpdatedBy,
	)
	var i AuraSettings
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
