// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram_accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTelegramAccounts = `-- name: CountTelegramAccounts :one
SELECT count(*) FROM aura.telegram_accounts
`

func (q *Queries) CountTelegramAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTelegramAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTelegramAccountByIdentity = `-- name: GetTelegramAccountByIdentity :one
SELECT telegram_user_id, identity_id, username, first_name, added_at, last_seen_at
FROM aura.telegram_accounts
WHERE identity_id = $1
`

func (q *Queries) GetTelegramAccountByIdentity(ctx context.Context, identityID pgtype.UUID) (AuraTelegramAccounts, error) {
	row := q.db.QueryRow(ctx, getTelegramAccountByIdentity, identityID)
	var i AuraTelegramAccounts
	err := row.Scan(
		&i.TelegramUserID,
		&i.IdentityID,
		&i.Username,
		&i.FirstName,
		&i.AddedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getTelegramAccountByTelegramID = `-- name: GetTelegramAccountByTelegramID :one
SELECT telegram_user_id, identity_id, username, first_name, added_at, last_seen_at
FROM aura.telegram_accounts
WHERE telegram_user_id = $1
`

func (q *Queries) GetTelegramAccountByTelegramID(ctx context.Context, telegramUserID int64) (AuraTelegramAccounts, error) {
	row := q.db.QueryRow(ctx, getTelegramAccountByTelegramID, telegramUserID)
	var i AuraTelegramAccounts
	err := row.Scan(
		&i.TelegramUserID,
		&i.IdentityID,
		&i.Username,
		&i.FirstName,
		&i.AddedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const insertTelegramAccount = `-- name: InsertTelegramAccount :one
INSERT INTO aura.telegram_accounts (telegram_user_id, identity_id, username, first_name)
VALUES ($1, $2, $3, $4)
RETURNING telegram_user_id, identity_id, username, first_name, added_at, last_seen_at
`

type InsertTelegramAccountParams struct {
	TelegramUserID int64       `json:"telegram_user_id"`
	IdentityID     pgtype.UUID `json:"identity_id"`
	Username       pgtype.Text `json:"username"`
	FirstName      pgtype.Text `json:"first_name"`
}

func (q *Queries) InsertTelegramAccount(ctx context.Context, arg InsertTelegramAccountParams) (AuraTelegramAccounts, error) {
	row := q.db.QueryRow(ctx, insertTelegramAccount,
		arg.TelegramUserID,
		arg.IdentityID,
		arg.Username,
		arg.FirstName,
	)
	var i AuraTelegramAccounts
	err := row.Scan(
		&i.TelegramUserID,
		&i.IdentityID,
		&i.Username,
		&i.FirstName,
		&i.AddedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listTelegramAccounts = `-- name: ListTelegramAccounts :many
SELECT telegram_user_id, identity_id, username, first_name, added_at, last_seen_at
FROM aura.telegram_accounts
ORDER BY added_at ASC, telegram_user_id ASC
`

func (q *Queries) ListTelegramAccounts(ctx context.Context) ([]AuraTelegramAccounts, error) {
	rows, err := q.db.Query(ctx, listTelegramAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraTelegramAccounts{}
	for rows.Next() {
		var i AuraTelegramAccounts
		if err := rows.Scan(
			&i.TelegramUserID,
			&i.IdentityID,
			&i.Username,
			&i.FirstName,
			&i.AddedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTelegramLastSeen = `-- name: TouchTelegramLastSeen :exec
UPDATE aura.telegram_accounts
SET last_seen_at = now()
WHERE telegram_user_id = $1
`

func (q *Queries) TouchTelegramLastSeen(ctx context.Context, telegramUserID int64) error {
	_, err := q.db.Exec(ctx, touchTelegramLastSeen, telegramUserID)
	return err
}
