// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tool_invocations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getToolInvocationEnd = `-- name: GetToolInvocationEnd :one
SELECT id, conversation_id, request_id, tool_call_id, tool_name, event_kind, seq, ts,
       started_at, ended_at, duration_ms,
       args_raw, args_bytes,
       status, error, result_preview, preview_bytes, result_bytes, result_truncated,
       result_sidecar_path, exit_code, meta
FROM aura.tool_invocations
WHERE conversation_id = $1 AND request_id = $2 AND tool_call_id = $3 AND event_kind = 'end'
`

type GetToolInvocationEndParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	RequestID      pgtype.UUID `json:"request_id"`
	ToolCallID     string      `json:"tool_call_id"`
}

func (q *Queries) GetToolInvocationEnd(ctx context.Context, arg GetToolInvocationEndParams) (AuraToolInvocations, error) {
	row := q.db.QueryRow(ctx, getToolInvocationEnd, arg.ConversationID, arg.RequestID, arg.ToolCallID)
	var i AuraToolInvocations
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.RequestID,
		&i.ToolCallID,
		&i.ToolName,
		&i.EventKind,
		&i.Seq,
		&i.Ts,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMs,
		&i.ArgsRaw,
		&i.ArgsBytes,
		&i.Status,
		&i.Error,
		&i.ResultPreview,
		&i.PreviewBytes,
		&i.ResultBytes,
		&i.ResultTruncated,
		&i.ResultSidecarPath,
		&i.ExitCode,
		&i.Meta,
	)
	return i, err
}

const insertToolInvocation = `-- name: InsertToolInvocation :execrows
INSERT INTO aura.tool_invocations (
    conversation_id, request_id, tool_call_id, tool_name, event_kind, seq, ts,
    started_at, ended_at, duration_ms,
    args_raw, args_bytes,
    status, error, result_preview, preview_bytes, result_bytes, result_truncated,
    result_sidecar_path, exit_code, meta
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12,
    $13, $14, $15, $16, $17, $18,
    $19, $20, $21
)
ON CONFLICT (conversation_id, request_id, tool_call_id, event_kind) DO NOTHING
`

type InsertToolInvocationParams struct {
	ConversationID    pgtype.UUID        `json:"conversation_id"`
	RequestID         pgtype.UUID        `json:"request_id"`
	ToolCallID        string             `json:"tool_call_id"`
	ToolName          string             `json:"tool_name"`
	EventKind         string             `json:"event_kind"`
	Seq               int32              `json:"seq"`
	Ts                pgtype.Timestamptz `json:"ts"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	EndedAt           pgtype.Timestamptz `json:"ended_at"`
	DurationMs        pgtype.Int8        `json:"duration_ms"`
	ArgsRaw           pgtype.Text        `json:"args_raw"`
	ArgsBytes         pgtype.Int4        `json:"args_bytes"`
	Status            pgtype.Text        `json:"status"`
	Error             pgtype.Text        `json:"error"`
	ResultPreview     pgtype.Text        `json:"result_preview"`
	PreviewBytes      pgtype.Int4        `json:"preview_bytes"`
	ResultBytes       pgtype.Int4        `json:"result_bytes"`
	ResultTruncated   pgtype.Bool        `json:"result_truncated"`
	ResultSidecarPath pgtype.Text        `json:"result_sidecar_path"`
	ExitCode          pgtype.Int4        `json:"exit_code"`
	Meta              []byte             `json:"meta"`
}

func (q *Queries) InsertToolInvocation(ctx context.Context, arg InsertToolInvocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertToolInvocation,
		arg.ConversationID,
		arg.RequestID,
		arg.ToolCallID,
		arg.ToolName,
		arg.EventKind,
		arg.Seq,
		arg.Ts,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationMs,
		arg.ArgsRaw,
		arg.ArgsBytes,
		arg.Status,
		arg.Error,
		arg.ResultPreview,
		arg.PreviewBytes,
		arg.ResultBytes,
		arg.ResultTruncated,
		arg.ResultSidecarPath,
		arg.ExitCode,
		arg.Meta,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listInFlightToolInvocationsBefore = `-- name: ListInFlightToolInvocationsBefore :many
SELECT s.id, s.conversation_id, s.request_id, s.tool_call_id, s.tool_name, s.event_kind, s.seq, s.ts,
       s.started_at, s.ended_at, s.duration_ms,
       s.args_raw, s.args_bytes,
       s.status, s.error, s.result_preview, s.preview_bytes, s.result_bytes, s.result_truncated,
       s.result_sidecar_path, s.exit_code, s.meta
FROM aura.tool_invocations s
WHERE s.event_kind = 'start'
  AND s.started_at < $1
  AND NOT EXISTS (
      SELECT 1 FROM aura.tool_invocations e
      WHERE e.conversation_id = s.conversation_id
        AND e.request_id = s.request_id
        AND e.tool_call_id = s.tool_call_id
        AND e.event_kind = 'end'
  )
ORDER BY s.started_at ASC, s.id ASC
`

func (q *Queries) ListInFlightToolInvocationsBefore(ctx context.Context, startedAt pgtype.Timestamptz) ([]AuraToolInvocations, error) {
	rows, err := q.db.Query(ctx, listInFlightToolInvocationsBefore, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraToolInvocations{}
	for rows.Next() {
		var i AuraToolInvocations
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RequestID,
			&i.ToolCallID,
			&i.ToolName,
			&i.EventKind,
			&i.Seq,
			&i.Ts,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMs,
			&i.ArgsRaw,
			&i.ArgsBytes,
			&i.Status,
			&i.Error,
			&i.ResultPreview,
			&i.PreviewBytes,
			&i.ResultBytes,
			&i.ResultTruncated,
			&i.ResultSidecarPath,
			&i.ExitCode,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolInvocationsByConversation = `-- name: ListToolInvocationsByConversation :many
SELECT id, conversation_id, request_id, tool_call_id, tool_name, event_kind, seq, ts,
       started_at, ended_at, duration_ms,
       args_raw, args_bytes,
       status, error, result_preview, preview_bytes, result_bytes, result_truncated,
       result_sidecar_path, exit_code, meta
FROM aura.tool_invocations
WHERE conversation_id = $1
ORDER BY seq ASC, ts ASC, id ASC
`

func (q *Queries) ListToolInvocationsByConversation(ctx context.Context, conversationID pgtype.UUID) ([]AuraToolInvocations, error) {
	rows, err := q.db.Query(ctx, listToolInvocationsByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraToolInvocations{}
	for rows.Next() {
		var i AuraToolInvocations
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RequestID,
			&i.ToolCallID,
			&i.ToolName,
			&i.EventKind,
			&i.Seq,
			&i.Ts,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMs,
			&i.ArgsRaw,
			&i.ArgsBytes,
			&i.Status,
			&i.Error,
			&i.ResultPreview,
			&i.PreviewBytes,
			&i.ResultBytes,
			&i.ResultTruncated,
			&i.ResultSidecarPath,
			&i.ExitCode,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
