// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tool_invocations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertToolInvocation = `-- name: InsertToolInvocation :exec
INSERT INTO aura.tool_invocations (
    conversation_id, request_id, tool_call_id, tool_name, event_kind, seq, ts,
    started_at, ended_at, duration_ms,
    args_raw, args_bytes,
    status, error, result_preview, preview_bytes, result_bytes, result_truncated,
    result_sidecar_path, exit_code, meta
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12,
    $13, $14, $15, $16, $17, $18,
    $19, $20, $21
)
ON CONFLICT (conversation_id, request_id, tool_call_id, event_kind) DO NOTHING
`

type InsertToolInvocationParams struct {
	ConversationID    pgtype.UUID        `json:"conversation_id"`
	RequestID         pgtype.UUID        `json:"request_id"`
	ToolCallID        string             `json:"tool_call_id"`
	ToolName          string             `json:"tool_name"`
	EventKind         string             `json:"event_kind"`
	Seq               int32              `json:"seq"`
	Ts                pgtype.Timestamptz `json:"ts"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	EndedAt           pgtype.Timestamptz `json:"ended_at"`
	DurationMs        pgtype.Int8        `json:"duration_ms"`
	ArgsRaw           pgtype.Text        `json:"args_raw"`
	ArgsBytes         pgtype.Int4        `json:"args_bytes"`
	Status            pgtype.Text        `json:"status"`
	Error             pgtype.Text        `json:"error"`
	ResultPreview     pgtype.Text        `json:"result_preview"`
	PreviewBytes      pgtype.Int4        `json:"preview_bytes"`
	ResultBytes       pgtype.Int4        `json:"result_bytes"`
	ResultTruncated   pgtype.Bool        `json:"result_truncated"`
	ResultSidecarPath pgtype.Text        `json:"result_sidecar_path"`
	ExitCode          pgtype.Int4        `json:"exit_code"`
	Meta              []byte             `json:"meta"`
}

func (q *Queries) InsertToolInvocation(ctx context.Context, arg InsertToolInvocationParams) error {
	_, err := q.db.Exec(ctx, insertToolInvocation,
		arg.ConversationID,
		arg.RequestID,
		arg.ToolCallID,
		arg.ToolName,
		arg.EventKind,
		arg.Seq,
		arg.Ts,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationMs,
		arg.ArgsRaw,
		arg.ArgsBytes,
		arg.Status,
		arg.Error,
		arg.ResultPreview,
		arg.PreviewBytes,
		arg.ResultBytes,
		arg.ResultTruncated,
		arg.ResultSidecarPath,
		arg.ExitCode,
		arg.Meta,
	)
	return err
}

const listToolInvocationsByConversation = `-- name: ListToolInvocationsByConversation :many
SELECT id, conversation_id, request_id, tool_call_id, tool_name, event_kind, seq, ts,
       started_at, ended_at, duration_ms,
       args_raw, args_bytes,
       status, error, result_preview, preview_bytes, result_bytes, result_truncated,
       result_sidecar_path, exit_code, meta
FROM aura.tool_invocations
WHERE conversation_id = $1
ORDER BY seq ASC, ts ASC, id ASC
`

func (q *Queries) ListToolInvocationsByConversation(ctx context.Context, conversationID pgtype.UUID) ([]AuraToolInvocations, error) {
	rows, err := q.db.Query(ctx, listToolInvocationsByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuraToolInvocations{}
	for rows.Next() {
		var i AuraToolInvocations
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RequestID,
			&i.ToolCallID,
			&i.ToolName,
			&i.EventKind,
			&i.Seq,
			&i.Ts,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMs,
			&i.ArgsRaw,
			&i.ArgsBytes,
			&i.Status,
			&i.Error,
			&i.ResultPreview,
			&i.PreviewBytes,
			&i.ResultBytes,
			&i.ResultTruncated,
			&i.ResultSidecarPath,
			&i.ExitCode,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
