#!/bin/sh
# garage-init.sh — idempotent bootstrap that teaches a fresh garage daemon
# about the S3 access key generated by aura-secrets and grants it owner
# access to the aura-artifacts bucket. Re-running is safe: every step is
# guarded by a `garage <thing> info` check.
#
# The garage CLI connects to the daemon via RPC. rpc_secret + rpc_public_addr
# come from /etc/garage.toml (mounted from data/secrets/garage.toml).
set -eu

SECRETS_DIR="${AURA_SECRETS_DIR:-/secrets}"
BUCKET="${GARAGE_BUCKET:-aura-artifacts}"
KEY_NAME="${GARAGE_KEY_NAME:-aura}"

access_key="$(cat "$SECRETS_DIR/garage_s3_access_key")"
secret_key="$(cat "$SECRETS_DIR/garage_s3_secret_key")"

# Wait for garage RPC to be ready. `garage status` is the lightest probe and
# fails fast (~100ms) when the daemon is not yet listening.
attempt=0
while : ; do
	if garage status >/dev/null 2>&1; then
		break
	fi
	attempt=$((attempt + 1))
	if [ "$attempt" -gt 60 ]; then
		echo "garage-init: RPC not ready after 60s" >&2
		garage status || true
		exit 1
	fi
	sleep 1
done

# Register the access/secret pair if garage has never seen it before.
if ! garage key info "$access_key" >/dev/null 2>&1; then
	garage key import --yes -n "$KEY_NAME" "$access_key" "$secret_key"
	echo "garage-init: imported key $KEY_NAME"
else
	echo "garage-init: key $KEY_NAME already registered"
fi

# Create the bucket the aura backup/source pipelines write to.
if ! garage bucket info "$BUCKET" >/dev/null 2>&1; then
	garage bucket create "$BUCKET"
	echo "garage-init: created bucket $BUCKET"
else
	echo "garage-init: bucket $BUCKET already present"
fi

# Grant read+write+owner to the imported key. `bucket allow` is idempotent.
garage bucket allow --read --write --owner --key "$access_key" "$BUCKET"
echo "garage-init: granted read+write+owner on $BUCKET to $KEY_NAME"
