// A partial Italian table for Filerobot's `translations` prop — the visible labels only, enough to
// prove the override works offline. The full build needs all 128 keys of defaultTranslations.js.
export const IT = {
  name: 'Nome',
  save: 'Salva',
  saveAs: 'Salva come',
  cancel: 'Annulla',
  back: 'Indietro',
  loading: 'Caricamento…',
  adjustTab: 'Regola',
  finetuneTab: 'Ritocca',
  filtersTab: 'Filtri',
  annotateTab: 'Annota',
  watermarkTab: 'Filigrana',
  resizeTab: 'Ridimensiona',
  cropTool: 'Ritaglia',
  rotateTool: 'Ruota',
  flipX: 'Specchia O',
  flipY: 'Specchia V',
  original: 'Originale',
  brightnessTool: 'Luminosità',
  contrastTool: 'Contrasto',
  hsvTool: 'HSV',
  warmthTool: 'Calore',
  blurTool: 'Sfocatura',
  textTool: 'Testo',
  imageTool: 'Immagine',
  rectangleTool: 'Rettangolo',
  ellipseTool: 'Ellisse',
  polygonTool: 'Poligono',
  penTool: 'Penna',
  lineTool: 'Linea',
  arrowTool: 'Freccia',
  quality: 'Qualità',
  fileType: 'Tipo di file',
};
