"""Neo4j graph operations and schema management."""

from neo4j_agent_memory.graph import queries
from neo4j_agent_memory.graph.client import Neo4jClient
from neo4j_agent_memory.graph.preference_queries import (
    FIND_DUPLICATE_PREFERENCES,
    SEARCH_PREFERENCES_BY_CATEGORY,
    SEARCH_PREFERENCES_BY_CATEGORY_SCOPED,
    SEARCH_PREFERENCES_BY_EMBEDDING,
    SEARCH_PREFERENCES_BY_EMBEDDING_SCOPED,
)
from neo4j_agent_memory.graph.schema import SchemaManager

queries.FIND_DUPLICATE_PREFERENCES = FIND_DUPLICATE_PREFERENCES
queries.SEARCH_PREFERENCES_BY_CATEGORY = SEARCH_PREFERENCES_BY_CATEGORY
queries.SEARCH_PREFERENCES_BY_CATEGORY_SCOPED = SEARCH_PREFERENCES_BY_CATEGORY_SCOPED
queries.SEARCH_PREFERENCES_BY_EMBEDDING = SEARCH_PREFERENCES_BY_EMBEDDING
queries.SEARCH_PREFERENCES_BY_EMBEDDING_SCOPED = SEARCH_PREFERENCES_BY_EMBEDDING_SCOPED

__all__ = [
    "Neo4jClient",
    "SchemaManager",
]
