# Spike 067 - Stage C: build hybrid (pgvector + AGE) test SQL with REAL Granite-97m
# embeddings from the live aura-llama-embed sidecar. Invariant culture forced on every
# float (host locale it-IT -> comma decimals would corrupt pgvector literals).
# ASCII-only on purpose (Windows PowerShell 5.1 misreads non-ASCII BOM-less files).
$ErrorActionPreference = "Stop"
$inv = [System.Globalization.CultureInfo]::InvariantCulture

$corpus = [ordered]@{
  "e1" = "Tesla Model 3 electric car"
  "e2" = "Davide the car owner"
  "e4" = "a red electric vehicle"
  "e5" = "the hungry cat sleeps"
}
$queryText = "electric vehicle"

$inputs = @($corpus.Values) + @($queryText)
$body = @{ input = $inputs } | ConvertTo-Json
$r = Invoke-RestMethod -Uri "http://127.0.0.1:8081/v1/embeddings" -Method Post -ContentType "application/json" -Body $body -TimeoutSec 60

function Lit($vec){ "[" + (($vec | ForEach-Object { $_.ToString("G9",$inv) }) -join ",") + "]" }

$L = New-Object System.Collections.Generic.List[string]
$L.Add("-- GENERATED by 03_gen_hybrid_sql.ps1 - real Granite-97m 384d embeddings.")
$L.Add("\set ON_ERROR_STOP off")
$L.Add('LOAD ''age''; SET search_path = ag_catalog, "$user", public;')
$L.Add("DROP TABLE IF EXISTS chunk_vec;")
$L.Add("CREATE TABLE chunk_vec (node_id text PRIMARY KEY, txt text, embedding vector(384));")

$i = 0
foreach($k in $corpus.Keys){
  $vec = $r.data[$i].embedding
  $txt = $corpus[$k].Replace("'","''")
  $L.Add("INSERT INTO chunk_vec VALUES ('$k','$txt','$(Lit $vec)');")
  $i++
}
$qvec = $r.data[$i].embedding
$ql = Lit $qvec
$L.Add("CREATE INDEX ON chunk_vec USING hnsw (embedding vector_cosine_ops);")
$L.Add("\echo '== C1: pgvector cosine top-3 for query electric vehicle =='")
$L.Add("SELECT node_id, txt, round((embedding <=> '$ql')::numeric,4) AS cos_dist FROM chunk_vec ORDER BY embedding <=> '$ql' LIMIT 3;")
$L.Add("\echo '== C2: hybrid bridge - pgvector top hit id matches an AGE Entity.id =='")
$L.Add("SELECT node_id AS vec_hit_id FROM chunk_vec ORDER BY embedding <=> '$ql' LIMIT 1;")
$L.Add("\echo '-- expand top hit (e1) in AGE: graph<->vector linkage by shared id property'")
$L.Add('SELECT * FROM cypher(''aura'', $$ MATCH (e:Entity {id:''e1''})-[r]-(n) RETURN label(e), type(r), coalesce(n.name, n.content) $$) as (el agtype, rt agtype, nm agtype);')

$out = Join-Path $PSScriptRoot "03_hybrid.sql"
[System.IO.File]::WriteAllLines($out, $L)
"wrote $out ($($L.Count) lines)"