#!/usr/bin/env bash
# Fan the canary corpus out into every format the pipeline claims to accept
# (PRD amendment #115's synthetic gate corpus — no personal data, no network).
#
# The three MASTERS are generated by the document skills' own libraries, not here:
#   scripts/fixtures_gen/docx_fixture.js   docx-js       -> sample.docx  (justified)
#   scripts/fixtures_gen/xlsx_fixture.py   openpyxl      -> sample.xlsx  (banner + header on row 3)
#   scripts/fixtures_gen/pptx_fixture.js   pptxgenjs     -> sample.pptx  (canary whole on slide 2)
# This script only converts them, because LibreOffice is the only thing that
# writes the legacy BIFF/CFB formats an ordinary office still emits.
#
# Every file carries the same CANARY sentence verbatim, and that is the point: an
# extractor that reflows text still returns plausible content, and the failure only
# surfaces when an exact-phrase search finds nothing. MarkItDown passed a
# character-count check on a justified PDF while emitting 49.8 double spaces per
# 1k characters — more characters than a clean extractor, and unsearchable.
set -euo pipefail

out="${1:-scripts/fixtures/document_pipeline_e2e}"
img="${AURA_INGEST_IMAGE:-aura-ingest:local}"

for master in sample.docx sample.xlsx sample.pptx; do
  [ -f "$out/$master" ] || {
    echo "FAIL: $out/$master missing — generate the masters first:" >&2
    echo "  node scripts/fixtures_gen/docx_fixture.js $out/sample.docx" >&2
    echo "  python scripts/fixtures_gen/xlsx_fixture.py   (writes /out/sample.xlsx)" >&2
    echo "  node scripts/fixtures_gen/pptx_fixture.js $out/sample.pptx" >&2
    exit 1
  }
done

# `pwd -W` gives Docker a Windows path under Git Bash; the braces matter, because
# without them the `||` binds to the `cd` and both branches run.
abs="$(cd "$out" && { pwd -W 2>/dev/null || pwd; })"

MSYS_NO_PATHCONV=1 docker run --rm -i -v "${abs}:/out" --entrypoint bash "$img" <<'INNER'
set -euo pipefail
work=/tmp/fx
mkdir -p "$work"
cp /out/sample.docx /out/sample.xlsx /out/sample.pptx "$work"/
cd "$work"

conv() {  # conv <target-ext> <source>
  soffice --headless --convert-to "$1" --outdir "$work" "$2" >/dev/null 2>&1
  [ -f "${2%.*}.$1" ] || { echo "FAIL: soffice produced no .$1 from $2" >&2; exit 1; }
}

# Word master -> ODF, legacy CFB, RTF, and the justified PDF.
for ext in odt doc rtf pdf; do conv "$ext" sample.docx; done
# Spreadsheet master -> ODF, legacy BIFF, CSV.
for ext in ods xls csv; do conv "$ext" sample.xlsx; done
# Deck master -> ODF and legacy CFB.
for ext in odp ppt; do conv "$ext" sample.pptx; done

for f in sample.*; do cp "$f" /out/; done

cat > /out/GROUND_TRUTH.txt <<'GT'
CANARY: La sovranita appartiene al popolo che la esercita nelle forme e nei limiti della Costituzione.
SHEET:  header on row 3 under a merged banner; Codice | Quantita | Descrizione
SUM:    total Quantita = 24
CODE:   A9A26924 appears exactly once, with Quantita 11
NOTE:   sample.pptx slide 1 splits the canary across two text boxes ON PURPOSE.
        No extractor recovers a sentence split across text boxes; slide 2 carries
        it whole, and that is the case the gate asserts.
GT

ls -1 /out
INNER

echo "ok: fixtures in $out"
