package adaptive

import (
	"context"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

var (
	// ErrAdaptiveManageDenied reports a missing adaptive.manage capability.
	ErrAdaptiveManageDenied = errors.New("adaptive.manage capability is required")
	// ErrPromotionEvidenceRequired prevents promotion without a closed, eligible cohort.
	ErrPromotionEvidenceRequired = errors.New("eligible calibrated production evidence is required")
	// ErrProductionModelMismatch rejects evidence generated by a non-production model.
	ErrProductionModelMismatch = errors.New("canary evidence model does not match the configured production model")
	// ErrIllegalPolicyTransition rejects transitions outside the policy state machine.
	ErrIllegalPolicyTransition = errors.New("illegal adaptive policy state transition")
)

// PolicyService is the only mutation surface. It binds capability verification,
// a legal state transition, optional calibrated promotion evidence, the policy
// epoch update, and an append-only audit row in one PostgreSQL transaction.
type PolicyService struct {
	store             *PolicyStore
	productionModelID string
}

// NewPolicyService binds audited transitions to the configured production model.
func NewPolicyService(store *PolicyStore, productionModelID string) *PolicyService {
	return &PolicyService{store: store, productionModelID: strings.TrimSpace(productionModelID)}
}

// Transition performs a non-promoting state change. Canary and active are
// deliberately rejected here and can only be reached through Promote.
func (s *PolicyService) Transition(
	ctx context.Context,
	actorID uuid.UUID,
	expectedEpoch int64,
	next PolicyUpdate,
	reason string,
) (Policy, error) {
	if next.Mode == PolicyCanary || next.Mode == PolicyActive {
		return Policy{}, ErrPromotionEvidenceRequired
	}
	return s.transition(ctx, actorID, expectedEpoch, next, reason, nil)
}

// Promote evaluates the supplied closed cohort itself, checks that its model is
// the configured production model, then commits evidence+policy+audit atomically.
func (s *PolicyService) Promote(
	ctx context.Context,
	actorID uuid.UUID,
	expectedEpoch int64,
	next PolicyUpdate,
	batch CanaryBatch,
	cfg PromotionConfig,
	reason string,
) (Policy, error) {
	if s == nil || s.productionModelID == "" ||
		strings.TrimSpace(batch.ModelID) != s.productionModelID {
		return Policy{}, ErrProductionModelMismatch
	}
	if next.Mode != PolicyCanary && next.Mode != PolicyActive {
		return Policy{}, ErrIllegalPolicyTransition
	}
	report := EvaluatePromotion(batch, cfg)
	if !report.Eligible || !report.Promote || report.EvidenceSHA256 == "" {
		return Policy{}, fmt.Errorf("%w: %s", ErrPromotionEvidenceRequired, strings.Join(report.Reasons, "; "))
	}
	if report.PolicyVersion != strings.TrimSpace(next.Version) {
		return Policy{}, fmt.Errorf("%w: report policy %q != target %q",
			ErrPromotionEvidenceRequired, report.PolicyVersion, next.Version)
	}
	return s.transition(ctx, actorID, expectedEpoch, next, reason, &report)
}

func (s *PolicyService) transition(
	ctx context.Context,
	actorID uuid.UUID,
	expectedEpoch int64,
	next PolicyUpdate,
	reason string,
	report *PromotionReport,
) (Policy, error) {
	if s == nil || s.store == nil || s.store.pool == nil {
		return Policy{}, errors.New("adaptive policy service requires a database store")
	}
	if actorID == uuid.Nil {
		return Policy{}, ErrAdaptiveManageDenied
	}
	if strings.TrimSpace(reason) == "" {
		return Policy{}, errors.New("adaptive policy transition reason is required")
	}
	if err := validatePolicyUpdate(next); err != nil {
		return Policy{}, err
	}
	var evidenceID *uuid.UUID
	var evidenceModelID *string
	var evidenceCohortID *string
	var evidenceHash []byte
	var evidenceReport []byte
	if report != nil {
		reportJSON, err := json.Marshal(report)
		if err != nil {
			return Policy{}, fmt.Errorf("marshal promotion report: %w", err)
		}
		hash, err := hex.DecodeString(report.EvidenceSHA256)
		if err != nil || len(hash) != 32 {
			return Policy{}, ErrPromotionEvidenceRequired
		}
		id := uuid.Must(uuid.NewV7())
		evidenceID = &id
		evidenceModelID = &report.ModelID
		evidenceCohortID = &report.CohortID
		evidenceHash = hash
		evidenceReport = reportJSON
	}

	config := next.Config
	if len(config) == 0 {
		config = json.RawMessage(`{}`)
	}
	var updated Policy
	var updatedMode string
	if err := s.store.pool.QueryRow(ctx, `
SELECT epoch, policy_version, mode, rollout_bps, config, updated_at
FROM aura.apply_adaptive_policy_transition(
    $1::uuid, $2::bigint, $3::text, $4::text, $5::integer, $6::jsonb,
    $7::uuid, $8::text, $9::text, $10::bytea, $11::jsonb, $12::text
)`,
		actorID, expectedEpoch, strings.TrimSpace(next.Version), string(next.Mode),
		next.RolloutBPS, config, evidenceID, evidenceModelID, evidenceCohortID,
		evidenceHash, evidenceReport, strings.TrimSpace(reason),
	).Scan(
		&updated.Epoch, &updated.Version, &updatedMode, &updated.RolloutBPS,
		&updated.Config, &updated.UpdatedAt,
	); err != nil {
		return Policy{}, classifyPolicyTransitionError(err)
	}
	updated.Mode = PolicyMode(updatedMode)
	return updated, nil
}

func classifyPolicyTransitionError(err error) error {
	var postgresError *pgconn.PgError
	if errors.As(err, &postgresError) {
		switch postgresError.Code {
		case "40001":
			return ErrPolicyChanged
		case "42501":
			return ErrAdaptiveManageDenied
		case "23514":
			return fmt.Errorf("%w: %s", ErrIllegalPolicyTransition, postgresError.Message)
		}
	}
	return fmt.Errorf("apply audited adaptive policy transition: %w", err)
}
