package tools

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/chetto1983/aura/internal/identityctx"
	"github.com/chetto1983/aura/internal/mediagen"
)

// stagedMediaBasename is fixed so no caller-controlled text ever reaches the filesystem.
const stagedMediaBasename = "generated"

// mediaExtensions is the closed set of types generation delivers, not mime.ExtensionsByType:
// that answer depends on the host (Windows lists .jfif first for image/jpeg). An image's
// extension must round-trip through guessDeliveryMIME, which types the ingested asset; a video
// is already an asset of an accepted video type when it is staged, and is never ingested again.
var mediaExtensions = map[string]string{
	"image/png":     ".png",
	"image/jpeg":    ".jpg",
	"image/webp":    ".webp",
	"image/svg+xml": ".svg",
	"video/mp4":     ".mp4",
	"video/webm":    ".webm",
}

const uncheckedOptionsNote = "the model catalog is unavailable, so the options were not checked against the model; OpenRouter validates them"

// mediaResult is the model-facing summary of one delivered generation. CostUSD stays
// null when the provider reported no cost: unknown is not free.
type mediaResult struct {
	AssetID     string   `json:"asset_id"`
	MIMEType    string   `json:"mime_type"`
	Model       string   `json:"model"`
	CostUSD     *float64 `json:"cost_usd"`
	Used        any      `json:"used"`
	Adjustments []string `json:"adjustments"`
}

// mediaDeliveryOwner returns the identity a generated file will be delivered to, after
// checking everything stageMedia and ingestForDelivery need. A generation is paid, so a
// delivery that cannot happen must be refused before the provider is called: unlike
// send_file, there is no path-only fallback for a file that exists nowhere else.
func mediaDeliveryOwner(ctx context.Context) (string, bool) {
	owner := identityctx.IdentityID(ctx)
	tc, ok := toolCallCtx(ctx)
	if owner == "" || !ok || tc.sessionID == "" || tc.toolCallID == "" {
		return "", false
	}
	if _, err := mediaRunDir(ctx); err != nil {
		return "", false
	}
	return owner, true
}

func mediaRunDir(ctx context.Context) (string, error) {
	tc, ok := toolCallCtx(ctx)
	if !ok || !filepath.IsAbs(tc.runDir) {
		return "", errors.New("media staging needs an absolute run directory")
	}
	info, err := os.Stat(tc.runDir)
	if err != nil {
		return "", fmt.Errorf("media run directory: %w", err)
	}
	if !info.IsDir() {
		return "", fmt.Errorf("media run directory %q is not a directory", tc.runDir)
	}
	return tc.runDir, nil
}

// mediaCatalogEntry finds model in the catalog. An unreadable catalog is treated like a model
// the catalog does not list: no entry, so the request goes out unclamped, and one note, because
// refusing a paid call over a free lookup helps nobody. Any other catalog error is returned.
func mediaCatalogEntry(ctx context.Context, catalog *mediagen.Catalog, baseURL string, kind mediagen.Kind, model string) (*mediagen.Model, []string, error) {
	entry, err := catalog.Find(ctx, baseURL, kind, model)
	switch {
	case errors.Is(err, mediagen.ErrCatalogUnavailable):
		return nil, []string{uncheckedOptionsNote}, nil
	case err != nil:
		return nil, nil, err
	}
	return entry, []string{}, nil
}

// stageMedia writes generated bytes to a fresh directory under the run directory's tmp
// tree, the subtree the run-directory sweeper reclaims. The file must outlive Execute:
// channels open the descriptor's path after the turn returns.
func stageMedia(ctx context.Context, data []byte, mimeType string) (path, filename string, err error) {
	return stageMediaWith(ctx, mimeType, func(w io.Writer) error {
		_, err := w.Write(data)
		return err
	})
}

// stageExistingVideo stages an owned video asset for delivery, copied out of identity storage
// within maxBytes; the asset is never ingested again. A missing, foreign or deleted asset and
// one that is not a video are indistinguishable, as they are for references.
func stageExistingVideo(ctx context.Context, reader mediagen.ReferenceReader, owner, assetID string, maxBytes int64) (path, filename, mimeType string, size int64, err error) {
	if err := mediagen.ValidByteLimit(maxBytes); err != nil {
		return "", "", "", 0, err
	}
	rc, meta, err := reader.Open(ctx, owner, assetID)
	if err != nil {
		if ctxErr := ctx.Err(); ctxErr != nil {
			return "", "", "", 0, ctxErr
		}
		return "", "", "", 0, videoNotAvailable()
	}
	defer func() { _ = rc.Close() }()
	if meta.Modality != "video" {
		return "", "", "", 0, videoNotAvailable()
	}
	if meta.SizeBytes > maxBytes {
		return "", "", "", 0, videoTooLarge()
	}
	path, filename, err = stageMediaWith(ctx, meta.MIMEType, func(w io.Writer) error {
		copied, err := io.Copy(w, io.LimitReader(rc, maxBytes+1))
		size = copied
		if err == nil && copied > maxBytes {
			return videoTooLarge()
		}
		return err
	})
	if err != nil {
		return "", "", "", 0, err
	}
	return path, filename, meta.MIMEType, size, nil
}

func videoNotAvailable() *mediagen.Error {
	return &mediagen.Error{Code: "asset_not_found", Message: "The generated video is no longer available."}
}

func videoTooLarge() *mediagen.Error {
	return &mediagen.Error{Code: "too_large", Message: "The generated video exceeds the configured byte limit."}
}

func stageMediaWith(ctx context.Context, mimeType string, write func(io.Writer) error) (path, filename string, err error) {
	ext, ok := mediaExtensions[mimeType]
	if !ok {
		return "", "", fmt.Errorf("no staging extension for media type %q", mimeType)
	}
	runDir, err := mediaRunDir(ctx)
	if err != nil {
		return "", "", err
	}
	root, err := stagingRoot(ctx)
	if err != nil {
		return "", "", err
	}
	resolvedRoot, inside, err := fenceWithinRoot(runDir, root)
	if err != nil {
		return "", "", err
	}
	if !inside {
		return "", "", fmt.Errorf("media staging root %q escapes the run directory", root)
	}
	dir, err := os.MkdirTemp(resolvedRoot, "media-")
	if err != nil {
		return "", "", err
	}
	filename = stagedMediaBasename + ext
	path = filepath.Join(dir, filename)
	if err := writeStagedMedia(path, write); err != nil {
		discardStagedMedia(path)
		return "", "", err
	}
	return path, filename, nil
}

func writeStagedMedia(path string, write func(io.Writer) error) error {
	// #nosec G304 -- path is a fresh os.MkdirTemp directory joined with a fixed basename.
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return err
	}
	writeErr := write(f)
	if closeErr := f.Close(); writeErr == nil {
		writeErr = closeErr
	}
	return writeErr
}

// discardStagedMedia removes the directory stageMedia created for path.
func discardStagedMedia(path string) {
	_ = os.RemoveAll(filepath.Dir(path))
}

// mediaErrorResult maps an operational failure to its tool error. Only a coded
// mediagen.Error carries a message the model may read; any other error text can name
// infrastructure, so it is replaced.
func mediaErrorResult(err error) ToolResult {
	message := "Media generation failed."
	if mediaErr, ok := errors.AsType[*mediagen.Error](err); ok {
		message = mediaErr.Message
	}
	return errorResult(mediagen.ErrorCode(err), message)
}

// mediaArtifactResult emits the send_file artifact descriptor for a delivered generation.
// The caption is the original prompt; channels sanitize it for their own limits.
func mediaArtifactResult(ctx context.Context, path, filename, mimeType, assetID, prompt string, size int64, preview any) ToolResult {
	result, ok := mediaPreviewResult(preview)
	if !ok {
		return result
	}
	descriptor := map[string]any{
		"path": path, "filename": filename, "mime_type": mimeType,
		"asset_id": assetID, "caption": prompt,
		"tool_call_id": ToolCallIDFromContext(ctx), "size_bytes": size,
	}
	result.Meta = &ToolResultMeta{"artifact": descriptor}
	return result
}

// mediaPreviewResult encodes a generation summary as the model-facing result; false means it
// could not be encoded and the result is the job_failed error instead.
func mediaPreviewResult(preview any) (ToolResult, bool) {
	encoded, err := json.Marshal(preview)
	if err != nil {
		return errorResult("job_failed", "Cannot encode the generation result."), false
	}
	return ToolResult{Preview: string(encoded), Bytes: len(encoded)}, true
}
